### ISSUE TITLE
Blaze renders self-closing tags with attributes with / at the wrong place

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#1]
If there is in Blaze template such string:

```
<input foo={{foo}}/>
```

This is rendered as:

```
<input foo="/">
```

Instead of:

```
<input foo="">
```

Or:

```
<input>
```

I [see in the code some special handling](https://github.com/meteor/meteor/blob/devel/packages/html-tools/parse.js#L156) for non-self-closing tags of this situation. But for self-closing tags there is no special handling.

Inserting space solves the problem:

```
<input foo={{foo}} />
```

**Comment by mitar** [comment]
First issue claimed!

**Comment by stubailo** [comment]
Awesome!

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
