### ISSUE TITLE
failed to create or update project since today(09/19/2016)

### ISSUE THREAD

**Issue by oyyq99999** [meteor/blaze#104]
Sorry, it's network problems.. F*ck GFW!

But maybe you can make it clearer.

~~I set up meteor and created a project yesterday, everything works fine. Today I found `blaze-html-templates` has updates and I tried `meteor update`. After downloading `templating-compiler@1.2.15`, I got this error:~~
~~>/Users/myusername/.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/ddp/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^~~
~~Error: ENOENT: no such file or directory, open '/private/var/folders/t9/4wjd0vgx10x1rbvssjw99y140000gn/T/mt-1ix75kv/plugin.compileTemplatesBatch.os/program.json'
    at Error (native)~~

~~Then I tried to create another project from scratch with `meteor create another-project`, but got the same error.~~

~~I've checked the directory and found `/private/var/folders/t9/4wjd0vgx10x1rbvssjw99y140000gn/T` exists but not anything after that matches.~~

~~Seems no changes since yesterday, so I've no idea at all...~~

System: OS X 10.11.6
Meteor: 1.4.11
Node: 6.4.0

**Comment by mitar** [comment]
I cannot reproduce this:

```
$ meteor create meteor-test-blaze
Created a new Meteor app in 'meteor-test-blaze'.                                   

To run your new app:                          
  cd meteor-test-blaze                        
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                
                                              
$ cd meteor-test-blaze/     
$ meteor update
This project is already at Meteor 1.4.1.1, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
Newer versions of the following indirect dependencies are available:
 * autoupdate 1.2.11 (1.3.11 is available)    
 * ddp-client 1.2.9 (1.3.1 is available)      
 * ddp-server 1.2.10 (1.3.10 is available)    
 * http 1.1.8 (1.2.9 is available)            
To update one or more of these packages, pass their names to 
`meteor update`, or just run `meteor update --all-packages`.
$ meteor  
[[[[[ .../meteor-test-blaze ]]]]]          

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```

It might be a Meteor error. @tmeasday?
