### ISSUE TITLE
extending template instances

### ISSUE THREAD

**Issue by lucendio** [meteor/blaze#106]
Hi,

great to see further development on blaze is starting to happen.
In the past few year we all had some critics about blaze. Out of my personal understanding and needs I wrote some small extensions to the frontend of our beloved rendering engine. I thought, now might be a good time to share this work, just because it might contain some helpful and inspiring ideas for what blaze will become in the future.

nothing fancy, but maybe worth a look https://github.com/lucendio/meteor_extended-template-instance

/cc @mitar

**Comment by mitar** [comment]
Thanks for sharing this. I think the current idea of making templates be proper classes will make a lot of these things even easier to do.

I will close this ticket, but I did look your project. If you have any particular feature in mind which you think we should really consider, maybe open another issue for that particular feature.
