### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by alexandesigner** [meteor/blaze#107]
Currently I see a lot of good materials, articles and ideas written in blazejs, however, I see that some are either outdated (deprecated) or may not have a lot of information. I would like to propose the idea to create a publication in @medium and here we could discuss how do posts, posts and rules etc.. That could help both the new developers as even the most experienced.

@mitar 

> people could just submit posts they would like to be published under that banner? (Maybe the only requirement could be that guest posts have to be true, about Blaze, a good practice, and not too promotional for your own stuff.)
> but maybe even just simple things, maybe just things from the changelog, an example of a change and how this improves something, maybe shoutouts to projects using Blaze, things like that? 

_Let me know what you think..._

**Comment by mitar** [comment]
Moreover, @theadactyl is also inviting us to make a blog post to be featured on Meteor's blog.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
