### ISSUE TITLE
Explicitly declaring which arguments a component is receiving (as a dict)

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#108]
(Moving to an issue from #75, so that we can have a discussion about it.)

I think we should make this optional. So if you do not declare anything, you can pass anything, otherwise you can declare that it receives nothing, or some explicit arguments.

I would go with something similar to [validated method](https://github.com/meteor/validated-method) which allows various ways to do argument checking.

In a way, it would be just a method on the template class. Because you will be able to extend the class, you can use a different base class for your templates which is by default strict.

**Comment by tcastelli** [comment]
Yep validated method way seems nice and aligned to what is proposed on meteor guide(they do manual validation with simple schema but could be allowed directly by blaze with an interface for a validate function.

so yes sounds really useful +1

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
