### ISSUE TITLE
Inline event binding

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#109]
(Moving to an issue from #75, so that we can have a discussion about it.)

Personally, I would just do it like [Blaze Components does it](https://github.com/peerlibrary/meteor-blaze-components#handling-events). I am using this quite some time now and it works really well.

``` handlebars
<button onClick={{onButtonClick}}>Click me</button>
<button onClick="{{onClick1}} {{onClick2}}">Click me</button>
<button onClick>Click me</button>
<button {{attrs}}>Click me</button>
<button onClick={{onButtonClick 'first'}}>Click me</button>
<button onClick={{onButtonClick 'second'}}>Click me</button>
```

``` javascript
attrs() {
  return {
    onClick: this.onButtonClick,
    title: "Button title"
  }
}
```

**Comment by tcastelli** [comment]
I also like this style (especially when thinking about letting definitions of html and js being in a single file), but I see some limitations to this approach

- Some browsers do not support all the typical html embedded onClick, onChange, etc. 
- Not easy to use custom events

My idea to cover both would be something like

````
<button {{events click=onClick1  change=onChange7 custom=awesomeFunc }}>Click me</button>
````
so events could be a general helper that would loop through all the input arguments, and attach the appropiate event  handler to the element (some of them like click, change and so on should be already available so no need to create them).

I guess it will do something like this for custom events 

```
if (!event.library["custom"])
// Create the event.
event.library["custom"] = document.createEvent('Event');

// Define that the event name is 'build'.
event.initEvent('custom', true, true);

// Listen for the event.
elem.addEventListener('custom', function (e) {
  awesomeFunc(e);
}, false);

// target can be any Element or other EventTarget.
elem.dispatchEvent(event.library["custom"]);
```

**Comment by mitar** [comment]
> Some browsers do not support some of the html embedded onX events. 

No, this is just Blaze syntax. It has nothing with browsers. It is not rendered to DOM at all.

It works with custom events as well:

```
<button onCustomevent/>
```

Will handle `customevent` on the `button` by calling template method `onCustomevent`.

**Comment by tcastelli** [comment]
Oh my bad then, if it's just syntactic sugar for Blaze then I see no problems with the proposal :)

**Comment by mitar** [comment]
You can see [here how it already works in practice](https://github.com/peerlibrary/meteor-blaze-components#handling-events). Try it out there. :-)

**Comment by msavin** [comment]
IMO - this could be a nice package but not something for core. I think we should keep the core minimal. Perhaps we should consider what Blaze looks like, and what kind of packages we can offer to stack around it?

**Comment by tcastelli** [comment]
I think it is already in the core(template.events), this is just syntactic sugar to make it more convenient which can help the adoption of Blaze without needing extra biolerplate.

**Comment by mitar** [comment]
@msavin: In fact I think this should be core Blaze because from my preliminary measurements it is one of main optimizations we can do for Blaze rendering and removal times. Attaching event maps takes a lot of time because they go through jQuery, while inline event handlers go directly. (They are not just syntactic sugar, even if they look like that.)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
