### ISSUE TITLE
Allow <style> tag inside the blaze file

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#110]
(Moving to an issue from #75, so that we can have a discussion about it.)

[Similar to how Vue does it](http://vue-loader.vuejs.org/en/features/scoped-css.html).

Potentially, we could even support dynamic style:

```
<style>
  .button {
    width: {{width}};
  }
</style>
```

**Comment by tcastelli** [comment]
Not sure of how complex this will turn to be, but looks great to have <script> and <style> defined along the blaze template :)

**Comment by jhuenges** [comment]
I really like the idea. Especially the `<style>`-tag. Template scoped styles could save a lot of searching where what style class is located. The dynamic styling would be icing on the cake but I wouldnt prioritize it that high (I have no idea how difficult it would be to implement that feature).

**Comment by nathan-muir** [comment]
I like the idea of `<style>` tags, however I think dynamic/templated styles might be too ambitious [without something like css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)

1. Most importantly it should be treated as a separate file by the build system, so we can use `less`  or `sass` along with things like `less-autoprefixer` and things like minification.

2. A nice to have would be "scoped" selectors in the stylesheet - so that:

```
<style>
  .button {
    width: 10px;
  }
</style>

<template name="foo">
  <button class="button">Click</button>
</template>

```

gets compiled to (for illustrative purposes)

```
.button-168hxB8 {
  width: 10px;
}

<template name="foo">
  <button class="button-168hxb8">Click</button>
</template>
```

**Comment by msavin** [comment]
Agree - I think if we went the dynamic route, it should be built around CSS variables.

Maybe a better place to start is to allow us to define things in one file, for example:

```html
<style>
#button { 
  background: red;
}
</style>

<template name="button">
  <div id="button">Click Me</div>
</template>

<script>
Template.button.events({
  // ...
})
</script>
```

Meteor could compile things as if they were individual HTML, CSS and JS files.

**Comment by mitar** [comment]
> Agree - I think if we went the dynamic route, it should be built around CSS variables.

I agree. Let's start with static things first, then scoped things, and we can see about dynamic thing last.

But just imagine that you could write all CSS animations with Blaze instead of external libraries. :-)

> Maybe a better place to start is to allow us to define things in one file, for example:

This is what this ticket is about? Is this unclear?

So we are already talking about adding `<script>`, and now we are also talking about adding `<style>`. The end result will be exactly the thing above.

**Comment by msavin** [comment]
Ah - you know, I think I got mixed up last night. For some reason, I thought people wanted to run <script> inside their templates - that is something that confuses new Meteor developers. Then I saw dynamic CSS, and thought there is something else going on here.

I've thought about it some more as well - does anyone think <script> may confused actually developers, since it has its own meaning with-in pages? 

Additionally, since Meteor can support various file formats, maybe this could be the way to go?

```
<code extension="jsx">
// React component
</code>

<code extension="sass">
.chicken
  color: #idk000
</code>
```

**Comment by mitar** [comment]
> I've thought about it some more as well - does anyone think `<script>` may confused actually developers, since it has its own meaning with-in pages? 

Good question. Pose this question in #94.

> Additionally, since Meteor can support various file formats, maybe this could be the way to go?

Yes, but I was more thinking of using some other attribute with less typing. :-) Please read #94, because you are repeating things from there.

But this is why I need this pull request to implement other : https://github.com/meteor/meteor/issues/5936

The question for this issue here is how to implement it. `<script>` is easy because we are converting `.html` -> `.js` anyway with Blaze, so we can just add a bit more of JavaScript inline.

But can we do `.html` -> [`.js`, `.css`]` conversion with Meteor build tool? Can one file produces two output files? Is this supported?

**Comment by stubailo** [comment]
Yes a file can output as many different things as you want - assets, js, styles

**Comment by mitar** [comment]
Can it output a `.styl` file which would then be converted through plugin again to get to `.css`?

**Comment by stubailo** [comment]
Unfortunately no. It might be a good idea to add it, but that could have unknown performance implications once files have to do multiple passes through plugins.

**Comment by mitar** [comment]
But now we will have to do it manually. Which means that we will have to probably do caching ourselves. Probably it would be better if caching would be done by Meteor in place. So if I output from one file the same other file, and if it didn't change, then Meteor can just reuse the previous thing.

But OK. We need https://github.com/meteor/meteor/pull/5936 then.

**Comment by gcacars** [comment]
I hate this idea.
Is better to separate the concepts. CSS shouldn't stay with templates/HTML.
Maybe React could be used for who wants to do this.

**Comment by mitar** [comment]
But supporting this for those who would like it is probably OK, no? But I agree, one could see it as better not mixing styles with templates/HTML.

**Comment by gcacars** [comment]
> But supporting this for those who would like it is probably OK

Sure. But restrict this makes beginners think about the right thing, the concepts, let this not start with a few styles for one component and later grow up for all components. Makes bosses don't require the wrong thing :) (my think)

**Comment by mitar** [comment]
BTW, please also cast votes by upvoting/downvoting the opening comment on this issue. Then it is much easier to see support/opposition to ideas.

**Comment by antoninadert** [comment]
Where is this going? I really like the idea. Ideally this should also work in react components.

So how I see this: the Meteor's bundler / minifier system would look for all the < style> tags in all js files and it would append it to the final css. It would ve able to scope them with the scoped attribute as well

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
