### ISSUE TITLE
Ideas for optimizing Blaze

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#111]
Let's start collecting ideas how we could optimize Blaze better. (For more great discussion about this you can check discussions in #103 and #45. This issue is trying to distill and organize those discussions.)
- data context level, equality being what it is, which triggers reruns on any non-primitive value change:
  - possible solutions:
    - get rid of data context
    - allow custom data context with custom equality function
- tracker level, which is similar to data context level, but means that in general any reactive dependency might rerun more often than necessary (#68)
  - possible solutions:
    - using something like [computed field](https://github.com/peerlibrary/meteor-computed-field) to be precise about dependency changes
- no tracker caching level: if you have autorun with multiple dependencies, when one of those change, also other are recomputed, instead of previously returned value just cached and returned
- minimongo and array processing level: we want changes to be triggered only when data really changes, and only for those changes
  - #41
  - #69
- blaze data level (what you are talking about here, I think): that propagation of data through blaze might be ineffective and be done when data has not really changed
- HTMLJS materialization level: when HTMLJS does not really change, but Blaze still builds DOM elements and does diff against DOM
- interacting with DOM level: querying DOM for state is often expensive
  - for more information:
    - http://kellegous.com/j/2013/01/26/layout-performance/
    - https://www.sitepoint.com/incredibly-fast-ui-animation-using-velocity-js/
    - https://davidwalsh.name/css-js-animation
  - possible solutions:
    - ignore 3rd party changes in DOM and just trust the previous HTMLJS state and apply it blindly (should probably be configurable per template)
    - do rendering only inside the `requestAnimationFrame` when DOM is frozen and do not do layout trashing, see [example](https://github.com/DispatchMe/meteor-kernel)
- optimize `_.bind`
- it seems that observe sequence is still called even when non-reactive cursor is returned from a template helper: the reason is probably because template helpers depend on data context so it can potentially return different non-reactive cursors as it reruns, but maybe we could provide some way to return static arrays which we know will never change and then do not observe changes at all

**Comment by mitar** [comment]
I made [this test case for benchmarking the first rendering of Blaze](https://github.com/mitar/meteor-blaze-benchmark). Not updates. To have a baseline and see what we can improve.

**Comment by mitar** [comment]
@stubailo: Can you check if I am doing a React rendering in a reasonable way? I want to have it around so that I can compare.

**Comment by mitar** [comment]
It is interesting that React spends the same amount of time switching between two tables which are completely different and between one table and another which is only 50% different. I thought it will a diff and replace only 50% of those DOM elements, so spend around 50% less time.

**Comment by nathan-muir** [comment]
@mitar I wonder how [mobx (previously mobservable)](https://github.com/mobxjs/mobx) would fare instead of `tracker` - 

[> MobX builds a virtual derivation graph to minimize the number of recomputations needed to keep derivations in sync with the state.](https://medium.com/@mweststrate/becoming-fully-reactive-an-in-depth-explanation-of-mobservable-55995262a254)

I think it might solve issues in Blaze regarding re-rendering inner vs, outer templates; by figuring out which computations the others depend on and re-computing those first.

**Comment by mitar** [comment]
I have no idea about that one. Feel free to investigate. :-) But I think we might have some other low-hanging fruits first.

**Comment by mitar** [comment]
One interesting test case to test against: https://github.com/meteor/meteor/issues/3733

**Comment by mitar** [comment]
Tracker is used a lot in Blaze. I am seeing that every time a computation is rerun, `withNoYieldsAllowed` is called. This could be probably called only once at the beginning when computation is constructed.

**Comment by janat08** [comment]
DOM caching:
https://gist.github.com/arunoda/9e3997d9c8d8d73a16f7
https://forums.meteor.com/t/making-blaze-faster/5762/22

**Comment by janat08** [comment]
You heard my complaints about setter/getter not working with arrays, while blaze only renders array lists, and so perhaps we could consider switching to proxies as you explained was my true solution.

**Comment by janat08** [comment]
hyperhtml is pretty fast and weights nothing with basic api such that it supports all the browsers. Uses template literals.

**Comment by janat08** [comment]
Anyway blaze slowness is due to rendering or tracking?

**Comment by jeffm24** [comment]
@mitar Are you still willing to take some PR's on some of these issues? I am currently working on a project that is a bit stuck with Blaze, and I would be willing to give a shot at implementing some quality of life stuff.

I think there are a few things that can be done fairly easily that would be great improvements:

1. Update Blaze.With to use a dictionary of key -> ReactiveVar in addition to the single ReactiveVar for the entire context.
2. Update Template.Instance constructor in the following ways:
    - Cache the corresponding 'with' data view inside of its own view. This makes it so that the instance can access its own data context internally without having to search up the tree for it (like Template.currentData currently does).
    - For backwards compatibility, create internal 'data' property by iterative through the current data context and resolving all key ReactiveVar values so that it is a plain dictionary like before.
3. Add Template.Instance getData([key]) method that accesses the internal data view directly and reactively gets context data
    - If a key is provided, it will use the key -> ReactiveVar dictionary to resolve the value so that it is only dependent on that key. Otherwise, it will use the whole context ReactiveVar (equivalent to Template.currentData except specified to the current template).
    - If the key does not yet exist in the context, a ReactiveVar will be created for it and depended on.
4. **(Breaking Change)** Make 'this' context for helpers and events be the current Template instance.
    - This would make these blocks consistent with the onCreated/Rendered/Destroyed blocks and, most importantly, have the benefit of completely stopping the need for re-rendering the entire template when the data context changes by making 'this' a constant that never needs to be updated.
    - This is a breaking change, but shouldn't be too hard to migrate in most projects because of the ease of searching for helpers and events blocks. Essentially all 'this.prop' accesses would need to change to this.getData('prop').
5. Add a 'computed' method to Blaze.Template that functions similarly to helpers with the following differences:
    - Computation functions would be autorun (so they take no parameters) and their values would be stored (similarly to the data context) in a dictionary of key -> ReactiveVar within the current Template instance view
    - We could implement a 'getComputed' method in Template.Instance that accesses the dictionary by key and returns the value of the corresponding ReactiveVar. It would also start the autorun for that computation if necessary.
    - So that they are accessible from Spacebars, for every computation initializated, we could create a corresponding function in __helpers that would just call this.getComputed(name). This means that computations and helpers share the same namespace, but I don't think that should be much of an issue.
    - This method would greatly reduce the need for caching the returns from helpers via #let blocks and should be more efficient than that, since it doesn't need to traverse to search the lexical scope.

I have already implemented most of these things in my own project by just overriding the default Blaze functions, but I think it would be worthwhile to implement them into the official codebase. In addition, the only breaking change would be the helper/event context, but again that wouldn't be too hard for most users to migrate anyway. Let me know what you think if you get the chance to look through this or if I've missed something/not explained clearly enough.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
