### ISSUE TITLE
Blur events not firing on iOS Safari

### ISSUE THREAD

**Issue by arggh** [meteor/blaze#117]
Blur events, at least on `input` and `textarea` elements, are not firing when they should on **iOS Safari 10.0.1** (possibly other versions as well).

### Expected behavior: ###

When interaction with an input element ends and user taps 'DONE' above the virtual keyboard, input should lose focus.

### Observed behavior: ###

Keyboard is hidden, but the input stays in focus and no blur events are fired.

### How to reproduce: ###

- 1. Create an empty meteor project
- 2. Add this html (css only to visualize the behavior) to project

**html**
```
<form>
   <input type="text" onblur="console.log('not gonna fire')"/>
</form>
```

**css**
```
input:focus {
   border-color: red;
}
```

- 3. Open the page, tap on the input -> keyboard appears and the input has a red border
- 4. Tap 'Done' to close the keyboard
- 5. **Input stays in focus** = no log in console and the border stays red, but the keyboard disappears

********

Doing the same experiment with a regular html document produces the expected end result (blur event firing and the input losing focus).

It doesn't matter if we use inline `onblur` or Blaze Template event mappings. I'll test on iOS 10.0.2 briefly which is downloading to my phone right now.

This causes a really annoying side effect, when submitting forms. After tapping the submit button, the virtual keyboard is shown and then immediately hidden again.

**Comment by arggh** [comment]
Updating to iOS 10.0.2 fixed this 🎉

**Comment by mitar** [comment]
So we can close this?

**Comment by arggh** [comment]
Would be nice to know what specifically caused it, but of course there's no guarantee of any benefit in researching further. I'm closing this.
