### ISSUE TITLE
template-class branch 

### ISSUE THREAD

**Issue by rwatts3** [meteor/blaze#118]
I couldn't help but to notice the template class branch.  Is this a step in the direction of components with blaze ? 

Nice work btw !!

**Comment by mitar** [comment]
Yes. Please see pull request here: https://github.com/meteor/blaze/pull/116

Please test it. Please provide feedback/comments at #98 and #116.

**Comment by rwatts3** [comment]
This is awesome Mitar. I am happy to do so.  My apologies for the
rudimentary question but is there a specific step I must take to use this
version of the packages vs. The one pulled from atmosphere.  Other than
placing the directories in my packages folder.

**Comment by mitar** [comment]
I [documented how to run Meteor with unpublished Blaze versions](https://github.com/meteor/blaze/blob/master/CONTRIBUTING.md).
