### ISSUE TITLE
Class method: triple braces processing

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#119]
Currently, triple brackets send through raw HTML. This is very dangerous. But in practice, it is pretty limited what an app is using them for. For example, I do not believe anyone uses it to inject script tags on the fly. It is mostly used to add some simple markup like bold and stuff. So we could be doing some simple sanitization.

We could offer a class method which where you could hook into and decide how you want to process the content before it goes output through triple braces.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
