### ISSUE TITLE
Cannot check for inverse of statement

### ISSUE THREAD

**Issue by patrickml** [meteor/blaze#12]
Say I have a helper function made to check if I am the current user in a loop like so:

~~~
{{#if currentUser user=user}}

//code

{{/if}}
~~~

I cannot check for the inverse

~~~

{{#if !currentUser user=user}}

//code

{{/if}}
~~~

Normally you would use else if you had something else to show but in my case I do not and this doesn't work

~~~

{{#if currentUser user=user}}
{{else}}

//code

{{/if}}
~~~

**Comment by gabrielhpugliese** [comment]
http://docs.meteor.com/#/full/blaze_unless

**Comment by patrickml** [comment]
Thank you I didn't realize this existed!
