### ISSUE TITLE
Class method: shouldRecreate

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#120]
We could add reactive method `shouldRecreate` which would force a template to be recreated from scratch. This is useful to help with integration with 3rd party plugins where it would be too complicated to hook into detecting changes of data, cleaning jQuery plugin, and re-initializing it.

One could simply have a condition on data in that method, and if it changes to `true`, Blaze recreates the whole thing for you.

Of course this could make things more inefficient than necessary, but code can be much simpler. Probably it should be used only on leaf templates.

**Comment by msavin** [comment]
I'm all for this functionality. We need to a way to "reset" a template if its being modified by a library, stuff like content-editable, etc.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
