### ISSUE TITLE
List of reserverd top-level tags

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#121]
Now that we are moving to one-file style, some tags should be reserved for special meaning. Keep in mind that we should consider both current and future use. (It is better that we reserve them now, even if we do not end up using them, then having issues later on with backwards compatibility.)

Please help me create such list.

For now I was thinking of reserving:
- `template`
- `body`
- `head`
- `style`
- `import`
- `module`
- `export`
- `group`

Any other?

The idea is that any other top-level tag would represent the base class. So:

```
<template is="Component">
```

Would be the same as:

```
<component>
```

So anything except those reserved tags would get internally translated in the above manner.

**Comment by stubailo** [comment]
I'm confused - why would we allow arbitrary top-level tags?

**Comment by mitar** [comment]
So we are moving to class-based templates. So you want to be able to configure easily which class should serve as your base class. And so because you do not want to use `<template is="Component">` all the time, it is much smoother if you could write `<component>` instead, for the same effect.

**Comment by stubailo** [comment]
Hmm, interesting - I guess it's not so bad because we can always add more restricted things and it's not a huge code change for people to just rename one component.

**Comment by mitar** [comment]
True. But I also think we can reserve anything we consider we could need to use in the future.

Maybe we should also reserve any HTML tag name?

So please no:

```
<p name="paragraph">
```

I do not want to go with custom elements limitation on having to use `-` in the name.

**Comment by mitar** [comment]
Oh, while writing #122 I got an interesting idea. Maybe we should simply require all custom tags to start with upper-case letter. This is a bit like Go. So lower case is reserved. But you can start with upper case.

That could nicely match with JavaScript as well (where common style is to have class names in `CamelCase`).

So you would have to write:

```
<Component>
```

**Comment by tcastelli** [comment]
Yes!

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
