### ISSUE TITLE
Converting class namest to template tags

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#122]
So, we are introducing class templates slowly. I hope to be able to achieve that we can use different base classes easily for templates. So that one could say:

``` handlebars
<template is="Component">
```

Which would make JavaScript class `Component` the base class for the content in that template.

The thing is, I would also like to be able to specify this in a shorter form, like:

``` handlebars
<component>
```

Now, the question is:
- should we require top-level tags to be case sensitive?
- should we just use class names, or convert them to kebab-style?

For example, if I have a class name `FooComponent`, should the tag be:

**Comment by mitar** [comment]
```handlebars
<FooComponent>
</FooComponent>
```

**Comment by mitar** [comment]
```handlebars
<foocomponent>
</foocomponent>
```

**Comment by mitar** [comment]
```handlebars
<foo-component>
</foo-component>
```

**Comment by mitar** [comment]
Vue is converting between CamelCase to kebab-case between HTML and code. I like that. But they also have to do that because their templates are often part of HTML. Also, HTML is not case sensitive, so they have that issue as well. We do not.

[Interesting discussion](https://github.com/vuejs/vue/issues/2308).

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
