### ISSUE TITLE
Allow Event Maps to Handle Keycodes

### ISSUE THREAD

**Issue by JelaniThompson** [meteor/blaze#123]
Hey there! I'm working with an application that needs to track backspaces for a character count and isn't supported by 'keypress'.

The only way I have of tracking backspace right now is [this](http://stackoverflow.com/questions/8222809/recognize-the-backspace-and-spacebar-with-jquery) and I don't like the idea of changing the way I have to handle events specifically for one key. Am I missing something vital or would you support the addition of a better way to handle keycodes within event maps? 

[Event maps documentation](http://blazejs.org/api/templates.html#Event-Maps)

**Comment by mitar** [comment]
I do not think this should be done at the event maps level (their syntax is already complicated). I would just make it so that you count on `keyup` and this is it?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
