### ISSUE TITLE
Rich event support for Blaze

### ISSUE THREAD

**Issue by msavin** [meteor/blaze#125]
Blaze has very nice event support, but I found it quite lacking when compared to React: https://facebook.github.io/react/docs/events.html

They have cool things like:
- Media Events: onCanPlay, onPause, onPlay, etc
- Image events: onLoad, onError
- Touch events
- etc

Additionally, maybe even things like template render or destroy can be considered as an event rather than having its own API.

``` javascript
Template.blogPost.events({
  'render': function () {
   //..  
  },
  'onPlay': function () {
    //.. trackAnalytics()  
  },
  'onScroll': function () {
    // ..
  },
  'click .save': function () {
    // .. 
  }
});
```

Looking at DOM event support (see: https://developer.mozilla.org/en-US/docs/Web/Events), there's even more cool stuff:
- on cut, copy, paste, select
- SVGResize, etc

While on the subject, I thought I would mention with touch events, we have to be very careful because they are blocking in some cases and can fire off many, many times (i.e. when swiping over an element). Performance is huge here.

**Comment by mitar** [comment]
Doesn't Blaze support any event?

**Comment by laosb** [comment]
I was thinking that Blaze supports every kind of events.

**Comment by NitroBAY** [comment]
Oh ya ? It supports also resize ? Because I finally opted for jQuery few month ago, I didn't find it was suppported.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
