### ISSUE TITLE
Make this of template.subscribe be template instance

### ISSUE THREAD

**Issue by elpddev** [meteor/blaze#130]
Hi, I am must be missing something.

In the [docs](http://blazejs.org/api/templates.html#Blaze-TemplateInstance-subscribe), the way to use subscribe is:

`this.subscribe("notifications");`

But when I tried that and when I dive into the code, its seems the correct way it to wrap the calls in an array. If not, I get "TypeError: CreateListFromArrayLike called on non-object" error. That is because of the usage of the "apply" functionality.

`this.subscribe(["collectionName", param1])
`

Blaze view.js:

>   Blaze.View.prototype.subscribe = function (args, options) {
>   ...
>   subHandle = Meteor.subscribe.apply(Meteor, args);

https://github.com/meteor/blaze/blob/master/packages/blaze/view.js#L250
https://github.com/meteor/meteor/blob/dce2b20ddbe45da48c37f26813fce8d0c72d8c88/packages/ddp-client/livedata_connection.js#L539

**Comment by mitar** [comment]
The docs are for template instance. You seem to be calling subscribe on a view directly?

**Comment by elpddev** [comment]
Yes, it was on my part. In an autorun section, the "this" refers to the view from what I see now. 
Thank you for responding.

**Comment by stubailo** [comment]
Wow, that's surprising! One way to fix it is to use arrow functions so that 'this' is always what you expect.

**Comment by mitar** [comment]
Personally, I would break compatibility here and just make `this` a template instance.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
