### ISSUE TITLE
Use blaze syntax inside html that is stored in database

### ISSUE THREAD

**Issue by cloudrocketsoftware** [meteor/blaze#133]
Hi guys,

We're using Blaze as part of MeteorJS. And I'm looking for a way to allow my client to update strings/text on our website using some sort of edit-in-place functionality. The Meteor plugins for such a feature already exist, but the thing is: we're using i18n to show translated content.

What would be the best way to allow logged in admin users to change the static strings on the website? I already came up with the idea similar to how most CMS work: store the HTML of editable parts of a page in the db with a Tapi18n collection. But this would only work with content that is exclusively static. But a lot of times we use Blaze syntax inside our page content.

This poses an interesting challenge: would it be possible to have Blaze syntax in HTML that is stored inside db?

**Comment by mitar** [comment]
I think this could be a major security challenge. Blaze was not really designed to be used on untrusted content.

**Comment by mitar** [comment]
But yes, having a function which takes a string and compiles it to a Blaze template should probably be provided.

**Comment by mitar** [comment]
Closing for now. I think another issue could be opened for providing runtime template compilation.

**Comment by mitar** [comment]
And that is probably #21.
