### ISSUE TITLE
Blaze: helpers do not work for <body> attributes

### ISSUE THREAD

**Issue by WayneUong** [meteor/blaze#136]
I have `<body class="{{bodyClasses}}">...</body>` in code, and it shows exactly `<body class="{{bodyClasses}}">...</body>` in the browser without replacing `bodyClasses`.

I have tried `bodyClasses` as both a global helper and a `Template.body` helper, same result.

**Comment by stubailo** [comment]
I think this is specifically in the case of attributes, right? Helpers inside the content of `<body>` should work correctly if I'm not mistaken.

**Comment by WayneUong** [comment]
you are right.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
