### ISSUE TITLE
`Template.instance()` is `null` in nested helpers.

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#140]
Migrating this over from meteor/meteor#4035 (reported by @xbtsw, currently has 12 upvotes).

---

When the helper is a nested dictionary, `Template.instance()` inside the helper will return `null`

To reproduce:
`meteor create app`

change `app.js` and `app.html` as follows:

``` js
//app.js


if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.hello.helpers({
    c: {
      counter: function () {
        //below line will throw exception since Template.instance() is null
        var data = Template.instance().data;
        return Session.get('counter');
      }
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
    }
  });
}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup
  });
}
```

``` html
<!-- app.html -->

<head>
  <title>app</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{c.counter}} times.</p>
</template>
```

If we remove the extra level in helper dictionary:
i.e. change `c.counter` to `counter` then `Template.instance()` will behave normally.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
