### ISSUE TITLE
Guide/Example or Instructions for Publishing a Blaze Components to Npm

### ISSUE THREAD

**Issue by rwatts3** [meteor/blaze#142]

**Comment by rwatts3** [comment]
Greetings 

I would like to know of there is a guide or instructions anywhere that provides a workflow for creating a library of components for others to use.  Similar to Polymer Paper and react components.  I feel that by doing this and creating more components for the rear of the is community to use will help drive people to blaze.

**Comment by mitar** [comment]
Some information is available [here](http://blazejs.org/guide/reusable-components.html). But Blaze is currently not very strong in reusable components. There is [an extension](https://github.com/peerlibrary/meteor-blaze-components) I made which makes components a bit easier to do.

**Comment by rwatts3** [comment]
Thank you.  Any information as to publishing outside of atmosphere

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
