### ISSUE TITLE
Click event handlers are sometimes not triggered

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#143]
Migrating this confirmed bug over from meteor/meteor#2850. I've documented a temporary workaround in the original issue (originally reported by @mitar).

---

See [example project](https://github.com/mitar/meteor-issue2850). Open it (always open clean, not with hot-reload, to make reproduction clear):
- open Developer Tools
- click on "Sign in"
- document level line appears in the console
- click anywhere in the opened dialog (for example, email input form)
- both template level and document level lines appear in the console
- click on "Create account"
- only document level line appear in the console

This is unexpected. What would be expected is that both template level and document level events would be triggered in all cases. Click on a template is click, no? Why template level clicks are not triggered in those two cases above (clicking on "Sign in" and clicking on "Create account").

**Comment by mitar** [comment]
Can you also post a workaround here?

**Comment by hwillson** [comment]
Sure thing (copied from https://github.com/meteor/meteor/issues/2850#issuecomment-256926722):

... A quick workaround to this problem is to register login button/link click events in a Template onRendered callback, instead of within the Template's event map. For example, modify @mitar's repro as follows:

**test-events.js**

```
if (Meteor.isClient) {
  $(document).on('click', function (event) {
    console.log("document level", event);
  });

  Template.loginButtons.onRendered(function onRendered() {
    this.$('#login-buttons').on('click', (event) => {
      console.log("template level", event);
    });
  });

  // Template.loginButtons.events({
  //   'click': function (event, template) {
  //     console.log("template level", event);
  //   }
  // });
}
```

This will make sure the Template level click event is triggered on all login elements.

The above workaround is clearly a hack though ...

 (so this issue is still open)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
