### ISSUE TITLE
Active developement routers

### ISSUE THREAD

**Issue by rezaxdi** [meteor/blaze#144]
What are the active development meteor routers that work with blaze ? Or what are you guys using ?

**Comment by aadamsx** [comment]
> active development meteor routers that work with blaze 

There is none these days.  

If you're going to use:
* Blaze, use FlowRouter (no longer maintained)
* Vue, vue-router
* React, react-router

**Comment by mitar** [comment]
I use FlowRouter. To me it seems like a stable thingy which does not really have to be maintained much.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
