### ISSUE TITLE
What do bad index means

### ISSUE THREAD

**Issue by NitroBAY** [meteor/blaze#145]
I used to use easysearch but because grounddb was updating too fast my collection, it was updating too fast the DOM (I think) causing a lot of `Error: Bad index in range.removeMember: 0 Error: Bad index in range.removeMember: 1` etc. I created my own search engine but still I have these range.removeMember + a number in my log and my UI doesn't work as expected.
But what does that means ??

**Comment by NitroBAY** [comment]
The thing that is very problematic here is that once there's a removeMember error blaze stops updating like it should the part of my app which causes the 'trouble'. So can you stop making removeMember breaking ??

**Comment by mitar** [comment]
Please create a small reproduction.

**Comment by NitroBAY** [comment]
https://bitbucket.org/NitroBAY/worksheets can I share my full project because it's faster to me or to you really want a small repro ?

**Comment by NitroBAY** [comment]
Okay

**Comment by NitroBAY** [comment]
This bug happens only with grounddb and therefore is kinda related with #146, I made a reproduction repository for both 

> Hello this bug is only with grounddb's collection (maybe it update the collection too frequently) but it also caused by Blaze so it's not only up to grounddb as it fournish an iterable collection for Blaze's each. I have this problem since weeks, made hours to made this repro as simple as possible for you I hope you'll help me. Don't forget to see the readme.md
>  https://github.com/NitroBAY/ground-blaze-bug-repro

**Comment by NitroBAY** [comment]
dispatch:kernel added by ground:db was causing this issue.
