### ISSUE TITLE
#each sometimes keeps old elements

### ISSUE THREAD

**Issue by NitroBAY** [meteor/blaze#146]
```
    {{#each worksheetsResult}}
      <div class="col s12 m6 worksheet-card">
        <a href="/worksheet/{{_id}}">
          <div class="card">
            <div class="card-content">
              <div class="center-align">
                <span class="card-title {{#if isModified this}}green-text{{/if}}">{{title}}</span></div>
              <div class="text-container">
                {{#if visual content}}
                  <p class="center-align"><span class="mdi mdi-pencil visual-warning
                       {{#if this.isModified}}green-text{{/if}}"></span></p>
                {{else}}
                  {{{textualContent this.content}}}
                {{/if}}
              </div>
            </div>
          </div>
        </a>
      </div>
    {{/each}}
```
worksheetsResult has only one object `{category: "9", content: "<p>Mondial</p>", title: "Le supplément", updatedAt: Tue Oct 25 2016 00:18:42 GMT+0200 (Paris, Madrid (heure d’été)), _id: "itrpKqCHkaiGPD5mK"}`
But after the url changes I changes the query for find() and so I have 3 objects so one could think that there will be 3 elements in the UI but not always (sometimes gods are with me and it's working but sometimes it's not working), sometimes I have 3 elements + the old one.
http://imgur.com/a/aNld8
The card in the bottom left should have disappeared as I only want the 3 new object in worksheetsResult to be here but it's still here. Like if blaze has memory disorders and sometimes forget to clean old cards before showing new one.

**Comment by mitar** [comment]
Please create a small reproduction showing this issue.

**Comment by NitroBAY** [comment]
Hello this bug is related to grounddb (maybe it update the collection too frequently) but it also caused by Blaze so it's not only up to grounddb. I have this problem since weeks, made hours to made this repro as simple as possible I hope you'll help me. Don't forget to see the readme.md
 https://github.com/NitroBAY/ground-blaze-bug-repro

**Comment by NitroBAY** [comment]
raix's dispatch:kernel was causing this issue
