### ISSUE TITLE
Need a way to stop reactive updates on a template

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#147]
Migrating this open issue over from meteor/meteor#2031 (created by @avital). 

---

(Originally reported by @tmeasday) Sometimes apps want to explicitly opt-out of the automatic page updates.

This is also related to meteor/meteor#2023 -- right now there's no way to stop Deps computations that control live updates on a template. This introduces memory leaks and degraded performance over time (unless you always use jQuery to remove elements).

**Comment by mitar** [comment]
I am not sure if this is really needed, once you move away from using data contexts and start using things like [reactive fields](https://github.com/peerlibrary/meteor-reactive-field) on a [Blaze component](https://github.com/peerlibrary/meteor-blaze-components). See [demo here](http://components.meteorapp.com/) how you can stop reactive updating a template when a form input field has a focus, for example.

**Comment by mitar** [comment]
So I am in favor of closing this because one can attach such field to a template instance and then access it from inside a template helper as well.

**Comment by mitar** [comment]
Related: https://github.com/meteor/meteor/issues/3976
