### ISSUE TITLE
Allow nested template.autorun calls

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#148]
For some reason this is not allowed. I do not understand why. I think something like this should be supported:

```js
template.onCreated(function () {
  this.autorun(() => {
    this.autorun(() => {
      // do something
    });
  });
});
```

Ideally, the following would be equivalent:

```js
template.onCreated(function () {
  this.autorun(() => {
    Tracker.autorun(() => {
      // do something
    });
  });
});
```

But this would then be a solution for this as well: https://github.com/meteor/meteor/issues/4494

**Comment by zimme** [comment]
What would happen if the outer computation is invalidated in this case? Would it stop and and re-initiate a new inner computation or would it just create new computations for each re-run?

**Comment by zimme** [comment]
Also, if that code would be equivalent with the code that you suggested, would the inner computation be destroyed with the template?

**Comment by mitar** [comment]
So this is already implemented. The inner computation is recreated. This is how it works normally in Tracker. And yes, inner computation is destroyed with the template (as a consequence of outside computation being invalidated).

So there is some cost of using nested autorun, but I do not see a reason to prevent it. It might not be good in your case to do it, because creating a computation does cost a bit, but there are also reasons (like [computed field](https://github.com/peerlibrary/meteor-computed-field)) when this is useful because you do want to cache an expensive computation inside another computation.

**Comment by zimme** [comment]
Thanks, just wanted to know how this work s a bit closer :)
