### ISSUE TITLE
After upgrading to 2.2.0, <input> tag 'readonly' attribute is not rendered

### ISSUE THREAD

**Issue by jancurn** [meteor/blaze#151]
Hi there, after I upgraded blaze@2.1.9 to blaze@2.2.0 in our Meteor app, the 'readonly' attributes on <input> tag are no longer rendered. This only happens if the tag has some dynamically generated attributes, for example:

```	  
<input type="text" readonly value="{{todo.text}}">
```

This one works correctly:
```	  
<input type="text" readonly>
```

I replicated the problem also in "Todos" example app. I cloned the repo from https://github.com/meteor/todos, updated meteor and all packages to their latest versions and have the same problem (actually I tested the above code in Todos app). When I downgraded to blaze@2.1.9, readonly attribute is rendered (although not as boolean attribute like 'disabled', but that's another story). Strangely enough, other attributes like 'disabled' are rendered normally.

**Comment by mitar** [comment]
So this might be related to #102. @gcacars, could you take a look?

@jancurn: could you make a pull request with a test to Blaze to test for this case? Are we missing a test for this?

**Comment by jancurn** [comment]
re @mitar: I will try to add some test, although not sure when I find time for it :-/

**Comment by thearabbit** [comment]
I have the same problem
```js
// Work fine for blaze 2.1.9, but now don't work
{{> afQuickField name='branchId' readonly=true}}
```
How to fix?

**Comment by gcacars** [comment]
I done some tests with my project.

```
Template.login.helpers({
	attrs(){
		return {
			readonly: false
		};
	},
	
	test(){
		return false;
	}
});
```

`<input class="form-control" type="text" name="username" {{attrs}} disabled="{{test}}" required>
`

Every helper like `disabled` (helper in attribute) works fine.
But nothing in `attrs` works correctly.
I think that Blaze do something different with dynamic attributes.
@mitar Could you help with this? Where in the code Blaze treat this.

I also test an input like jancurn said:
`<input type="text" readonly value="{{todo.text}}">`

For me works fine.

**Comment by thearabbit** [comment]
Thanks, but I use `AutoForm` so I can't use like this
```js
Template.login.helpers({
    attrs(){
        return {
            readonly: false
        };
    },
});
--------
{{> afQuickField name='branchId' attrs}}
```
Could you help me?

**Comment by mitar** [comment]
@gcacars: Maybe [here](https://github.com/meteor/blaze/blob/53ed6b0ff9487ca5be441ca04d29517fef5e2bf2/packages/htmljs/html.js#L225) or [here](https://github.com/meteor/blaze/blob/32bc04764dffa13620833debde893e9be9d91808/packages/blaze/view.js#L483)?

But where does your pull request interfere with that?

**Comment by thearabbit** [comment]
Now I downgrade to `2.1.9`

**Comment by bharathkeshav12** [comment]
@thearabbit - Could you please tell me how you downgraded to 2.1.9?

**Comment by thearabbit** [comment]
please look it
```js
.meteor/
   versions
```
And then find the `blaze@2.1.9`

**Comment by jancurn** [comment]
hey guys, I wanted to write a test for this bug, but I wasn't able to find out how to run tests in this project...

**Comment by mitar** [comment]
One approach is explained in #70. What I do is I configure `METEOR_PACKAGES_DIRS` to `packages` directory of this repository. And then I run from a package I am testing (like `blaze`):

```
meteor test-packages ./
```

**Comment by gcacars** [comment]
@mitar I put a break point inside `Blaze._makeAttributeHandler` and `BooleanHandler` but nothing hits both break points, I don't know why.
I will take a look in this `HTML.flattenAttributes`.

**Comment by gcacars** [comment]
With the [same example](https://github.com/meteor/blaze/issues/151#issuecomment-261107280), the debug shows me:

![image](https://cloud.githubusercontent.com/assets/1190940/20450942/8ea7f904-addb-11e6-8a48-db537bf1729a.png)

The first object is the attributes declared in HTML. But `disabled` have a null value here (in helper, this value is `false`, but I think that helper do your job later). The second object is the dynamic attributes, with `readonly false` as set in helper object.

![image](https://cloud.githubusercontent.com/assets/1190940/20450991/152db720-addc-11e6-90f8-bbf3bef51d22.png)

But HTML.isNully don't interpret the value false as nully, adding it to the list that render attributes. So HTML is still rendered in the wrong way with `readonly="false"`.

![image](https://cloud.githubusercontent.com/assets/1190940/20451086/d5e6a422-addc-11e6-8769-48d0e357ecdf.png)

The final result object is:
![image](https://cloud.githubusercontent.com/assets/1190940/20451098/ef344d9e-addc-11e6-9be3-3d1dd2225901.png)

`Blaze._makeAttributeHandler` (pull request change) never was called.

**Comment by gcacars** [comment]
Maybe other commit is impacting. `checked` is not working too.

**Comment by mitar** [comment]
@gcacars: Any progress on fixing this?

**Comment by serkandurusoy** [comment]
People are reporting success with changing the attribute name from `readonly` to `readOnly`, which makes sense since that's the actual name on the dom object when fetched using the javascript api.

So if perhaps this is a case sensitivity issue, can't we just make the name comparison in https://github.com/meteor/blaze/blob/95d68da33faeef5d897f7b671123e29991c02b70/packages/blaze/attrs.js#L285 case insensitive?

**Comment by Netherdrake** [comment]
I can confirm that:
```
        autoform: {
            readOnly: true
        }
```
Works fine, but only on String input types.

**Comment by bharathkeshav12** [comment]
@mitar - Safe to upgrade to the latest version without any modifications? (readonly to readOnly) ?

**Comment by mitar** [comment]
I hope so. :-) 2.2.1 should work the same as 2.1.9. But I would love feedback. :-)
