### ISSUE TITLE
Add event scroll 

### ISSUE THREAD

**Issue by NitroBAY** [meteor/blaze#152]
https://github.com/meteor/meteor/issues/3298

**Comment by mitar** [comment]
I am using jQuery inside `onRendered` for this.

**Comment by NitroBAY** [comment]
I also do but shouldn't event of templates should support most events ?

**Comment by mitar** [comment]
Hm, but not for events on `document` and `window`. Blaze does not render there or manage that.

**Comment by NitroBAY** [comment]
Okay

**Comment by abernix** [comment]
@mitar A similar issue just came up and I posted [some comments](https://github.com/meteor/meteor/issues/2024#issuecomment-39882933).  While I agree that it's not really Blaze's department to manage top-level DOM events like `scroll`, `keydown`, etc., it has been discussed in the past that there should be a method for this in Blaze:

Like in this issue about a similar situation with `scroll`: https://github.com/meteor/meteor/issues/2024#issuecomment-39882933:
> Blaze should provide a way to declare events on the body or document.

But I still think you're right.  I think an official note should be about this in the Guide, but maybe something could be added to the Blaze docs to make this clear?  I think even in the React-world developers need to do something along the lines of `document.addEventListener("scroll", ...`) (or use jQuery).

**Comment by mitar** [comment]
So I do things like [this](https://github.com/peer/mind/blob/master/packages/peermind/layout/layout.coffee#L40). Where I generate a random ID and then attach it under that event namespace in `onCreated` of a template which needs it, and then remove it on `onDestroyed`.

**Comment by NitroBAY** [comment]
Great hack,which tends to prove that `'scroll window'` could be implemented on template level

**Comment by mitar** [comment]
I think we should focus our resources to more important things, but if you want to look into a pull request, then maybe.
