### ISSUE TITLE
jQuery returns wrong data-* attributes the second time I click a remove button on a item part of a list.

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#155]
Migrating this issue over from meteor/meteor#4231. I've created an [up to date repro here](https://github.com/hwillson/meteor-issue-4231) (reproduction steps are included in the repro). Although there are several ways to work around this issue (by finding another way to get the id), this exact issue is still happening. Looking at the following ([here](https://github.com/hwillson/meteor-issue-4231/blob/0ab473eea4e8ddeeb37b174bb7562cd963a439c0/client/main.js#L37) in the repro):

```js
var id = $target.data('id');
```

On subsequent calls the `.data` call always returns the previous `id` value, instead of the current elements `id` value. As mentioned in [meteor/meteor#4231 (comment)](https://github.com/meteor/meteor/issues/4231#issuecomment-94947067), it's unknown if this is a jQuery specific issue, or being caused by Blaze reusing DOM nodes somewhere and preventing jQuery from clearing its internal cache.

Originally reported by @brugnara.

----

(Original issue)

**Short story**

Here you can see a demo of the problem (press some times ADD and then the first X many times.. Only the first one will delete the record. Then try with the second button for the very same issue).

**Long story**

I have a template that renders an array of objects stored in `Session`.

You can try by your self. You press the ADD button and you will see a list of items with a red sign that is supposed to remove the current item, and it works the first time you press it. The second time I get an error saying the id doesn't exist. With the inspector, I can see the `data-id=RAND` and it is right. The only wrong thing is the result of the `.data('id')` function the second time I press the button. I really can't understand what is happening. May this be a bug somewhere? (see the ***** signed comment. The value obtained is wrong but anything else is rendered ok, ie the `DEBUG {{id}}` is showing correctly and the inspector shows the data-id setted correctly. In my opinion the `event` routine fails at some point, or simply I'm making some issue with the code :) )

Thank you for the attention.

Manager:

```js
var MESSAGE_QUERIES = 'messages:queries';
var MESSAGE_CURRENT = 'messages:current';

Template.messagesNew.helpers({
  queries: function() {
    return Session.get(MESSAGE_QUERIES);
  }
});

Template.messagesNew.events({
  'keyup #message-new-text': function(e) {
    var $len = $('#message-new-text-length');
    var $text = $(e.target);
    var len = $text.val().length;
    $len.html(len === 0 ? '' : len + (len === 1 ? ' char' : ' chars'));
  },

  'click .query-add': function(e) {
    e.preventDefault();
    var id = chance.word({ length:16 });
    var queries = Session.get(MESSAGE_QUERIES);
    if (!queries) {
      queries = [];
    }
    queries.push({
      id: id
    });
    Session.set(MESSAGE_QUERIES, queries);
  },

  'click .btn-remove': function(e) {
    e.preventDefault();
    e.stopImmediatePropagation();
    var $target = Template.instance().$(e.currentTarget);
    var id = $target.data('id'); // ************* This is wrong any click but first
    TARGET = $target; // for debug only
    var queries = Session.get(MESSAGE_QUERIES);
    var toRemove = -1;
    $target.blur();
    //
    queries.forEach(function(query, index) {
      if (query.id === id) {
        toRemove = index;
      }
    });
    if (toRemove === -1) {
      return console.warn('Nothing found with id:', id);
    }
    console.log('Removing query with id:', id, 'in position:', toRemove);
    queries.splice(toRemove, 1);
    Session.set(MESSAGE_QUERIES, queries);
  }
});
```

Template

```html
<template name="messagesNew">

  <form>

    <div class="form-group">
      <label for="message-new-text">Text message</label>
      <small class="pull-right" id="message-new-text-length"></small>
      <textarea id="message-new-text" class="form-control" placeholder="Lorem ipsum"></textarea>
    </div>

    <div class="form-group">
      <label>Queries</label>
      <button class="btn btn-default query-add">
        <span class="glyphicon glyphicon-plus"></span>
        Add
      </button>
    </div>

    <div class="form-group">
      {{#each queries}}
        DEBUG: {{id}}
        <div class="panel panel-default">
          <div class="panel-title">
            <div>
              <span class="pull-right query-remove">
                <button class="btn btn-danger btn-xs btn-remove" id="query-remove-{{id}}" data-id="{{id}}">
                  <span class="glyphicon glyphicon-remove disabled" style="margin-top: 3px;"></span>
                </button>
              </span>
            </div>
          </div>
          <div class="panel-body">
            {{>query .}}
          </div>
        </div>
      {{/each}}
    </div>

  </form>

</template>
```

Thank you.

**Comment by mitar** [comment]
Hm, it might be that Blaze updates attributes, but jQuery is caching `data-` attributes so it does not detect a change.

I wonder, if you manually (trough DOM inspector) change `data-id` attribute, and then call jQuery `data` on it, does it return the updated value?

**Comment by mitar** [comment]
Maybe that is also a difference between jQuery `prop` and `attr`. Read [discussion here](https://api.jquery.com/prop/).

Read also [this](https://api.jquery.com/data/#data-html5):

> As of jQuery 1.4.3 HTML 5 data- attributes will be automatically pulled in to jQuery's data object. The treatment of attributes with embedded dashes was changed in jQuery 1.6 to conform to the W3C HTML5 specification.

> To retrieve the value's attribute as a string without any attempt to convert it, use the attr() method.

> The data- attributes are pulled in the first time the data property is accessed and then are no longer accessed or mutated (all data values are then stored internally in jQuery).

I think this resolves it. If you want the latest value. You should be using `attr` and not `data`.

**Comment by mitar** [comment]
So I think this is just misunderstanding of jQuery `data`. `data` is not an interface to `data-` attributes, but jQuery specific thing to store data associated with DOM, which is only prepopulated from `data-` attributes. You can see that also from the fact that if you update a value using `data`, an attribute is not updated on DOM element. If you care about attributes, access them using `attr`.

**Comment by mitar** [comment]
@hwillson, thanks for migrating the issue over and the work looking into this!

**Comment by kodamirmo** [comment]
Any update?

**Comment by mitar** [comment]
See [this comment](https://github.com/meteor/blaze/issues/155#issuecomment-260144553).

**Comment by kodamirmo** [comment]
I can't get the correct value, event with attr.

```javascript
let closest = $(e.target).closest('.deleteGalleryItem');
let idToDelete = closest.attr('item');
console.log(closest);
console.log(idToDelete);
```

![screen shot 2017-06-04 at 18 51 36](https://cloud.githubusercontent.com/assets/1815586/26766421/1eb05e44-4957-11e7-8c74-10ea1493f382.png)

**Comment by mitar** [comment]
Maybe use `prop`.

**Comment by kodamirmo** [comment]
Prop is undefined, I'll be looking how to fix  this.

**Comment by adamgins** [comment]
hi did you solve this?

we have an `each` that list a grid of images and a similar loop for list images in a carousel which is 
statement that is then worked on by some carousel js see http://idangero.us/swiper/api/ 

so conceptually

grid
carousel


... when we remove an item from the grid using then try and `mySwiper.removeSlide(slideIndex);` sometimes the clicked item n the grid refers to a different item in the grid... ie item 0 clicked, but meteor thinks it's item 1.

if we use `document.getElementById` it works.. but both `Blaze.getData(e.currentTarget)` refers to the wrong item. ... ie e.currentTarget seems to be for a totally different item. 

Any ideas pls?
