### ISSUE TITLE
Documenting reserved words

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#156]
Creating this issue based on @mitar's [comments](https://github.com/meteor/meteor/issues/3723#issuecomment-260026053) in meteor/meteor#3723:

> I think opening one ticket on Blaze to document reserved words (or mentioning that one should not use same words as existing methods) could be opened. I wonder though if this is will be a problem at all once we move to class-based templates. Because it is probably clear that you should not override other methods with your methods. 

This issue replaces both meteor/meteor#3723 and meteor/meteor#3156.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
