### ISSUE TITLE
Strange behaviour of select element

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#164]
Migrating this over from meteor/meteor#5588 (I've confirmed this is still happening via an [updated repro here](https://github.com/hwillson/meteor-issue-5588)).

----

(originally reported by @npvn)

I have a simple template consisting of a `select` element. When there is no option selected, a placeholder item is shown at the top of the list. If any option is selected, the placeholder will be removed from the DOM.

The implementation for this is very simple and can be found in this repo (see updated repro link above).

There is a strange issue: When the first option is selected, the selection is "shifted" to the second option (see [screencast](http://quick.as/b87wHRQP9)). This only happens for the first selection, and only for the first option.

It looks like Blaze is confused about the placeholder element, and transforms it into the first option element instead of removing it from DOM.

A workaround that seems to fix this is adding a random `id` to each option element, like [this](https://bitbucket.org/npvn/meteor-select-element-issue/commits/a20a0a85c3e16445edd9d52957dc07a82fd769af?at=master).

**Comment by mutdmour** [comment]
I have narrowed down this issue to `ElementAttributesUpdater` in attrs.js. When changing attributes from placeholder to first option, `handler["selected"]` is set to `true`, whereas the `elem["selected"]` is set to  `false`. If I comment out the validation `if (oldValue !== value) {` to allow `handler.update(elem, oldValue, value);` to run, issue is gone. Though this creates conflict with separating handlers. Should this validation be at the level of the updater (calling the update on the handler) or the handler itself?
Cannot yet figure out why the placeholder's `elem["selected"]` is being set to false, if it was set to true before. Any ideas?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
