### ISSUE TITLE
this context of template.autorun should be a template instance

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#166]
Migrating this PR encouraged feature request over from meteor/meteor#5603.

----

(original reported by @mitar)

Currently it is `view`. One could get to the template instance with `view.templateInstance()`, but I think it is really cleaner if it would be a template instance to begin with.

**Comment by deanius** [comment]
If it was changed to `undefined` like most autoruns, would there be no other way to access the `view` variable?

**Comment by mitar** [comment]
You can always use `Blaze.currentView()` to access view. I think we should make `this` be current template instance.

**Comment by mitar** [comment]
So I think we should change it so that `this` is current template instance. Pull requests encouraged.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
