### ISSUE TITLE
HTML files with <head> tags shuld be added to the server side target

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#167]
Migrating this over from meteor/meteor#5913. This issue relates to #16.

----

(originally reported by @mitar)

It is a bit strange. Currently, HTML files with `<head>` tags are added for web target, but then they are rendered by the server and never really send to the client. This makes it tricky to create templates which can work both on the client and server side.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
