### ISSUE TITLE
v1.0.4 regression (sort of): How to get reference to block template from content block?

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#170]
Migrating this over from meteor/meteor#3973. This isn't really an issue but it might be a good idea to document some of the discussed behaviour in the Blaze docs.

----

(originally reported by @aldeed)

The v1.0.4 notes say

> Fix bug where, when a helper or event handler was called from inside a custom block helper, Template.instance() returned the Template.contentBlock template instead of the actual user-defined template, making it difficult to use Template.instance() for local template state. While this may have been a bug, I was actually using it to work back to the block template instance from within a content block. Now I can't figure out how to do that, so it seems like a regression.

For example with

```handlebars
<template name="autoForm">
  <form {{atts}}>
    {{> Template.contentBlock ..}}
  </form>
</template>
```

I have a helper for use within the `{{#autoForm}}{{/autoForm}}` block, which gets the `autoForm`  template instance using code like this:

```js
var instance = Template.instance();
if (!instance) {
  return {};
}

var view = instance.view;
while (view && view.name !== 'Template.autoForm') {
  view = view.originalParentView || view.parentView;
}
```

But since `instance` is now returning the outer instance, we're already past 'Template.autoForm' in the hierarchy. How can I get the template instance I want?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
