### ISSUE TITLE
Un-rendering and re-rendering a large section of DOM can be expensive; add a way to keep the DOM around when it is not visible

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#171]
Migrating this over from meteor/meteor#4351. There has been a lot of recent discussion about Blaze 2.0 (see #131), some of which could greatly impact how Blaze renders content (like [using Vue behind the scenes](https://github.com/Akryum/blaze2)). For that reason I'm not sure if this feature request should be kept open, or just referenced in one of the larger feature discussions ...

----

(originally reported by @ganySA)

Hi

I have posted a similar question on iron-router forums but i would keen to understand if anyone else is suffering from performance issues using meteor on mobile rendering large lists.

Scenario is Master List --> Details Page. When navigating between a master list and the details page and back to the master using a mechanism such as iron router to yield data - blaze is forced to re-render. On a mobile device this is very noticeable (not unusable) but simply starts loosing any sort of native appeal / feel - this is not experienced on a desktop.

The only way to get around this is to manually load the templates into the dom and then manually hide + show templates as needed (not re-render)

Is there a means in Blaze to keep a template as a singleton - that it is never disposed from view? Just hidden and shown as needed and does not have to re-fire "rendered" or other template events.

Or is this simply a issue with how iron-router works?

**Comment by mitar** [comment]
I think it is a good issue to keep open for now. This is one of important performance considerations for legacy apps. I have not seen too much of it in comparison with React on my benchmarking suite: https://github.com/mitar/meteor-blaze-benchmark But it seems it is connected with using jQuery for events. Inline events might improve this.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
