### ISSUE TITLE
Please use Releases

### ISSUE THREAD

**Issue by rwatts3** [meteor/blaze#173]
Please use Releases so that those who are following blaze do not have to hunt through commit logs to have a clear understanding of where blaze is heading.

**Comment by mitar** [comment]
What do you mean? There is history file: https://github.com/meteor/blaze/blob/master/HISTORY.md

**Comment by laosb** [comment]
@mitar I think he's referring to [Release feature of GitHub](https://github.com/meteor/blaze/releases).

**Comment by mitar** [comment]
I know. But I am asking why those over the history file? So what is missing? Tags? Text in releases feature? Descriptions of changes?

**Comment by mitar** [comment]
Closing for now because I think history file servers this purpose. But I think we should use tags to tag releases.
