### ISSUE TITLE
Heterogenous Attributes (Like HTML)

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#174]
Migrating this feature request over from meteor/meteor#4809. This functionality doesn't currently exist, but since there has been very little interest in adding it (and there are numerous ways to work around this), we might want to consider closing this issue.

----

(originally reported by @DerekTBrown)

In passing data to templates, the parser works one of two ways. It either returns a string:

```
{{#foo bar}}
{{/foo}}
RESULT: this.data = "bar"
```

or it returns an object

```
{{#foo bar="baz" bat="bah"}}
{{/foo}}
RESULT: this.data = {bar: "baz", bat: "bah"}
```

However, it cannot parse multiple strings, or a combination of strings and objects. It would be nice to be able to parse both of these elements, to replicate HTML like features. For example:

```
{{#foo snap crackle="pop"}}
{{/foo}}
RESULT: this.data = {snap:"", crackle:"pop"}
```

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
