### ISSUE TITLE
Spacebars compiler should fail when a contenteditable DIV has interpolation tags in it's contents

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#175]
Migrating over from meteor/meteor#3635 (two potential workarounds exist - https://github.com/meteor/meteor/issues/1964#issuecomment-57948734 and https://github.com/meteor/meteor/issues/3635#issuecomment-131991460).

----

(originally reported by @avital)

(See meteor/meteor#1964 -- this use-case doesn't work.)

We should add an error when Spacebars parses a contenteditable DIV with any interpolation inside of it, eg `{{foo}}` or `{{> otherTemplate}}`.

Similar to React's facebook/react#1466, but we can do better by allowing initial contents if they aren't dynamic.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
