### ISSUE TITLE
How to sync template.autorun with DOM update?

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#176]
Migrating this over from meteor/meteor#3372. Using `Tracker.afterFlush` has been the main way to work around this issue, and is quite common. That being said I don't think there is much to do with this issue other than potentially documenting `Tracker.afterFlush` use as a workaround to this issue somewhere? The [`Blaze.TemplateInstance#subscribe`](http://blazejs.org/api/templates.html#Blaze-TemplateInstance-subscribe) section of the Blaze API docs actually shows an example of this workaround in the context of waiting for a subscription to load before using a DOM based plugin. Maybe that's enough (it's kind of hard to find though)? 

----

(originally reported by @artpolikarpov)

If I write this:

```
Template.my.rendered = function () {
    this.autorun(function () {
        var data = Template.currentData();
    });
}
```

...when my autorun callback will be called — before or after DOM update? Or is it just async?

Actually, I’m trying to find the best place to initialize and reinitialize custom-scrolling-module. I need to react on DOM changes. I found that way to depend on data context not the fine one, because it no guarantees the fresh state of the DOM.

It’s even harder when you have child templates...

How do you solve such kind of problems?

P. S. Maybe I’m wrong but I’m still missing **Template.my.updated** callback that will be called when instance of a template is updated (including child instances).

**Comment by mitar** [comment]
I think this really depends on the exact problem to solve. Sometimes it is easy to put the internal DOM into its own subtemplate and then use its `onRendered` to detect changes.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
