### ISSUE TITLE
Strange order of life-cycle callbacks in Blaze

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#177]
Migrating this pull-request encouraged issue over from meteor/meteor#4166 (note: this issue was fixed in [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components)).

----

(originally reported by @mitar)

When a template includes (`outer`) another template (`inner`), then `onDestroyed` callback of the `outer` template is called first before the `inner`. This is really strange for any cleanup one might want to do.

See this example: https://github.com/mitar/meteor-issue4166 Open the web console and type `Session.set('flag', true);`. The order of life-cycle callbacks will be:

```
onCreated outer
onCreated inner
onRendered inner
onRendered outer
onDestroyed outer
onDestroyed inner
```

But probably a more reasonable order would be:

```
onCreated outer
onCreated inner
onRendered inner
onRendered outer
onDestroyed inner
onDestroyed outer
```

I propose this to be switched around.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
