### ISSUE TITLE
Tracker.autorun inside template.autorun should make sure Template.instance() works

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#178]
Migrating this over from meteor/meteor#4494 (also see this important  https://github.com/meteor/meteor/issues/4494#issuecomment-148250571 - everyone help keep 🔥 == 😎).

----

(originally reported by @mitar)

Currently, if you run `Template.autorun` inside of a `template.autorun`, `Template.instance()` is not bound correctly inside that nested computation to the template instance. This makes it really hard to use reactivity as immediately when you have a bit more complicated code and you split it into multiple reactivity paths, things do not work anymore. The issue is even larger because you cannot nest `template.autorun` calls..

I would propose that if `Template.autorun` detects that it is running inside of `template.autorun`, it remembers the template context in which is running and runs its computation in that template context, when the computation is rerun, so that `Template.instance()` keeps working.

[Reproduction](https://github.com/mitar/meteor-issue4494). Just click the button and see the web console.

**Comment by abernix** [comment]
Tagging as related to meteor/meteor#6516.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
