### ISSUE TITLE
TemplateInstance#data is only updated when Template.instance() is called

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#179]
Migrating this over from meteor/meteor#4491 - thanks!

----

(originally reported by @santiagopuentep)

The Template.data doesn't update unless view.templateInstance() is called.

This makes it useless to save a reference to the template and use it's data. Instead of that the user would have to call myTemplate = myTemplate.view.templateInstance() or save a reference to the view instead and call templateInstance from there.

This is very missleading and generates hard to track bugs. To find what was wrong with the update I had to create a special project to track down the issue, since the template.data was updated after a click event was fired in that template (because in the meteor source code when there is a handler attached to it the view.templateInstance() function is called automatically).

**Comment by mitar** [comment]
I think it is explicitly said that `template.data` is not reactive. I would even say that it is a bug if it changes at all ever. It should stay the same as it was initially.

**Comment by mitar** [comment]
(But we should leave it as it is for now and provide a reactive `.data` at some point.)

**Comment by hwillson** [comment]
> I think it is explicitly said that template.data is not reactive.

Yes, adding the doc reference from [Blaze.TemplateInstance#data](http://blazejs.org/api/templates.html#Blaze-TemplateInstance-data):

> This property provides access to the data context at the top level of the template. It is updated each time the template is re-rendered. Access is read-only and non-reactive.

Regarding 

> (But we should leave it as it is for now and provide a reactive .data at some point.)

I believe [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) already does this? I'm starting to notice a re-occuring theme here regarding long standing Blaze issues already being addressed by Blaze Components ...  😄.

**Comment by mitar** [comment]
> I believe [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) already does this? I'm starting to notice a re-occuring theme here regarding long standing Blaze issues already being addressed by Blaze Components ...  😄.

Of course it does. :-)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
