### ISSUE TITLE
Blaze.toHTML not rendering images, missing formats (bootstrap)

### ISSUE THREAD

**Issue by juliomac** [meteor/blaze#18]
I am using the same template for both my website and re-use it to email mu customers.

However they look quote different from each other.

On email it is not aligning with ```class="col-lg-4``` for instance nor the images are shown.

Is this a limitation of Blaze.toHTML or is there a workaround?

**Comment by stubailo** [comment]
I think this is a limitation of email - I bet the HTML code is correct, the email client just doesn't know how to render it. Have you researched the current best practices for HTML email that works across email clients?

**Comment by gabrielhpugliese** [comment]
I suggest using [Foundation for Emails](http://foundation.zurb.com/emails.html)

**Comment by juliomac** [comment]
Thanks for the tip @gabrielhpugliese !

Dear @stubailo, thanks for the comment. I didn't realize email clients had this limitations. This has nothing to do with Blaze.toHTML itself then, but on how limited (and each one is different) are email clients.

As for the image not loading, I found out how to work around it. The problem was in the ```<img> src="/images/image.png" path. While this works perfectly on the browser, ```Blaze.toHTML``` seems not to be able to find it. It only recognizes the full path.

To solve it, I created a helper using ```Meteor.absoluteURL()``` like below:

    Template.mytemplater.helpers({
      ImageFullPath: function(){
         var UrlPath = Meteor.absoluteUrl();
         return UrlPath.slice(0,-1) + this.imageRelativePath;
      },
    });

My imageRelativePath use a "/ " a the beginning so I had to use ```slice Meteor.absoluteUrl()``` to avoid duplicated "/"
