### ISSUE TITLE
Template name collision

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#180]
Migrating this over from meteor/meteor#4189 (sounds like [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components#namespaces) to the rescue again on this one - https://github.com/meteor/meteor/issues/4189#issuecomment-148258163).

----

(originally reported by @dbnoble)

In the case of a template being named "watch", rendering is halted when viewing with Firefox, leaving only a blank page.

The following error is thrown:

Expected template or null, found: undefined

The error is only thrown in Firefox, while in IE and Chrome the application seems to load as expected.

I'm assuming that there are likely other template names which would the same type of collision with native javascript functions.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
