### ISSUE TITLE
IE11 crashes when Blaze updates <table> children while MutationObserver is active

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#181]
Migrating this pull request encouraged issue over from meteor/meteor#6081. There is a known workaround (including a `<tbody>` explicitly in your template - see https://github.com/meteor/meteor/issues/6081#issuecomment-178884241 for more details).

----

(originally reported by @DiegoOlivierFernandezPons)

**Refer to the second comment for more specific information about what triggers the crash/bug.**

We have encountered crashes in IE and have reduced the issue to a Semantic UI dropdown and a table that is reactively updated by Blaze.

https://github.com/DiegoOlivierFernandezPons/IE_crash_semantic_meteor

The code is a 2 x 2 table `[[1, 2][3]]` that is updated into a 1 x 2 table `[5,6]` and an empty dropdown initialized in an `onRendered()` callback. Internet Explorer 11 (11.64.10586) crashes. Chrome, Firefox and Edge are unaffected.

The crash happens on line 366 of `blaze.js`

**(see videos in original issue)**

To reproduce

- Download the code and type 'meteor'
- point the browser to localhost:3000
- type character 'b' or open the console and type 'show_bug()'

You can put a breakpoint on line 366 of blaze.js before triggering the bug.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
