### ISSUE TITLE
Make templates follow JS scoping rules between package and app code

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#182]
Migrating this over from meteor/meteor#5032.

----

(originally reported by @JWo1F)

I'm making a large Meteor app and all my templates are now named "veryLongNameOfMyTemplate". I want to avoid having such long names.
I tried to create my templates in packages but I have a strange issue: while most package variables are file-scoped or package-scoped, templates are not: they are global by default.

How can I create package-scoped templates?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
