### ISSUE TITLE
Template.currentData behaves differently in helpers and event handlers

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#183]
Migrating this over from meteor/meteor#3249. A fix for this issue was created but ultimately not merged, due to it being a breaking API change (see https://github.com/meteor/meteor/issues/3249#issuecomment-77949966).

----

(originally reported by @mitar)

Currently there is a big difference how `Template.currentData()` behaves inside a event handler and template helper. In event handler it returns always the data context at the top level of a template where event handler was defined (and `this` is a data context of where event was triggered).

But for template helper it is always where the template is rendered. So if one is using `Template.currentData()` to access the template-level data context in the event handler, you have to use `Blaze.getData(Template.instance().view)` to access the same template-level data context in the template helper. So reusing the code and learned behavior between event handlers and template helpers is hard and it leads to programming bugs.

See example:

https://github.com/mitar/meteor-issue3249

As example also shows, `Template.parentData` would not be a suitable approach here because the same code is used at various level of data contexts.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
