### ISSUE TITLE
Improve {{#each}} errors logging

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#184]
Migrating over from meteor/meteor#3312. I've created a repro for this here:

https://github.com/hwillson/meteor-issue-3312

----

(originally reported by @MattiSG)

If I pass a currently non-iterable variable to a Spacebars `{{#each}}`, I get the following exception:

> Exception from Tracker recompute function: {{#each}} currently only accepts arrays, cursors or falsey values.
> [very long stack trace]

However, I have no hint as to _which_ iterator failed. Even on a medium-sized app, it is extremely time-consuming to narrow down on the responsible template.

I expect the runtime to tell me the name of the template, and the line and column number of the failing iterator.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
