### ISSUE TITLE
Spacebars : no easy way to handle @first/@last/@index/@odd/@even ?

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#185]
Migrating over from meteor/meteor#2587. [`@index` has been implemented](https://github.com/meteor/meteor/pull/3716) but the others have not.

----

(originally reported by @temsa)

Spacebars is inspired by Handlebars, yet it does not support [@data](http://handlebarsjs.com/reference.html#data) properties as far as I know (at least it is not in the reference).

How should we handle some "{{#each}}" which should not have some element for the last or the first one ?

How should we handle "stripes" as well ?

**Comment by vadimmelnicuk** [comment]
Any updates on this?

**Comment by MrSpark2591** [comment]
Try this one. works for me 💃 
[Link to answer](https://stackoverflow.com/a/31664610/6318875)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
