### ISSUE TITLE
Trouble using jQuery UI sortable with an array within a Mongo document

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#186]
Migrating this over from meteor/meteor#2003. There is a lot of discussion in this issue, so maybe jump straight the to most recent comments, starting at https://github.com/meteor/meteor/issues/2003#issuecomment-263041788.

----

(originally reported by @JackAdams)

I've got a feeling this might be expected behaviour in Blaze, given how things are indexed using the {{#each}} block helper, but this is something that used to work in Spark. Repo showing the problem is here: https://github.com/JackAdams/blaze-issue and the example app is deployed here: http://blaze-issue-example-app.meteor.com/

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
