### ISSUE TITLE
Allow templates to be grouped

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#189]
Migrating this over from meteor/meteor#3449 (viable workarounds are outlined in https://github.com/meteor/meteor/issues/3449#issuecomment-69463052 and https://github.com/meteor/meteor/issues/3449#issuecomment-69866038).

----

(originally opened by @d4nyll)

At the moment, I have several templates which, when rendered, needs to run some Javascript to style it properly.

```handlebars
<template name="abc">
</template>
<template name="def">
</template>
<template name="ghi">
</template>
```

```js
Template.abc.rendered = function() {
  renderSliderScrollbar();
}
Template.def.rendered = function() {
  renderSliderScrollbar();
}
Template.ghi.rendered = function() {
  renderSliderScrollbar();
}
```

It would be nice if we can apply a group to the template so when any member of this group is rendered, it would run the function.

```handlebars
<template name="abc:xyz">
</template>
<template name="def:xyz">
</template>
<template name="ghi:xyz">
</template>
```

```js
Template.:xyz.rendered = function() {
  renderSliderScrollbar();
}
```

**Comment by mitar** [comment]
I will close this in favor of #100.
