### ISSUE TITLE
Fold template-extension package into core packages

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#190]
Migrating over from meteor/meteor#3706.

----

(originally opened by @aldeed)

I'd like to make a case for folding the [template-extension](https://github.com/aldeed/meteor-template-extension) package API into the core API from blaze/templating packages.

- It's messing with private properties.
- Some of the functions could be implemented in a more ideal way if done alongside the core functions
- Most of the functions are extremely useful, to the point of being needed in pretty much every project I do.
- It's really not much code
- We'd like to add support for [template tag attributes](https://github.com/aldeed/meteor-template-extension/issues/2), which we can't currently do.
- We can submit PRs with tests if we know MDG will pull them.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
