### ISSUE TITLE
Feature Request: Allow extra template tag attributes and copy them to the template

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#191]
Migrating over from meteor/meteor#3980.

----

(originally opened by @aldeed)

Template tag parser currently throws errors for any attributes other than `name`. If it allowed extra attributes besides `name` and attached them to the template object for use in code, then packages could support a syntax like:

```
<template name="foo" inherits-helpers-from="bar">
<template name="foo" replaces="bar">
```

That would yield, for example:

```
Template.myTemplate.atts.inheritsHelpersFrom = "bar"
```

Which would be a little nicer in some cases where it makes more sense to define such things in the markup versus javascript.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
