### ISSUE TITLE
Bug in {{else}}.  Does not fully evaluate expressions using helpers.

### ISSUE THREAD

**Issue by MichaelJCole** [meteor/blaze#192]
There is a bug when using {{else}} with a helper.  

Template expressions are not fully evaluated in {{else}}.
 The first call to log evaluates submission(), then prints the id.  
The call to log in the {{else}} evaluates an returns submission(), without evaluating .id

`submission` is a helper on the Meteor user. (See below)

```
                        {{#if submission.completedAt}}
                          {{submission._id}}   <-- prints string id
                        {{else}}
                          {{submission._id}}  <-- prints object
                        {{/if}}
```

submission() looks like:
```
// Helpers
Meteor.users.helpers({
  submission() {
    var s = Submissions.find().fetch()
    if (s && s[0]) return s[0];
  },
});
```
log is a template helper:
```
Template.registerHelper('log', function(thing) {
  if (!thing) thing = this;
  console.log(thing);
});
```

**Comment by mitar** [comment]
First, using template helpers for their side effects is not really supported and might never work as you expect. Blaze tries to optimize things.

I also do not understand this line: `if (!thing) thing = this;` Why is that necessary.

If you remove `log` helper, does it then render to template always `_id` correctly?

**Comment by MichaelJCole** [comment]
Hi Mitar, thanks for looking at this.

The log function is to help debug the templates.  That line may not be necessary, I wrote it once and it worked so I've left it alone.  Log isn't the problem it's what I used to debug it.

If you put {{submission._id}} is both places, it will show the bug.  That's how I first found it.

**Comment by mitar** [comment]
I think you have some other issue. :-) Please make a small reproduction with your bug.

Better for debugging is to use a helper which EJSON.stringify-ies the value. So you can see what is shown out.

So I think what happens is that `submission._id` simply does not exist. So in the second condition your object does not have a `_id`. And then in your logging you use outside data context and print that out.

**Comment by MichaelJCole** [comment]
Yep, you are right, mea culpa.  Thanks for your time :-)
