### ISSUE TITLE
Polymer 1.0 icon rendering issue while using blaze in Chrome

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#194]
Migrating this over from meteor/meteor#4528. This issue ties into the discussion in #71.

----

(originally reported by @mattiLeBlanc)

Hi,

While using Blaze and Polymer I am running in some rendering issues.
Already posted on Polymer's gitpage: [PolymerElements/iron-icon#19 (comment)](https://github.com/PolymerElements/iron-icon/issues/19#issuecomment-110401978)

However,
for me it seems to be related to Blaze.
When I render the following in a template:

```
iron-icon(icon="inbox" item-icon)
                        | Inbox
```

I receive the message in Chrome Console: [iron-icon::_updateIcon]: could not find iconset `icons`, did you import the iconset?

When I make a standalone project without Blaze, the icon renders fine in Blaze.

When in Blaze, I make use of WebComponentsReady event to render the icon, it renders fine.
However, when I wait for Blaze itself to render only when WebCompontentsReady has fired, then my whole scaffold layout is rendered incorrectly:

```
#Jade code
paper-drawer-panel
    paper-header-panel(drawer)
        paper-toolbar
            div Application
        paper-input#searchInput(label="Search")

        div
            paper-menu
                 paper-item
                    iron-icon(icon="inbox" item-icon)
                    | Inbox


    paper-header-panel(main='')
        paper-toolbar
            paper-icon-button(icon='menu', paper-drawer-toggle='')
            div Title
        div
            +Template.dynamic template=main
```

I am not sure where the origin of the issue is, Blaze or Polymer or a combination of both. However, I would like resolve this issue.

I have added a test Repo demonstrating the issue here:

https://github.com/mattiLeBlanc/blaze-polymer1-test

You are required to have Meteor installed to test.

**Comment by emmanuelbuah** [comment]
@hwillson You can close this issue. Blaze isn't supported by Meteor anymore so no need to have a lingering ticket. Thanks.

**Comment by hwillson** [comment]
Thanks @emmanuelbuah - I closed the original issue, but migrated a copy here under the new(_ish_) blaze repo. Blaze is no longer directly supported by Meteor (they still lend a hand where appropriate), but there is a community interested in keeping it alive. Your issue might be of interest to that community, so I'll leave it open here for now. There are a handful of other Polymer related issues open here as well. Thanks for reporting the original issue!

**Comment by mitar** [comment]
Closing this one in favor of #71. Let's have there all discussion about Polymer support and Blaze/Meteor.
