### ISSUE TITLE
Blaze + Polymer

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#195]
Migrating this over from meteor/meteor#3292 (relates to #71). 

----

(originally reported by @leebenson)

Not sure if this is Blaze or Polymer, but see: [ecwyne/meteor-polymer#19](https://github.com/ecwyne/meteor-polymer/issues/19)

in Chrome - click events fire on a web component natively.

in Safari/Firefox - template tags must be wrapped in a divfor any Template.name.events to fire on Polymer objects.

Blaze's event handling is being overridden (overwritten?) somewhere...

**Comment by mitar** [comment]
Closing this one in favor of #71. Let's have there all discussion about Polymer support and Blaze/Meteor.
