### ISSUE TITLE
Blaze.remove on Views rendered based on a data context provided by template helper does not work

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#196]
Migrating over from meteor/meteor#3828.

----

(originally reported by @lucendio)

I am not sure, if I'm holding it wrong or if its really a bug. I just ran into the problem introduced above.

I simply want to remove an list element by clicking on it. The event handler then just perform a Blaze.remove( template.view ). And that works, well, sort of. Only the once disabear which I put into the DOM by Blaze.renderWithData. The elemets rendered based on a data context provided by a template helper, just don't. Eaven if I make data source reative.

I provided an example: https://github.com/lucendio/blaze-remove-bug
The first 3 (client/templates/clog_onsceen.js:21) messages appearing on the top of the window wouldn't disapear by clicking on them, but the last does (client/templates/clog_onsceen.js:46)
disclaimer: I tried to run my example with a late version of devil (27th of Feb.), becasue I saw a potentialy related fix listed in the History.md for the next release. But without any success - I did as described in the readme and sadly run into "error: Symlink cycle detected at meteor/dev_bundle/lib/node_modules".

As I said, I am not sure, if it is really a bug or if I am doing anything wrong. If thats the case, I am sorry for bothering and would like to get an enlightenment from you guys :)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
