### ISSUE TITLE
Support {{foo.0.bar}} in templates

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#197]
Migrating this over from meteor/meteor#2195. PR meteor/meteor#4512 was created to address this, but was not accepted due to time constraints, and was closed during a cleanup round of old PR's.

----

(originally reported by @avital)

Should do the same as `{{foo.[0].bar}}` does now. Used to work in Meteor prior to 0.8.0 (when we used the Spark rendering engine).

We'll take pull requests with good tests. See the spacebars-compiler package.

**Comment by mitar** [comment]
I am not sure about this one. I think it is good that you have to be explicit for now with array access. I would close this for now and if there will be large demand for it in the future, we can revisit it.
