### ISSUE TITLE
UI._parentData() and `..` don't work properly through UI.dynamic

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#198]
Migrating this over from meteor/meteor#2337. 

----

(originally reported by @mizzao)

See the templates in https://github.com/mizzao/ui-dynamic-parent-data for a description of the problem.

In the `foo` template, we'd expect `..` or `UI._parentData(1)` to grab the data context for the `#with` helper. Instead, we have to actually "reach up" 3 times to get it. Here's the output if you run the example:

```
data:  Object {data: "otherData"} 

parent data with .. : 
constr {kind: "Template_foo", render: function, __helperHost: true, guid: "10", debug: function…}

parent data with ../.. : 
Object {template: "foo", data: Object}

parent data with ../../.. : Object {data: "firstData"}

parent data with _parentData(1):  
constr {kind: "Template_foo", render: function, __helperHost: true, guid: "10", debug: function…}

parent data with _parentData(2):  
Object {template: "foo", data: Object}

parent data with _parentData(3):  Object {data: "firstData"} 
```

Clearly this has to do with how `UI.dynamic` is implemented. However, running this example on 0.8.2 and 0.8.3-rc gives the same result, so I don't think it has anything to do with blaze-refactor.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
