### ISSUE TITLE
Blaze._javascriptUrlsAllowed make the same feature to be enabled per helper

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#199]
Migrating this over from meteor/meteor#3103. See https://github.com/meteor/meteor/issues/3103#issuecomment-73814768 for a recommendation to make this part of the Template API instead.

----

(originally reported by @adaptabi)

Make it per handler e.g. a simple example, where only this helper is allowed:

```
Template.registerHelper('pathForBack', function(view, opts){
  opts.javascriptUrlsAllowed = true;
  return "javascript:history.back()";
});
```

**Comment by mitar** [comment]
Not making any judgements about this proposal, but just adding that probably `Template.registerHelper(name, function, options)` would be a much better API, and also backwards compatible.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
