### ISSUE TITLE
Needs a README

### ISSUE THREAD

**Issue by stubailo** [meteor/blaze#2]
:fire: :fire:

Just so the repo doesn't look so bare.

**Comment by tinhphaius** [comment]
fix

**Comment by Kamin12** [comment]
Yeah...the docs...where they at?

**Comment by stubailo** [comment]
http://docs.meteor.com/#/full/blaze_render

**Comment by Kamin12** [comment]
The standalone Blaze docs?

**Comment by Kamin12** [comment]
I may be mistaken but didn't it use to exist here: https://meteor.github.io/blaze/docs.html 

Formatted in with a blue layout?

**Comment by stubailo** [comment]
Yes but that is not a thing anymore, plus it was outdated.

**Comment by Kamin12** [comment]
Word. Hope ya'll create a new one...

These other frameworks increase start-up costs, reduce DIY-ness. 

Blaze is at the core of Meteor's value offering. IMO, the great innovations will come from outside of the hardcore dev circles. Those who have been in other industries and see opportunities to disrupt. Those with experience in other industries are less likely to have access to access to funding or years of dev experience to wrestle with React or Angular. 

Blaze is perfect for disruption.  Disruption is where the big $$$ + impact is. 

Glad to see it continuing. Hope to see some new standalone documentation soon.

**Comment by mitar** [comment]
We have initial version of it. Let's close this and make more concrete proposals/pull requests what to add.
