### ISSUE TITLE
Get Meteor to use code from this repository for Blaze distributed with Meteor releases

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#20]

**Comment by laosb** [comment]
For now, Blaze doesn't really have a separated versioning. Should we have an independent versioning system?

**Comment by mitar** [comment]
I think it [does](https://github.com/meteor/blaze/blob/master/packages/blaze/package.js#L3) and I also think this was one of the core goals with splitting some (all) packages from Meteor.

**Comment by laosb** [comment]
Every Meteor release gets a bump. That wouldn't be ideal for a **separated** package.

**Comment by mitar** [comment]
I think that would not be needed anymore, this is one of those changes they are working on.

**Comment by MiroHibler** [comment]
I don't think MDG should ship Blaze (or any view layer for that matter) with Meteor in the first place. I'd rather make it all optional as they do now with React since v1.3 for example.

**Comment by mitar** [comment]
I think they will have to do so for foreseeable future (at least they go to Meteor 2.0). And also we will have to keep backwards compatibility for that purpose. We can (as a community) go and do Blaze 2. But we and MDG also have responsibility for current users using Blaze 1.

**Comment by MiroHibler** [comment]
I'm just pessimistic by nature and MDG has been known for abruptly changing their mind ;)

**Comment by mitar** [comment]
OK, let's be more optimistic in the future.

So, let's get community to go through tickets and see which are still relevant. This is only on us. If you are more optimistic about community, then feel free to organize this part.

**Comment by MiroHibler** [comment]
I was (trying to be) sarcastic ;) I wouldn't be here if it wasn't for my optimism! ;)

Lets hear what community has to say.

**Comment by mitar** [comment]
Sorry, a bit long day. Didn't catch that.

**Comment by brown2rl** [comment]
@mitar is there anyone from MDG watching this repo?  I think Blaze 1 has some serious potential.  It would be nice if we could add an option like 

$ meteor upgrade blaze

Essentially the proposed script combines both requirements above, and would pull from the official repo to replace Blaze 1

**Comment by tcastelli** [comment]
+1 Blaze has some good potential inside and I think a symlink to this repo in their own repo would be quite useful to forget shared versioning and dependencies.

**Comment by mitar** [comment]
They are, you can [see them here](https://github.com/meteor/blaze/watchers). :-)

**Comment by brown2rl** [comment]
@mitar ok, cool. let me know what i can do

**Comment by zol** [comment]
A loose plan for 1.4 is to depend on Blaze via the app's `package.json`. This will be the point at which we're naturally able to use this repo completely independently.

**Comment by mitar** [comment]
@zol, @benjamn: What does [this comment](https://github.com/meteor/meteor/pull/7072#issuecomment-232814912) mean for the future of this repository? It seems that community involvement in Blaze will again suffer and not move anywhere. I see that there are some potential changes to Blaze repository going in as fixes in Meteor repository, not here. I really worry that this delays of switching Meteor to use this repository will make put all this into a limbo and Blaze will not be able to move anywhere, which will effectively kill it. Not just that MDG is not investing time into Blaze anymore, but now even community seems to not be able to do so.

Can I propose a intermediate solution? Make meteor repository use git submodules to pull these packages here into the main repository and let's start working here on Blaze as a community. Later on, when you finish with NPM integration, we can improve things.

But waiting for NPM integration and everything else seems like putting all those plans we had for Blaze and community stewardship of Blaze in jeopardy.

**Comment by ramezrafla** [comment]
Agreed, many of us depend on Blaze and are not switching any time soon. There has to be an alternative when MDG changes its mind (again!)

**Comment by zol** [comment]
@mitar Meteor 1.4's package unpinning feature will allow us to completely move blaze development over to the community repo without waiting for npm integration.

**Comment by aadamsx** [comment]
> Meteor 1.4's package unpinning feature will allow us to completely move blaze development over to the community repo without waiting for npm integration.

Ok, my question now is, why wasn't @mitar aware of this before so we could have moved forward on this project?  Was/is this the only roadblock to moving forward?

**Comment by mitar** [comment]
@zol: Great to hear that. So, could we make this transition happen with 1.4 release? Can you then remove the code which is in this repository from Meteor repository? I think this would be a great signal that everything is ready to start in this repository.

So for now then we would keep Blaze pure-Meteor packages and continue with this until Meteor has better NPM integration.

So my proposal for steps is:
* code is removed from Meteor repository
* a Meteor 1.4 release comes with community (this repository) packages for Blaze
* community in meantime transfer all Blaze related packages to this repository
* we establish a stand-alone site
* and stand-alone documentation

How does this sound?

**Comment by aadamsx** [comment]
* code is removed from Meteor repository
* a Meteor 1.4 release comes with community (this repository) packages for Blaze
 Who will make the final decision here?  Who would carry out the tasks?  How can we get the decision makers to actually make a decision before 1.4 is released?

* community in meantime transfer all Blaze related packages to this repository
What are the tasks involved and can this be broken down and assigned or is this something that must be done by someone with deep knowledge of Blaze and related packages?

* we establish a stand-alone site
* and stand-alone documentation
These can be started by anyone.  But the documentation should be pulled from somewhere or should original documentation be built?

**Comment by mitar** [comment]
@aadamsx: Most of this things have already been discussed in other issues. I would invite you to check about site and documentation in those issues. Also process on transferring Blaze issues (not packages, that was a typo) have already been started.

About the governance. I think for now I would first like to see who is at all interested in contributing. And if can operate with rough consensus. If it becomes complicated, we can have a longer discussion. For now I would simply publish packages from this repository and I would like that this is possible - make one release where there are not really much changes (maybe just what is already there + fix for Chrome, https://github.com/meteor/meteor/issues/6793).

**Comment by laosb** [comment]
Is the code in this repo up-to-date?

**Comment by mitar** [comment]
It should be. We should of course check that. But when I was last checking it was.

**Comment by aadamsx** [comment]
[Meteor 1.4](https://forums.meteor.com/t/coming-soon-meteor-1-4/23260/111?u=aadams) is has been released.  

@mitar is there any prep that needs to take place in order to get started using this repo for Blaze?

Do you have guidance on using the new unpinning feature will allow us to completely move blaze development over to the community repo without waiting for npm integration?  ... Using Meteor 1.1 or another target release of Meteor?

**Comment by mitar** [comment]
We would just release Blaze as a Meteor package. But we first have to get permissions to do so. So, @zol, what's the plan here?

**Comment by zol** [comment]
@tmeasday was looking into whether there would be any technical ramifications of removing the package sources from `meteor/meteor` and just giving you publish permissions on the `blaze` package.  @tmeasday - can we just go ahead with this now?

**Comment by tmeasday** [comment]
Yeah, we talked about this a little bit. There are a couple of implications of removing these packages from `meteor/meteor`, assuming that means that we *no longer publish as part of the release*[1].

1. The boilerplate includes a dependency on Blaze. This is easily fixed by just putting an `@version` [here](https://github.com/meteor/meteor/blob/release-1.4/tools/static-assets/skel/.meteor/packages#L10) and (ideally) keeping it up to date with Blaze releases.

2. A bunch of internal packages depend on `templating` (mostly accounts related things). I *think* we can just switch them to again `@version` depending on it though. As long as Blaze follows semver, I think we should be OK to set this to something that makes sense now and not really touching it unless changes happen w/ Blaze.

3. Third party packages that use `api.versionsFrom(RELEASE)` and depend on `blaze` or `templating` without using a version constraint. This is probably the biggest issue. If Blaze is no longer in the release, then the semantics of that changes (from "blaze >= version specified in `RELEASE`" to "any blaze version"). But that would only bite people if they update `RELEASE` to be >= the release we remove blaze (let's say 1.4.1, for argument's sake).

  We would have to make it clear to package authors that they should specify blaze versions.

[1] A simpler option is to just use a submodule and keep including the latest version of Blaze in every Meteor release, but this seems like a half-way house. Perhaps we can keep it as a back up plan in case any of the above are deal breakers.

What do you think @mitar / et al?

**Comment by tmeasday** [comment]
There's also a minor philosophical problem that this list of packages includes `static-html`, which feels like it should remain in mainline meteor. But I'm not sure how to disentangle it from these blaze/spacebars packages.

**Comment by mitar** [comment]
I think the full change to `@version` seems OK.

Could we maybe change `api.versionsFrom` to have a more reasonable behavior? Like latest Blaze version? Or maybe we could even hard-code some exception for Blaze?

**Comment by tmeasday** [comment]
I think if we were going to do that we should probably just go the whole hog: if you depend on a non-core package from another package (where the list of core packages is shrinking and will continue to shrink over time), you have to specify some kind of version constraint, or there's an error.

**Comment by aadamsx** [comment]
Any progress on this front?

**Comment by tmeasday** [comment]
https://github.com/meteor/meteor/pull/7633

**Comment by tmeasday** [comment]
Hi! These packages are now gone from the mainline meteor repo! https://github.com/meteor/meteor/pull/7633 🎉

**Comment by tmeasday** [comment]
(See also https://github.com/meteor/blaze/pull/56)

**Comment by mitar** [comment]
Yea!!!

OK, we should then probably create now a Blaze Meteor development team, and get it access to publishing packages from this repo to Atmosphere.

**Comment by mitar** [comment]
And how we should go about updating changelog in meteor about Blaze related things? Or should we just maintain it here?

**Comment by tmeasday** [comment]
1. Yeah, create a MD organization and I'll give it publication rights.

2. Well `meteor update` will no longer treat Blaze any differently to any other non-core dependency[1], so people won't necessarily get Blaze updates w/ Meteor releases. OTOH people might not thing to check a different changelog if they do take a Blaze update. I'm not sure the best way to get this message across, but I think a separate changelog is still best.

[1] Not 100% true because some core packages depend on these packages but you can safely ignore that.

**Comment by mitar** [comment]
I created `blazecommunity`.

OK, then we will handle one changelog in this repository. Yea!

**Comment by tmeasday** [comment]
Maintainer added!

**Comment by tmeasday** [comment]
Let me know if you have thoughts on how best to tell people to look at the Blaze changelog.

**Comment by mitar** [comment]
Yea!

I think we should just make an entry in Meteor's changelog to point them here and this is it?

One more question: how will documentation (http://docs.meteor.com/) be done now? Is it pulled from here? Or should we setup something independent?

**Comment by tmeasday** [comment]
> I think we should just make an entry in Meteor's changelog to point them here and this is it?

I mean, definitely this, but I'm wondering if there's more we can do. Something prominent here: https://atmospherejs.com/meteor/blaze would be good too I think.

> One more question: how will documentation (http://docs.meteor.com/) be done now? Is it pulled from here? Or should we setup something independent?

For now, yes, it will pull from here (as I bump a submodule). If you set up something independent, we should point people there though, given the decoupling of the releases.

**Comment by mitar** [comment]
I opened #57.
