### ISSUE TITLE
Make UI._escape part of the public API.

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#200]
Migrating this over from meteor/meteor#3267. Note the `_escape` function is currently available (but still pseudo-private) as `Blaze._escape`. Last time I checked though (10 seconds ago 🙂), underscore is still a hard dependency of Blaze, and underscore already has an equivalent [escape](http://underscorejs.org/#escape) function (managing duplicate functionality under the Blaze umbrella might not be worth the extra overhead ...).

----

(originally requested by @cscott)

If you are dealing with `Spacebars.SafeStrings`, it is handy to have a reliable html-escaping method handy.

The `Handlebars._escape` method, which does basic HTML-safety escaping, isn't public, although it's now available at `UI._escape` as well. Any chance this could be made public, perhaps as `Spacebars.SafeString.escape`?

**Comment by mitar** [comment]
The `_.escape` sadly in underscore 1.5.2 sadly do not escape backticks. So current version of `Blaze_.escape` is better.

I think for now one can use `Blaze._escape` and later on `_.escape`.
