### ISSUE TITLE
Blaze Problem: Incorrect Parent Document With DOMBackend

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#201]
Migrating this over from meteor/meteor#3891. PR meteor/meteor#4168 was created for this but not merged (due to lack of time / old PR cleanup process).

----

(originally reported by @jchristman)

When creating a new window with `window.open`, IE11 conforms to the standard and does not allow insertion of nodes created by the current document into the new window's document. It only allows nodes created by that new window's document. For example:

```js
var newWindow = window.open('', '_blank', 'width=400,height=4000'); // Creates a new window

newWindow.appendChild(document.createElement('div')); // Fails, raising Hierarchy Request Error
newWindow.appendChild(newWindow.document.createElement('div')); // Succeeds 
```

This is relevant when attempting to use Blaze.render to create a second window with reactivity. For example, the following code, while working on Chrome and Firefox, fails on IE.

```js
var newWindow = window.open('', '_blank', 'width=400,height=4000'); // Creates a new window
Blaze.renderWithData(Template[template], context, self.newWindow.document.body);
```

After much javascript debugging, I have determined that the code breaks on [line 94](https://github.com/meteor/meteor/blob/13e98f5a4ad85b6caf5dc3778f3e29aa3c500f30/packages/blaze/domrange.js#L94) of domrange.js, throwing an "Invalid Argument" exception in Internet Explorer. I believe this is an expression of the fact that the nodes being inserted have a document parent of the current view, rather than of the new window.

I believe this can be fixed by adding an argument to Blaze.render that would allow specifying a "document context" to pass to [jQuery.parseHTML](http://api.jquery.com/jquery.parsehtml/) (optional second argument). This "document context" would need to be passed all the way to [line 18](https://github.com/meteor/meteor/blob/a81fbf483efa4f40ea2d382f0c7275d408536e96/packages/blaze/dombackend.js#L18) of dombackend.js where the html nodes are created so that they are created with the correct document hierarchy. Another way of fixing the problem would be to look at the parent document of the [parentElement](https://github.com/meteor/meteor/blob/13e98f5a4ad85b6caf5dc3778f3e29aa3c500f30/packages/blaze/view.js#L551) and automatically passing that "document context" to the jquery.parseHTML.

To reproduce this, clone into the below repository.

```
git clone https://github.com/jchristman/meteor-popout.git
cd meteor-popout/example
meteor
```

Next, perform the following steps:

1. Open the running site in Internet Explorer
2. Open the javascript console
3. Click on any of the buttons that say "Popout State: false" to create a window and get the error

If you have any questions or need further details, please let me know.

**Comment by jchristman** [comment]
I don't really know if this is still a problem - I haven't used blaze in quite some time. My guess though, is that this would still fail since my PR was never merged.

**Comment by hwillson** [comment]
Thanks @jchristman - I believe this is still an issue as well; I read over your PR and the source to confirm. Great PR by the way - thanks for putting that effort in! Hopefully someone here can review all of this and get that ball rolling again!

**Comment by mitar** [comment]
I think this is a valid bug report. I would love to have this in Blaze at some point.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
