### ISSUE TITLE
Template.instance() does not work in data context functions and accross Spacebars.dot

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#202]
Migrating over from meteor/meteor#4386.

----

(originally reported by @mitar)

`Template.instance()` does not work in functions defined in the data context. Moreover, it does not work when accessing a field using a dot operator, so in `{{something.foobar}}`, `something` has access to `Template.instance()`, but `foobar` does not.

This makes any more complicated functions and libraries of functions not be able to access current template instance.

See the reproduction here: https://github.com/mitar/meteor-issue4386

The output is:

```
Found template instance: false.
Found template instance: false.
Found template instance: true.
Found template instance: false.
Found template instance: false.
```

But expected output is:

```
Found template instance: true.
Found template instance: true.
Found template instance: true.
Found template instance: true.
Found template instance: true.
```

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
