### ISSUE TITLE
Possible error when printing an array with undefined values

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#203]
Migrating over from meteor/meteor#5374. Sounds like upgrading underscore would fix this.

----

(originally reported by @jagi)

Hi, I don't know if it's expected behavior. Let's say we have a following array that we want to pass to the template.

```js
Template.body.helpers({
  values: function() {
    var array = [];
    array[9] = 9;
    return array;
  }
});
```

and the template:

```handlebars
<body>
  {{#each values}}
    <div>{{@index}}: {{this}}</div>
  {{/each}}
</body>
```

As a result I will get the following HTML code:

```html
<body>
  <div>0: 9</div>
</body>
```

I would expect to print 10 indexes from 0 to 9 and the 9 value under the index 9 not 0 like it's now.
Here is a reproduction repository: https://github.com/jagi/meteor-array-error

EDIT:
I've noticed that it may probably be caused by `underscore` being in version 1.5.2 instead of the newest 1.8.3. They differ in how the `_.each` method works. The newest one iterates over an array in the correct way, however 1.5.2 omits undefined values. And I assume that you are using the `_.each`  method to iterate arrays.

**Comment by daltonrenaldo** [comment]
why move this here? I understand it's a blaze issue, but blaze doesn't have "underscore" itself... underscore would need to be updated from meteor. It's still using 1.5.2

**Comment by hwillson** [comment]
Hi @daltonrenaldo - I'm moving it here because it's a Blaze issue and all Blaze issues are being moved here for further review. The ultimate solution (be it upgrading underscore or something else) will need to be decided by the team here (as Blaze issues are no longer being reviewed on the main Meteor repo). If any changes need to be made to [meteor/meteor](https://github.com/meteor/meteor), then a new issue will need to opened back on the Meteor repo. Thanks!

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
