### ISSUE TITLE
Why script tags are removed after triple brackets rendering?

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#205]
Migrating over from meteor/meteor#2778.

----

(originally reported by @LeCoupa)

Hello, I have a simple document like the one below that contains some text and a script tag.

```
{
  "content" : "The following script tag is removed after the triple brackets rendering\n\n<script>console.log(\"hello\");</script>",
}
```

When I render it with the triple brackets `{{{content}}}`, the text is displayed but the script tag doesn't even appear in the DOM (it is also not evaluated).

What's the good way to proceed? I thought that the triple brackets rendered html tags but it doesn't seem to work with script tags on my side.

**Comment by nabilfreeman** [comment]
Hi everybody, is there an update on this? I am getting around it by doing:

```
Template.rendered = function(){
	Tracker.autorun(c => {
		//raw embed content...
		this.$('#raw-content').html('<script>window.alert("hello");</script>');
	});
};
```

which is not the cleanest of solutions.

As for my use case, I have a blog embedded into our web app which the marketing team edits on Wordpress (using REST API). They wanted to embed widgets in their posts and Blaze was silently stripping out all the scripts.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
