### ISSUE TITLE
Improve Blaze performance in comparison to React.js

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#207]
Migrating this over from meteor/meteor#3732 (we might just want to reference this in #111 then close it).

----

(originally opened by @mitar)

At the [Hype! React Conf talk from 2015](https://www.youtube.com/watch?v=z5e7kWSHWTg) interesting demos were presented. One of them was also a performance test and comparison with other reactive rendering engines. Blaze was not among them. But I [implemented it](https://github.com/mitar/reactconf-2015-HYPE) and discovered that it sadly performs much slower than React.js. Could this be improved?

- You can see Meteor demo here: http://dbmon.meteor.com/
- Original source code: https://github.com/ryanflorence/reactconf-2015-HYPE
- My code: https://github.com/mitar/reactconf-2015-HYPE

See the video linked above to see how React.js performs, or just run it.

**Comment by mitar** [comment]
Closing this in favor of #111.
