### ISSUE TITLE
Accessing lexical scope variable from event handler

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#212]
Migrating this over from meteor/meteor#5280.

----

(originally reported by @wh0)

Can we have a way to access a lexical scope variable from an event handler?

```handlebars
<template name="btns">
  {{#each a in b}}
    <button>{{a}}</button>
  {{/each}}
</template>
```

```js
Template.btns.events({
  'click button': function (event, template) {
    alert(/* a */);
  },
});
```

edit: `Blaze._lexicalBindingLookup(Blaze.getView(event.currentTarget), 'a')()`. But should there be a non-underscore-prefixed way?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
