### ISSUE TITLE
Template.body.events({'keyup': ... }) doesn't work

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#214]
Migrating over from meteor/meteor#2024.

----

(originally reported by @awatson1978)

Hi hi,
None of the keybinding events seem to be working on the UI.body template in Blaze.

```js
UI.body.events({
  'keydown': function(){
    alert('keypress!');
  }
});
```

Medium-low priority, but would be nice to have all the events supported on the UI.body template. Page-wide keybindings are a very useful thing! :)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
