### ISSUE TITLE
Sub templates starting with HTML comments that contain opening HTML tag trigger render bug

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#215]
Migrating over from meteor/meteor#5673.

----

(originally reported by @Anima-t3d)

# Only happening in template inclusion

A HTML comment containing an opening tag of a HTML element that is not allowed in the HTML structure will trigger sanitizing.

## Expected

HTML code to be rendered as intended, not taking into account comments.

## Result

HTML code is stripped of invalid characters based on HTML code in HTML comments.
Only happens when HTML comment precedes wanted HTML content AND it contains an opening HTML tag which would break HTML validation when rendered.

## Conclusion

HTML comments containing opening elements will be attempted to be rendered. After rendering it will trigger sanitizing filters after which certain elements get removed.

Repro here: https://github.com/Anima-t3d/meteor-comment-bug

```handlebars
<table>
    <caption>Bugged</caption>
    <thead>
        <tr>
            <th>col 1</th>
        </tr>
    </thead>
    <tbody>
        {{#each array}}
            {{> ReproRow}}
        {{/each}}
    </tbody>
</table>

<table>
    <caption>Bugged2</caption>
    <thead>
        <tr>
            <th>col 1</th>
        </tr>
    </thead>
    <tbody>
        {{#each array}}
            {{> ReproRow2}}
        {{/each}}
    </tbody>
</table>
```

```handlebars
<template name="ReproRow">
<!--Will not render tr and td due to comment before code-->
    <!-- <p> -->
    <tr>
        <td><strong>Does not render tr and td</strong></td>
    </tr>
</template>

<template name="ReproRow2">
    <!--Will render tr and td BUT ALSO tbody due to comment before code containing <tbody> -->
    <!-- <tbody> -->
    <tr>
        <td><strong>Also renders tbody</strong></td>
    </tr>
</template>
```

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
