### ISSUE TITLE
Unable to pass arguments to data context method

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#218]
Migrated over from meteor/meteor#3913.

----

(originally reported by @mitar)

If I have a method on data context:

```
DataContext.prototype.foo = function (var1, var2) {
  return Template.fooTemplate;
}
```

It seems I cannot do `{{> foo 'foo' 'bar'}}` or `{{> foo a='foo' b='bar'}}`. This does not look like there is any reason why it would not work, except that it is not implemented?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
