### ISSUE TITLE
Comments inside a head tag are not removed

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#220]
Migrated over from meteor/meteor#3677.

----

(originally reported by @mitar)

```
<head>
  {{! This should be removed }}
</head>
```

In the output static HTML file from Meteor, this tag is still present. But it should be removed.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
