### ISSUE TITLE
observe_sequence package should be moved to Blaze?

### ISSUE THREAD

**Issue by brucejo75** [meteor/blaze#221]
I found an [issue ](https://github.com/meteor/meteor/issues/8160)in the Meteor observe_sequence package.  I did a search for `ObserveSequence` and could not find it in Meteor, but it is in the Blaze repo.

Should this be in Blaze?

**Comment by mitar** [comment]
It is this package: https://github.com/meteor/meteor/tree/devel/packages/observe-sequence

Maybe you are right that it should be moved to Blaze. It is not used anywhere else?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
