### ISSUE TITLE
Compiling templates on server-side

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#223]
[Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) support it and it is more or less easy to get templates to be compiled on the server-side.

Some things to change:
* [web-only architecture should be removed](https://github.com/meteor/blaze/blob/master/packages/templating-compiler/compile-templates.js#L3)
* [Template.body.renderToDocument noop on the server](https://github.com/peerlibrary/meteor-blaze-components/blob/master/server.coffee)
* [head tag should not be processed on the server](https://github.com/peerlibrary/meteor-blaze-components/blob/master/patch-compiling.js#L84), see #167

We are introducing `.blaze` extension (#97). So we should decide if we want only that one on the server-side, or both `.html` and `.blaze`.

The downside is that it seems this will slow-down compilation as it prevents client-only compilation and push, but it then restarts the server-side, even if file is added to client-side only in packages (not sure about `client` directory). At least this happened with Blaze Components when server-side rendered was added.

**Comment by marcoschwartz** [comment]
Great to hear about server side rendering :) How would that compare to https://github.com/meteorhacks/meteor-ssr for example ?

**Comment by mitar** [comment]
We will see. But hopefully it will be compatible.

**Comment by j-jackson** [comment]
This is excellent news! 

I was about to start rewriting my application with react for SSR, but if this is isn't too far off I can stick with blaze. 

Do you have a rough idea on when this might be ready?

**Comment by mitar** [comment]
I do not think anyone is working on this at the moment. But pieces are mostly around ready.

**Comment by j-jackson** [comment]
Thanks Mitar!

**Comment by mave99a** [comment]
Thanks! We are about to work on this SSR part. Thanks for the good work! 

@mitar do you work for Meteor?  Is this SSR official feature ?

**Comment by mitar** [comment]
No, I do not work for Meteor. I just help keep Blaze around. Blaze is now maintained by the community.

There is no concept of "official feature". If community will make it, it will be there.

And again, "compiling templates on server" is not the same as SSR. SSR also requires management of how you pass correct data to templates to be compiled, and probably also management of life-cycle of templates on server, and then how you merge client side template with what server side rendered.

Also #26 is needed.

**Comment by mave99a** [comment]
Thanks @mitar for the clarification!

**Comment by janat08** [comment]
With the new package https://github.com/meteor/meteor/blob/master/packages/server-render/README.md that has a bunch of blaze people move to and complain in forums:
https://forums.meteor.com/t/how-to-use-server-render-with-blaze-html-templates/37963/6

**Comment by janat08** [comment]
Comment belongs in SSR given package description, so duplicating it there.

**Comment by marcoschwartz** [comment]
I was one of the people complaining on the Meteor forum actually :) For now I still don't see how to use server-render with Blaze & iron-router

**Comment by juho** [comment]
Hey, I'd like to start checking this out as we'll need SSR and are on Blaze for the foreseeable future. @mitar, could you help out with finding the right places to look at? What would be a good place to start and are some of these completed? 

```
Some things to change:

- web-only architecture should be removed
- Template.body.renderToDocument noop on the server
- head tag should not be processed on the server, see #167
```

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Comment by StorytellerCZ** [comment]
@juho did you manage to do it?
