### ISSUE TITLE
Additions to Blazejs.org

### ISSUE THREAD

**Issue by arggh** [meteor/blaze#225]
I think it would be good to have a link to the Github repo, as well as list of releases together with a changelog in the blazejs.org website.

**Comment by mitar** [comment]
I agree with GitHub repo, and for changelog, it would be great maybe to link to the one in [git](https://github.com/meteor/blaze/blob/master/HISTORY.md), or find a way to integrate it and nicely render it automatically in some way.

**Comment by arggh** [comment]
Sure, a link to the change log would be sufficient. Just to have them "within arms reach" would be nice.

For example, creating a link with the latest version as the title, pointing to the changelog (or HISTORY.md in Blaze's case) would be good, like Semantic UI does on their frontpage.

**Comment by abernix** [comment]
You may be interested in getting the same treatment as https://github.com/meteor/docs/commit/7e920ee88444a770c222198f6b74340d7cb8d36c provided for Meteor Docs! :smile:

**Comment by mitar** [comment]
Really cool. A great candidate for PR.

**Comment by alexandesigner** [comment]
I've seen some issues and decided to start with this because it's so simple.

**Comment by mitar** [comment]
Thanks!

**Comment by mitar** [comment]
Done with #237.
