### ISSUE TITLE
Packages["html-tools"] is undefined. Problem in html-tools.js

### ISSUE THREAD

**Issue by s7dhansh** [meteor/blaze#226]
This problem arose after adding the `spacebars-compiler` package. Without it, everything's perfect.

I am getting the following error in production.
```
Uncaught SyntaxError: Unexpected token ;
spacebars-compiler.js: Uncaught TypeError: Cannot read property 'HTMLTools' of undefined
global-imports.js: Uncaught TypeError: Cannot read property 'SpacebarsCompiler' of undefined
```
It halts the app execution and nothing loads.

On checking the error (first line), it show,
```
// Try to parse `>` or `/>`, mutating `tag` to be self-closing in the latter                                   // 287
// case (and failing fatally if `/` isn't followed by`>`).var handleEndOfTag=function(scanner,tag){if(getClangle(scanner))
return tag;if(getSlash(scanner)){if(!getClangle(scanner))
scanner.fatal("Expected `>` after `/`");tag.isSelfClosing=true;return tag;}
```
Clearly, during minification, the code `var handleEndOfTag=function(scanner,tag)` is also commented out, and is causing the trouble. Everywhere else (local, local with --production, testing), the code is non-minified  and works properly.
The production is deployed via older mup (due to certain reason), and somehow the file is minified, causing this error.
I am not using `standard-minifier-js`. I do have a `minifier-js` package, which I believe is minifying this file. It is an indirect dependecy of some pakcage, but I am not sure which one.

Can someone help me to figure out the exact issue?

**Comment by mitar** [comment]
I must say that I do not understand what you are reporting here. It seems this is a bug in your app. Can you create a small reproduction?

**Comment by s7dhansh** [comment]
Sorry, for the confusion. Most of it was written after a night out. I have updated the OP to clarify things.

Yes, it is definitely a bug in my app, but I am unable to debug it. Since everything works on local (even with production flag) and on staging, it is extremely hard to reproduce. If you have any pointers to help me on how to debug it, it would be great.

Now that I know it's a minifier issue, I am thinking of:
1. Trying to remove the minification and then test. I have no idea how is it being minified on production. If you know anything, do tell.
2. Making it work with standard-minifier-js.

I am currently following the latter step, so as to improve performance as well. If it doesn't help, I will spawn a machine and create a reprod.

**Comment by s7dhansh** [comment]
The approach worked. I had to fix one of the npm modules to get standard-minifier-js working, post which everything is proper.
