### ISSUE TITLE
Provide template helpers bound to template instance

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#232]
Moving over from meteor/meteor#5576. 

----

(originally reported by @mitar)

As [discussed here](https://github.com/meteor/guide/pull/75/files#r43528778), it would be really helpful to start offering template helpers bound to the template instance instead of data context. This would allow template helpers which use template instances for state, and also minimize unnecessary reactive reruns just because data context changed, but template helper might not even really use it.

API could be something like:

```js
template.helpers({
   ...
}, {bindInstance: true});
```

Or:

```js
template.boundHelpers({
  ...
});
```

The important thing is that helper should be bound to the instance of the template where it was defined, and not where it was invoked. `Template.instance()` can be used to retrieve the latter.

Should those bound template helpers be exposed also on the template instance as well? So that `template.boundHelpers({foo: function () {}})` means that there is also `instance.foo()` method available? This then allows good code reuse because a template helper can then call another template helper on the same instance.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
