### ISSUE TITLE
Strangely adding events to parent template

### ISSUE THREAD

**Issue by hwillson** [meteor/blaze#233]
Moving this over from meteor/meteor#7386.

----

(originally reported by @arashnewday)

I just find out Meteor adds events to parent template instead to specified elements

Best way to describe this issue is by giving example:
e.g. I have **todosList** and **todo** templates:

```
<template name="todosList">
    <div class="content-scrollable" id="content-scrollable">
            {{#each todo}}
                {{> todo}}
            {{/each}}
    </div>
</template>
```

```
<template name="todo">
    <div class="todo-item">{{text}}</div>
</template>
```
and:

```
Template.todo.events ({
    'click .todo-item: function () {
             // do something
    }
});
```

Here is the issue, **click event** will be added to `<div class="content-scrollable" id="content-scrollable">` which is a parent template element **multiple times**, as many times as i have todo items in this session. this is not normal behavior of JavaScript and it may cause problems and overhead event triggering specially for events like mousemove and scroll

[see image in original post]

**By the way why it using jQuery for handling event?!?**

Meteor 1.3.4.1 , Chrome 51.0.2704.106 , Firefox 47.0 , OSX El Capitan 10.11.5

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
