### ISSUE TITLE
Template instance namespace pollution

### ISSUE THREAD

**Issue by steph643** [meteor/blaze#240]
The concept of **view** is very common in programming.

For example, the [ProseMirror](http://prosemirror.net/) text editor requires that you create an object of type `EditorView` in `onRendered` and that you destroy it in `onDestroyed`. So you naturally end up adding a `view` property to your template instance... Bing, you have just broken your app in very subtle ways, by destroying Blaze's own [view](http://blazejs.org/api/templates.html#Blaze-TemplateInstance-view) property.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
