### ISSUE TITLE
#each block rerenders all objects in list when a new one is added/removed

### ISSUE THREAD

**Issue by BenjaminMerlynS** [meteor/blaze#241]
Hello,
I created a tab system in my meteor app (using simple bootstrap tabs). Each tab is rendered dynamically and displays a template. These tabs are rendered with a _Blaze #each block_. 
When I add a new tab, an element is added to the object array serving the #each block. In the same way, when the user closes a tab, it gets removed from the object array.

**The problem is that blaze rerenders all the tabs (and the templates in these tabs) on each array change instead of just rendering the new tab/template or destroying the tab/template.**

This really affects the overall app speed dramatically, making it almost unusable (wait times for up to 15 seconds...)

I read that this is "normal" blaze behaviour in an old post... Is there a way around this issue ? like for example another block that just adds or removes the element from the page without rerendering all of it?

Thanks in advance!

**Comment by janat08** [comment]
I think the issue here is probable lack of _id prop on objects, or shifting rather than pushing. Then there're systems in smart component that are meant to limit re-renders.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
