### ISSUE TITLE
_uihooks and friends

### ISSUE THREAD

**Issue by talha-asad** [meteor/blaze#246]
Somethings need to be improved:

1. _uihooks need to be documented.
2. insertElement hook needs to receive parent as the third argument, because sometimes next is null, particularly when the node needs to be inserted at the very end of it's parent. In this case, the parent is not available to the hook to be able to add the node.

I can submit a PR for 2, I am not good at documenting so maybe someone else can take up on that.

CC @mitar

**Comment by mitar** [comment]
I would just made a public interface for this, no need to keep it private. Then we can document it. And then we can break backwards compatibility and provide `parent` as well.

BTW, [Blaze Components do provide `parent` in its hooks](https://github.com/peerlibrary/meteor-blaze-components#low-level-dom-manipulation-hooks).

**Comment by talha-asad** [comment]
Looks like a pretty good approach. I look forward to this, let me know if you want me to contribute to this.

**Comment by mitar** [comment]
Feel free to do a take on it.

I am also not sure why hooks would not be called always, why just for list elements. But that is maybe another story. :-)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
