### ISSUE TITLE
Access object property names with spaces in them

### ISSUE THREAD

**Issue by dcantatore** [meteor/blaze#247]
I can't find a way to access a pass object property whose name has a space in it. Is this a known problem? I couldn't find it in the docs.

Example:
```

{{#each name in names}}
  {{> nameThing}}
{{/each}}

<template name="nameThing">
<p> {{this.name.profile["First Name"]</p>
.....

```

I know that object properties names generally shouldn't have spaces but I'm working with an existing db that stores them this way.

normally in js you can access them in that way with ["property name"] .

**Comment by sbr464** [comment]
If you can't access it directly, you can create a global template helper to do this easily:

```
Template.registerHelper('keySpace', (item, key) => {
  return item[key];
});

```

Then in the html, use it like this, dataObj referring to the object in context:

```
<h1> The info is {{keySpace dataObj "key with space"}} </h1>
```
