### ISSUE TITLE
Migrate all still relevant issues from Meteor main repository to this repository

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#25]

**Comment by MiroHibler** [comment]
Who do you think would be the best for this task, someone at MDG or we can do it by ourselves?

**Comment by mitar** [comment]
I think we should just crowdsource this. So any community member who would like to help should go over:
* https://github.com/meteor/meteor/issues?q=is%3Aopen+is%3Aissue+label%3AProject%3ABlaze
* https://github.com/meteor/meteor/issues?q=is%3Aopen+is%3Aissue+label%3AProject%3ABlaze%3ASpacebars
* https://github.com/meteor/meteor/issues?q=is%3Aopen+is%3Aissue+label%3AProject%3ABlaze+label%3AProject%3ABlaze%3AComponents

And see if an issue is still relevant. If a community member reading it endorses the issue, then they should copy it over, linking both issues with references. If they do not think it merits moving it, they should inform/comment on the original issue on Meteor that if author of the issue still thinks that the issue should be resolved, they (author) should open it here themselves.

MDG can go later on over the same issues and close them or lock them or something like that.

**Comment by MiroHibler** [comment]
With all due respect, even though it sounds like a good plan, I kinda doubt MDG will have time/resources to do it in a near future.

**Comment by mitar** [comment]
To do what? Close tickets which the community migrated? I do not think this would be a lot of work.

**Comment by MiroHibler** [comment]
Yeah, **we** don't think, but they have their own agenda and priorities, and honestly, I don't think Blaze is anywhere near the top of that list ;)

**Comment by mitar** [comment]
We will see. The plan is not dependent on that. So I am not sure what is the problem here? If they do not want to invest time to cleanup core Meteor repository, then this is their problem. Not sure what are we discussing now exactly.

**Comment by MiroHibler** [comment]
We're discussing whether we should wait for them (a potential showstopper) or just step in and do it by ourselves (the community)?

**Comment by mitar** [comment]
I do not think we are discussing that. :-) At least my plan was not to wait on them, but to ask community to help migrating. And then at the end MDG can close tickets we migrated.

**Comment by StanLindsey** [comment]
@mitar - can we add some additional labels for migrating things over:
feature
blocking
docs

And whatever else may be needed?

**Comment by mitar** [comment]
I added `blocking` and `documentation`. We already have `bug` which for me is for confirmed bugs. I do not like ideas for `feature` label because often it is tricky to know what is a new feature what is a bug, or slight improvement over a bug. So personally I prefer simply to not label those in any special way. But if community likes to have that label, we can add it.

**Comment by StanLindsey** [comment]
Can we get MDG to close issues that we've moved over? So our issue to-do list shrinks, we don't have any duplicates and its easier to search for ones not moved.

**Comment by laosb** [comment]
Yeah, that's important. Could we just come up with a system like nodebug.me to make it easier for community to contribute in issues?

**Comment by laosb** [comment]
I have an idea about the development of Meteor Community. See there ourmeteor/discussions#1

**Comment by mitar** [comment]
OK, let's start moving all issues now here. This is where community can really help now.

**Comment by hwillson** [comment]
Hi @mitar - this is now done (see https://github.com/meteor/meteor/labels/Project%3ABlaze). Thanks!

**Comment by mitar** [comment]
Amazing! Can you also migrate other Blaze issues? Like Blaze:Spacebars?

**Comment by hwillson** [comment]
Sure thing - I'll get those migrated next.

**Comment by hwillson** [comment]
Hi @mitar - I think that's it - all open `Project:Blaze`, `Project:Blaze:Spacebars` and `Project:Blaze:Components` issues have been moved over. Thanks!

**Comment by mitar** [comment]
Amazing! Thanks so much!
