### ISSUE TITLE
Spacebars each loop removes "selected" attribute

### ISSUE THREAD

**Issue by brucejo75** [meteor/blaze#250]
When I put an `<option selected="selected">` tag within a spacebars `#each` loop the `selected` attribute disappears off the `<option ...` tag.

### Environment
- Meteor v1.4.4.1
  - blaze@2.3.2
  - blaze-html-templates@1.1.2
  - blaze-tools@1.0.10
- Windows 10

### Repro
`>meteor create testselect`.

- Added this html to the `"hello"` template:
```
<select>
  {{#each item in list}}
    <option selected="selected">{{item}}</option>
  {{/each}}
  <option selected="selected">foo1</option>
  <option selected="selected">bar1</option>
</select>
```

- Added this helper to `Template.hello.helpers`:
```
  list() { return ['foo', 'bar'];}
```

Run `meteor`.  I take a look at the elements using chrome debugger and this is what I see:
![select issue](https://cloud.githubusercontent.com/assets/14342237/25317414/1d1bd90a-282d-11e7-969d-99f28f1a4faf.png)

You can see that the `<options>` within the `#each` loop lose their `selected` attributes.  But the `<options>` outside of the `#each` loop retain their `selected` attributes.

### Expected
Expected `selected` attribute to be set as I had set it with in an `each` loop.

### Notes
I tried multiple variations of trying to set the `selected` attribute.  Nothing works.
This makes it unnecessarily hard to use spacebars with select elements.

This might be related to #210?

**Comment by brucejo75** [comment]
I did a little digging around and I see that Blaze believes the attribute on my option tag is `selected=""` in [attrs.js](https://github.com/meteor/blaze/blob/f5791658aa1b7a013e2e0c1ee62ec12f397b3345/packages/blaze/attrs.js#L327).  But I statically set them all to `selected="selected"`.

Somewhere Meteor/Blaze is seeing `selected="selected"` and dropping the value.  If someone can point me where to look, I can pursue it further.  I do not quite understand how / where the template is compiled.  I assume somewhere it produces a fragment for my `<option selected="selected">` tag.

Also, any workaround welcome!

**Comment by mitar** [comment]
Can you try with v2.1.9?

**Comment by brucejo75** [comment]
Hi @mitar,

Can you explain how I can downgrade blaze?  I have tried:
```
meteor update blaze@2.1.9
meteor update blaze@=2.1.9
```
change `versions` file `blaze@2.3.2` => `blaze@2.1.9` & add `blaze@2.1.9` to the `packages` file.

downgraded my meteor version to 1.4.2.3, but it still had `blaze@2.3.2` in it.

Nothing seems to be able to change the version of blaze for me.  Thanks for any help!

**Comment by mitar** [comment]
This is not a bug. You have multiple options set to selected and the last one gets selected. Change your HTML snippet to:

```
  <select>
    <option>foo1</option>
    {{#each item in list}}
      <option selected="selected">{{item}}</option>
    {{/each}}
    <option>bar1</option>
  </select>
```

And you will see that the option with `bar` will be selected. Because it is the last one set to selected.

Also, there is a difference between DOM element property and HTML attribute. Blaze correctly sets selected property on elements, so option behaves like selected. But the HTML attribute does not expose that because it is not done through HTML attribute manipulation but by directly setting the property.

Read more about that:
* https://stackoverflow.com/questions/6003819/properties-and-attributes-in-html
* in #210 comment:

> The second thing, that `selected` attribute is not set is by design and with explicit exception for this in the code. Blaze sets only property for `selected` and `checked`. You can see that on the DOM element. Property is set, but attribute is not. The attribute in fact corresponds to the `defaultChecked` property. See more discussion about this in [jQuery documentation](https://api.jquery.com/prop/).

**Comment by brucejo75** [comment]
Hi @mitar, D'oh.  You are right.

But here is what I was really trying to accomplish.  I am using [bootstrap-select](https://silviomoreto.github.io/bootstrap-select/) and in order to set the default value I need to have the html with a `selected` attribute set to `"selected"`.  Essentially, bootstrap select converts a select to a specialized button.  So it counts on the initial html for setting the default(s).

I figured out a hack: I can add an attribute (e.g. `value`) that I put the initial value(s) into.

Is there some reason why the code actively deletes this attribute from the HTML?

Thanks!

**Comment by mitar** [comment]
It does not delete it from HTML. It does not render it in the first place. Blaze templates are just in the form of HTML, they are not HTML.

I would instead of trying to configure your library through a template instead use `onRendered` and call a method to set which value is selected.
