### ISSUE TITLE
Template.instance() "broken" in event handlers

### ISSUE THREAD

**Issue by zimme** [meteor/blaze#251]
I believe that `Template.instance()` is broken since this commit https://github.com/meteor/blaze/commit/3d7a3e75488b5c1c46840f449b910133edef76ba.

I have a vauge memory that `Template.instance()` and `templateInstance` given as the second argument in an event handler should be different instances when a handler is defined on a parent template but triggered from a child template. i.e. in the case of a click event defined on the list template where each row is its own template. Kind of the same way the context of the handler is based on in which template the event was triggered.

**Comment by mitar** [comment]
No, `template` is always the same as `Template.instance()`. See investigation done here: https://docs.google.com/spreadsheets/d/14DTa0096y7cA1wkbUXUo_lLPwHJji0ft14_9EnArhsM/edit#gid=0

But I completely agree that it is pretty inconsistent and hard to use. This is why I fixed all that in [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) but in Blaze it has to be kept for backwards compatibility like it is.

See discussion here: https://github.com/meteor/meteor/issues/3249

**Comment by mitar** [comment]
Can you make a test which works in version of Blaze before that revision and breaks now?

**Comment by zimme** [comment]
I'll look into it something this week.

**Comment by zimme** [comment]
Looked into this with version going back to 1.0 and if `templateInstnace` and `Template.instance()` ever were different it was pre-1.0.

Maybe I'm confusing this with the data context, which work this way.
