### ISSUE TITLE
Attribute helpers do not work as specified in docs

### ISSUE THREAD

**Issue by coagmano** [meteor/blaze#254]
In the documentation for [attribute helpers](http://blazejs.org/guide/spacebars.html#Attribute-Helpers) the example shows applying style attributes as an object:
```
Template.foo.helpers({
  attributes() {
    return {
      class: 'A class',
      style: {background: 'blue'}
    };
  }
});
```
providing an object to style like this gives the following error:
```
Exception in defer callback: Error: Unexpected object in htmljs in toText: [object Object]
    at HTMLVisitorSubtype.visitObject (http://localhost:3000/packages/htmljs.js?hash=1ac878018eee6c53ed1375dc7ee75fc6865666ae:292:11)
    at HTMLVisitorSubtype.visit (http://localhost:3000/packages/htmljs.js?hash=1ac878018eee6c53ed1375dc7ee75fc6865666ae:113:31)
    at Object.HTML.toText (http://localhost:3000/packages/htmljs.js?hash=1ac878018eee6c53ed1375dc7ee75fc6865666ae:668:18)
    at Object.Blaze._toText (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2468:15)
    at Blaze.View.updateAttributes (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1586:41)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934:20
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12)
    at http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1932:29
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271:12)
    at viewAutorun (http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1931:18)
```

Instead I need to assemble the string for the style attribute myself:
```
return {
    class: 'layout-item',
    style: `width: ${area.width}px; ` +
           `height: ${area.height}px; ` +
           `transform: translate3d(${area.x}px, ${area.y}px, 0);`,
}
```

Ideally, the attribute helper should flatten a style object, or as a minimal change, the docs should not have code that produces exceptions

**Comment by mitar** [comment]
Hm, seems to be a bug. There is [special handling of style attribute](https://github.com/meteor/blaze/blob/master/packages/blaze/attrs.js#L141) so I am not sure why this is being triggered. Care to investigate?

**Comment by coagmano** [comment]
As far as I can see in [`attrs.js#L141-L188`](https://github.com/meteor/blaze/blob/master/packages/blaze/attrs.js#L141-L188), the handler only deals with fully parsed strings, not a dictionary. 
From following the execution via the debugger, by the time it reaches the `StyleHandler` it's recieved a string of `"[object Object]"`

Boss won't be happy I'm tracking down this bug rather than using the workaround, but I'm going to keep digging haha

**Comment by coagmano** [comment]
Okay, so when the tag materializer converts the attributes to strings [here](https://github.com/meteor/blaze/blob/84c58a651c2cfbb3de825811a7b580afb7382f74/packages/blaze/materializer.js#L126-L142) it has no special handling for attributes like a style block. 

When it asks Blaze to convert to text (ultimately via [`HTML.ToTextVisitor`'s `visit` method](https://github.com/meteor/blaze/blob/ccafbb0f5e9d55a2ecb5222880ad4c3a697530b3/packages/htmljs/visitors.js#L37-L72)) it complains that it doesn't deal with objects.

**The question now is, where is the best place to convert styles before stringifying them for setAttribute?**

I tend to think that [here](https://github.com/meteor/blaze/blob/84c58a651c2cfbb3de825811a7b580afb7382f74/packages/blaze/materializer.js#L130-L137) we could test for an `attrName` of `'style'` and flatten the object into a style attribute string?

**Comment by MiroHibler** [comment]
I found a way to integrate it (#260) in [html.js#L216-L240](https://github.com/meteor/blaze/blob/956709d7cad0f0c96c97796aa78e6124918a2e29/packages/htmljs/html.js#L216-L240).

Not sure if it's the right place but it seemed so to me while debugging ;)

**Comment by mitar** [comment]
I do not think this is the right place because it will work for any attribute with object value, not just `style` one?

**Comment by MiroHibler** [comment]
Are there any that shouldn't be 'flattened'?

**Comment by coagmano** [comment]
Thanks for fixing this @MiroHibler!
I'd prefer to be specific about flattening the style attribute to minimise risk of unintended consequences. 
It's a good question though, and I can't think of any other attributes that would accept an object.

As an extension of this, it would be great if we accepted both css definitions and their js counterparts (ie. `elem.style.backgroundColor`) in flattening, hyphenating the js variant as required. This would mirror how [`Element.style`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style) worksin the DOM API. ie:
```
const attrs = {
   style: {
        backgroundColor: 'rebeccapurple', // js style, or
        'background-repeat': 'no-repeat' // css-style
    }
};
```
should both flatten to:
```
attrs = {
    style: 'background-color: rebeccapurple; background-repeat: no-repeat;'
}
```

**Comment by mitar** [comment]
> Are there any that shouldn't be 'flattened'?

Hm, I did play in the past with some object instances which have `toString` defined and then expect that to be rendered to Blaze. Not sure if it worked directly though (does Blaze use `toString` to serialize an object).

I use [such method myself](https://github.com/peer/mind/blob/master/packages/ui-components/base.coffee#L76). So an explicit cast. This allows me to have components extending each other which call the parent method to add more styles and then in the template I just render all of them together.

```handlebars
<div {{style myStyleObject}}>
```

Where `myStyleObject` is a method on the component returning a dict.

What you are asking for, if I understand, that this would be done automatically by:

```
<div style={{myStyleObject}}>
```

**Comment by mitar** [comment]
So I would be OK with this being magical, but just for `style` attribute.

(BTW, you could also make it magical for `class` attribute, where one would expect an array of strings.)

**Comment by mitar** [comment]
BTW, can somebody check if this maybe already worked in v2.1.9? We changed some logic around attributes in later versions so we might broke that?

**Comment by MiroHibler** [comment]
> (BTW, you could also make it magical for class attribute, where one would expect an array of strings.)

That has already been implemented, though not specifically for `style` attribute but for [any attribute](https://github.com/meteor/blaze/blob/master/packages/htmljs/html.js#L226).

That's why I also avoided to filter by property type/name. Though I could've tested against the `style` value (object) being constructed ([`HTML.isConstructedObject()`](https://github.com/meteor/blaze/blob/master/packages/htmljs/html.js#L180)) and it would also make sense to check whether a `style` value object has also values being functions, like:

```javascript
attrs = {
  class: [ 'btn', 'primary' ],
  style: {
    background: function () {
      return ( active ) ? 'green' : 'gray';
    }
  }
}
```
and invoke them for values, but that would be an enhancement (it could also work for other attributes).

As for

```handlebars
<div style={{myStyleObject}}>
```

that could work if we adapt [`Spacebars.mustache()`](https://github.com/meteor/blaze/blob/master/packages/spacebars/spacebars-runtime.js#L82) to not serialize objects but return them instead.

**Comment by coagmano** [comment]
Just went through the diff from v2.1.9 to master and couldn't find anything that would flatten a style object into a string.

Happy to do any other work to make this happen if needed?

**Comment by mitar** [comment]
> Just went through the diff from v2.1.9 to master and couldn't find anything that would flatten a style object into a string.

Can you run your example against the 2.1.9 version to be sure. We did have changes how attributes are handled.

**Comment by rub1e** [comment]
FYI this still seems to be an issue - I'm on Meteor 1.6 and Blaze 2.3.2 - getting the same error as https://github.com/meteor/blaze/issues/254#issue-233493045

Might be an idea to update the docs until this is fixed?

**Comment by coagmano** [comment]
Is there a reason that PR #260 hasn't been merged?

**Comment by mitar** [comment]
There are no tests, the fix is unclear if it is in the right place (it is merging thing for all attributes and not just for style), and nobody checked yet if this worked in 2.1.9 when we had the last change in this code.

**Comment by coagmano** [comment]
Okay, if @MiroHibler doesn't come back to it I'll take a look later this week at progressing this

**Comment by MiroHibler** [comment]
Hey @coagmano, I'm owfully busy these days. I might come back to it in a week or so, but if you cannot wait, please, be my guest :)

**Comment by coagmano** [comment]
Okay so looking at this again I'm still unsure of the right place for the style flattening to go.

Following the flow you find:
1. Start in `Blaze._materializeDOM` > `materializeDOMInner`> `materializeTag`
1. `materializeTag` creates autorun with `updateAttributes`
1. `updateAttributes` runs immediately
1. calls `Blaze._expandAttributes`
1. creates a `Blaze._HTMLJSExpander` and calls `visitAttributes`on it
1. Now we're in the compiled template
```javascript
HTML.DIV(HTML.Attrs(function() {
    return Spacebars.attrMustache(view.lookup("styleAttrs"));
}),
```
1. We look up the helper that returns the object with a key `style`
1. That helper function is passed to `Spacebars.attrMustache` 
1. Which is resolved via `Spacebars.mustacheImpl` to the object
1. **Back in `Spacebars.attrMustache` is the first place I think it could go since it deals specifically with attrs**
1. Which returns verbatim
1. We end up in `HTML.TransformingVisitor.visitAttributes` with the object 
(**I think this is the best place I think since it's a transforming function that deals with attrs**)
1. Then we go through `this.visitAttribute` > `this.visit` > `this.visitObject` > returns back through to `TransformingVisitor.visitAttributes`
  (**this.visit would be a good place, but we don't have access to the name of the key here so don't know it's a `style` object**)
1. This takes us back to `blaze/materializer.js`'s `materializeTag` function (as the result of `Blaze._expandAttributes`, could be a contender)
1. **Between `_expandAttributes` and `flattenAttributes` would also work, and call out to a style converter?**
1.  Through `HTML.flattenAttributes` (**@MiroHibler's chosen spot for the style flattening**)
1. `materializeTag` Then sends the object through `Blaze._toText` > `HTML.toText` > `HTML.Visitor.visit` > `Visitor.visitObject` > throws Error

So we have options in 4, 6, 7, 9, and 10.

Any thoughts on the best place?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
