### ISSUE TITLE
Blaze / Meteor 1.5 issue

### ISSUE THREAD

**Issue by alanwunsche** [meteor/blaze#255]
When I updated my Meteor app from 1.4 to 1.5, I started getting the following error and the app would not run.  Does anyone know why? Thanks

Uncaught SyntaxError: Unexpected end of input
blaze.js?hash=f33d3df…:1898

and other errors like this:
Uncaught TypeError: Cannot read property 'Blaze' of undefined
at spacebars.js?hash=ebf9381…:22
at spacebars.js?hash=ebf9381…:335

I have an unsolved thread here: https://forums.meteor.com/t/blaze-html-templates-error-in-meteor-1-5/37003

**Comment by mitar** [comment]
cc @benjamn

**Comment by benjamn** [comment]
Optimistic initial question: does `meteor reset` help?

**Comment by alanwunsche** [comment]
Based on someone else's help( https://forums.meteor.com/t/blaze-html-templates-error-in-meteor-1-5/37003/15 ), I tried this but it did not help: 

Remove:
- .meteor/local directory
- node_modules directory

Then:
- Run meteor npm install --save
- Run meteor update --packages-only

**Comment by alanwunsche** [comment]
Do I have to now explicitly import Blaze in Meteor 1.5 even thought it's a Meteor package?

**Comment by abernix** [comment]
@alanwunsche As long as you've got the `blaze-html-templates` package in your `.meteor/packages` file, you should not need to.

Could you copy your project to a new project and start incrementally removing pieces of it until the problem goes away (until you've basically deleted everything and got it back to a bare(-ish) Meteor app?  If you can and you could provide that reproduction, that would be quite helpful!

**Comment by alanwunsche** [comment]
I just realize that after I upgraded to Meteor 1.5, I never cleared browser cache.

So, I just took a Meteor 1.4.2 ... upgraded it to 1.5, then reset the browser cache before running.

The errors I was receiving before are not there.

Now, my error is:
Uncaught ReferenceError: Buffer is not defined

at der.js (modules.js?hash=50bea21…:49127)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at index.js (modules.js?hash=50bea21…:48829)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at elliptic.js (modules.js?hash=50bea21…:48815)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at index.js (modules.js?hash=50bea21…:48788)

Clicking on the error link:
var EC_PRIVKEY_EXPORT_DER_COMPRESSED = new Buffer([

**Comment by dr-dimitru** [comment]
@alanwunsche [here is solution](https://github.com/meteor/meteor/issues/8645#issuecomment-298349964)

**Comment by mitar** [comment]
OK, this seems now unrelated to Blaze. Closing.
