### ISSUE TITLE
Meteor serving server-side rendered Blaze templates

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#26]
After #16, we should try to get Meteor to serve server-side rendered Blaze templates.

**Comment by nicejwjin** [comment]
yeah. serverside rendering issue couldn't be disappeared in this life, so could be solved. possibly attached with phantom.js by single package to be implemented easy.

**Comment by brown2rl** [comment]
@mitar what do you mean by server-side rendering?  something like support for 
```
if (Meteor.isServer()) {
  if (Route.current.name == 'lists') {
    Meteor.render({ function() {
        {{#each list in lists}}
          {{> listUI }}
       {{/each}}
        }, listsCB});
 }
}
```

**Comment by mitar** [comment]
No, this ticket is about serving rendered content, so more like make sure this works for Blaze: https://github.com/kadirahq/flow-router/tree/ssr

**Comment by mitar** [comment]
Compilation is needed first: #223

**Comment by janat08** [comment]
With the new package https://github.com/meteor/meteor/blob/master/packages/server-render/README.md that has a bunch of blaze people move to and complain in forums:
https://forums.meteor.com/t/how-to-use-server-render-with-blaze-html-templates/37963/6

**Comment by antoninadert** [comment]
Any idea how this would be possible today? I still would love to see this happen, I can of regret we were forced to move to React because of this feature (mostly)

**Comment by janat08** [comment]
subs cache does it.

**Comment by kenshinman** [comment]
Imagine I have an already running project built with blaze, moving it to react is not an option now, but I would love to se ssr with blaze

**Comment by antoninadert** [comment]
Yesterday I got an answer on [this meteor forum thread](https://forums.meteor.com/t/why-i-believe-in-blaze/42242/51)

Basically, it says that https://atmospherejs.com/meteorhacks/ssr
still works today, and that it enables SSR for Blaze.

I didn't have chance to check by myself. Can anyone comment?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
