### ISSUE TITLE
First load optimization with prepack.io

### ISSUE THREAD

**Issue by janat08** [meteor/blaze#262]
https://prepack.io
So we use tracker a lot, setting dependencies and computations and such, I belief this makes us initialization heavy and hopefully deterministic enough to be able to be optimized. Suppose blaze-components may be inline with optimizations this is looking to provide when targeting react.

**Comment by mitar** [comment]
Does prepack understands Tracker semantics? Otherwise I would be surprised it prepack would work well for Blaze.

What type of optimization you care about? CPU load or bandwidth load?

**Comment by janat08** [comment]
It is not production ready even, but my take is that it.... :
"Symbolic Execution
In addition to computing over concrete values, Prepack's interpreter has the ability to operate on abstract values which typically arise from environment interactions."
So the whole deal with reactive vars/dependencies starting up and getting bound to computations may get fast as shit. We don't have to adapt virtual DOM.

**Comment by janat08** [comment]
In regards to semantics, the demo from linked official homepage can produce some pretty weird ass code, so i bet it gets it (in terms of semantics).

**Comment by janat08** [comment]
We may even go ahead and make everything reactive, imagine not ever having to bother with session stuff and etc, rellying on prepack to sort out what is in fact a dependency making up for our shite tracker :d.

**Comment by janat08** [comment]
https://github.com/meteor/meteor-feature-requests/issues/145

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
