### ISSUE TITLE
Blaze and Dynamic Imports

### ISSUE THREAD

**Issue by msavin** [meteor/blaze#263]
Would it be possible, or is there interest in, to make Blaze work via dynamic import?

Edit for clarification: not to make Blaze templates work over dynamic imports, but Blaze itself

**Comment by mitar** [comment]
I think that would be great. I assumed it should just work, but I have not yet tried it. Does it not?

**Comment by mitar** [comment]
I think this could be a good candidate to spend some [donations](http://opencollective.com/blaze) on it. So to keep Blaze up to date with new Meteor developments.

**Comment by msavin** [comment]
I believe Blaze would have to switch to import/export, and from my look at the repo, it is not the case.

The good news is, entire packages can now be dynamically imported:
https://github.com/meteor/meteor/issues/8745

**Comment by coagmano** [comment]
I've already been using blaze templates with dynamic imports.

Here's a contrived example of how:
```
// eg: you have main.js and three files for your template foo.html, foo.js, and foo.css
// main.js:
FlowRouter.route('/foo', {
    waitOn() { return import('/imports/ui/foo') },
// OR from a package:
    waitOn() { return import('meteor/bar:pack/ui/foo') },
    action() { this.render('layout', 'foo') }
});

// foo.js
import './foo.html'; // import blaze template as html/jade/etc
import './foo.css'; // import css/scss/less/etc
// ^^^ These will both be included in the bundle when foo.js is dynamically imported.
Template.foo.onCreated(function () {
 /// etc.
});
```
And the templates are excluded from initial bundle!


If you're using packages, the key things are:
 - to not reference the template files in `package.js`
 - if using `mainModule`, specify lazy loading: `Api.mainModule('foo.js', 'client', { lazy: true })`

**Comment by coagmano** [comment]
Maybe this belongs in the Blaze docs?

**Comment by mitar** [comment]
@coagmano, this looks amazing. Care  to do a PR for dos?

**Comment by coagmano** [comment]
Sure, I'll knock something up over the weekend

**Comment by msavin** [comment]
Indeed - Blaze already works with dynamic imports. However, what I mean is making the Blaze package itself dynamically importable. 

This can be big because, as we can see, we can import packages on demand. This means we could have one front-end written in Blaze, and the other in React, with-in the same app. It would be great if we could load the right FE into the app when needed instead of placing it in the entire bundle.

**Comment by mitar** [comment]
What are changes MDG did to core packages to make them dynamically importable?

**Comment by coagmano** [comment]
That would be a big, and useful, change!
I just checked a few packages in core and couldn't find any that are configured for dynamic loading. Maybe because they would stop working for apps running without `ecmascript`? 

Do you know if you can `require` a package with `api.mainModule('foo.js', 'client', {weak: true})` without `ecmascript` in the main app?

**Comment by msavin** [comment]
@coagmano do you mean import, or require in specific? I've been able to do so with only the dynamic imports package. However, I also noticed ecmascript is completely backwards compatible with ES5, so I no longer take it out. 

I think Meteor does some magic in regards to globals and import/export, where if you put an import statement into your file, it'll assume it works the module way, otherwise, it'll work the original way.

**Comment by msavin** [comment]
@coagmano do you think its possible to get Blaze working via Dynamic Import? It would help a ton because I need Meteor Candy to work with all front-ends, but without forcing Blaze into every client. I tried to run you repo but had some issues with it.

**Comment by coagmano** [comment]
I never ended up digging into this further, so I never got the package to a workable state

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
