### ISSUE TITLE
Provide stateless/functional version of Blaze templates

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#265]
It seems in many cases one can [benefit from stateless/functional versions](https://github.com/mitar/meteor-web-rendering-framework-benchmark). Both React and Vue support them to optimize for cases where you mostly group HTML tags together into what would be a Blaze template, but do not really keep any state around.

Maybe doing something similar would help Blaze as well. For example, a stateless Blaze template would not have its own reactivity and autorun context, but would use that of the parent.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
