### ISSUE TITLE
mouseenter and mouseleave triggering twice only on first run

### ISSUE THREAD

**Issue by michaelcbrook** [meteor/blaze#266]
Originally posted [here](https://github.com/meteor/meteor/issues/8935) but am moving this issue to the Blaze repo.

There is an issue where mouseenter and mouseleave trigger twice the first time they are run on an element, but every time after that, they run once as expected. Mouseover and mouseout work fine.

There are no children elements, so it is not a bubbling issue, and the element does not transform or change style.

[Here](https://github.com/michaelcbrook/meteor-mouseenter-bug) is a link to my reproduction of the issue.

Or `git clone git@github.com:michaelcbrook/meteor-mouseenter-bug.git`

Thanks!

**Comment by niranjans** [comment]
+1 

I'm facing the exact same issue.

**Comment by samuelhackwill** [comment]
+1, mouseleave triggers twice but mouseout works fine. (meteor 1.9.2)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.

**Comment by tenshis** [comment]
Weird reason to close this. It was barely a month old then and it's still a bug now, one and a half years later...

**Comment by jankapunkt** [comment]
@tenshis I can reopen if you want to help to resolve it. Do you have an app where this issue is relevant (so you could test potential fixes)? Which version of Blaze do you use? Is it maybe already fixed in 2.6.1?
