### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by YusifKhalilov** [meteor/blaze#270]
Sorry, I don't know do I posting in the correct place or not. But for beginners blaze documentation like Quantum Physics for 1st grade. Do you plan to write something normal with examples? 

I am about ["API - Blaze"](http://blazejs.org/api/blaze.html)

**Comment by JaimeVelasco** [comment]
Funny, I always thought Blaze had quite decent documentation.

**Comment by YusifKhalilov** [comment]
There are no explained examples.

**Comment by dandv** [comment]
@YusifKhalilov: [the tutorial](https://www.meteor.com/tutorials/blaze/creating-an-app) should help you understand Blaze better.

**Comment by YusifKhalilov** [comment]
I used blaze in my project before until got the problem and can't solve via the Blaze. I switched to the React. In the tutorial, it explains weak things. But when you diving deep into the Blaze and trying to read the documentation it is enough hard to understand how to use the methods.

**Comment by YusifKhalilov** [comment]
Thank you, everyone!
