### ISSUE TITLE
Native events initiated in a contentBlock can slip through event.stopPropagation()

### ISSUE THREAD

**Issue by nikparo** [meteor/blaze#272]
**Description:**
``` html
<template name="editor">
    <div id="editor">
        {{#modal}}
            {{> imageSelector}}
        {{/modal}}
    </div>
</template>
```

Consider that an event is triggered in the contentBlock `imageSelector`, and an event handler of `modal` attempts to stop it by using `event.stopPropagation()`. Blaze or jQuery event handlers of the template `editor`, do not receive it, however, from my testing it seems that native event handlers of `#editor` will:
``` javascript
Template.modal.events({
    'mousedown'(event, instance) {
        event.stopPropagation();
    },
});

document.getElementById('editor').addEventListener('mousedown', (event) => {
    console.log('I slipped through!');
});
->
'I slipped through!'
```
The event can still be stopped though a blaze event handler in `modal` using `event.stopImmediatePropagation()`, or by binding a handler to `modal` using jQuery or vanilla js. E.g.
``` javascript
document.getElementById('modal').addEventListener('mousedown', (event) => {
    event.stopPropagation();
});
```

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
