### ISSUE TITLE
Exceptions thrown by template helpers do not get source mapped in Chrome

### ISSUE THREAD

**Issue by mattmccutchen** [meteor/blaze#273]
I noticed that when an exception thrown by a template helper is logged by Blaze, its stack trace does not get source mapped, in contrast to an exception thrown by a Tracker autorun function.  Reproduction:

```
git clone https://github.com/mattmccutchen/meteor-exception-source-map-test
cd meteor-exception-source-map-test
meteor npm install    # https://github.com/meteor/meteor/pull/8165 ...
PATH/TO/CHECKOUT/meteor
# Open http://localhost:3000/ in Chrome, open the developer console, and click "Click Me".
```

Tracker was fixed in meteor/meteor#3655; see [this code](https://github.com/meteor/meteor/blob/1687537f6ea03312183059fed45f12f350de2f17/packages/tracker/tracker.js#L62).  Blaze has [its own exception logging code that hasn't received the fix](https://github.com/meteor/blaze/blob/750843824397a6f8062a6b1dcc884cacbd3bef85/packages/blaze/exceptions.js#L42).  I'm filing an issue here to plant a flag to help avoid duplicate work and will file a separate issue to factor out the Tracker code in a form that Blaze can call.

**Comment by mitar** [comment]
Thanks for reporting this.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
