### ISSUE TITLE
Error when compiling template in another frame

### ISSUE THREAD

**Issue by brucejo75** [meteor/blaze#275]
As part of my application I pre-compile templates on the server and then manually eval the pre-compiled template on the client.

As part of making that eval safe (in general) I am doing the eval in a separate frame that has very limited `sandbox` attributes. see [Play safely in sandboxed IFrames](https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/).

This all works swimmingly except for one small point.

[HTML.isArray](https://github.com/meteor/blaze/blob/v2.3.2/packages/htmljs/html.js#L173) cannot determine if an array returned by the iFrame is an array 😒. 

This is easily remedied by changing the [evaluation ](https://github.com/meteor/blaze/blob/v2.3.2/packages/htmljs/html.js#L177)to `x instanceof Array || Array.isArray(x)`

PR #276 submitted also

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
