### ISSUE TITLE
Log a warning if a template includes itself

### ISSUE THREAD

**Issue by ryangrahamnc** [meteor/blaze#278]
Made this mistake of typoing the name of a child template:
```
<template name="abc">
  parent
  {{> abc }}
</template>
<template name="abc_child">
  child
</template>
```
Line 3 should have been `{{> abc_child }}` when instead I did `{{> abc }}`, which caused an infinite loop.

I cant think of any instance where I'd want to include a template inside of itself, so I'd find it useful if such a case would log a warning to the console so I'd be able to figure out why I'm getting an infinite loop.

**Comment by fafournier** [comment]
Actually, a template calling itself is often used for recursive functions such as displaying trees. The calling arguments would obviously be different on each instance call, but this is a really common programming feature. 
There is also a normal "warning" system for this in javascript: the "max call stack exceeded". Didn't you get it in the console in this case?

**Comment by ryangrahamnc** [comment]
Ah, then a warning in the console wouldnt be a good idea.

I didnt get the max call stack error. Might be because I had a this.subscribe() in the autorun. What I got was a tab that was unresponsive and unclosable, with increasing ram usage until I killed it from chrome's task manager.

**Comment by fafournier** [comment]
Ah, this was probably a slow recursion. If you left it for a few hours, it would have gotten to it. Those bugs are some of the worst to find... ;-)

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
