### ISSUE TITLE
[idea] Blaze.remove(templateInstance)

### ISSUE THREAD

**Issue by trusktr** [meteor/blaze#28]
Currently we can do

``` js
Blaze.remove(this.view)
// or
Blaze.remove(template.view)
// or
Blaze.remove(Template.instance().view)
```

which also destroys the view's template. But that might not be as convenient as simply

``` js
Blaze.remove(this)
// or
Blaze.remove(template)
// or
Blaze.remove(Template.instance())
```

Suggestion: allow `Blaze.remove()` to accept a `Template` instance.

**Comment by HenriBeck** [comment]
Where is the benefit? When you have an instance you also have a view so that shouldn't matter.
I guess it's that way because Blaze.render() returns a view, not an instance.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
