### ISSUE TITLE
Blaze removes iframe contents when collection changes sort order

### ISSUE THREAD

**Issue by dandv** [meteor/blaze#281]
Posting here after getting [non answers on the forum](https://forums.meteor.com/t/blaze-removes-iframe-contents-when-collection-changes-sort-order/42275).

Am I missing something about how to protect iframes, or might this be a bug?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
