### ISSUE TITLE
Helper - Returning HTML-Node/Object

### ISSUE THREAD

**Issue by marvinside** [meteor/blaze#285]
I'd like to request a new Feature.

I am using a Helper to build some HTML:
```javascript
Template.registerHelper("menuItem", function (link, name) {
	let classnames = [];
	if(link === Router.current().route.path()) classnames.push("active");

	let classString = "class=\"";
	classnames.forEach(function(element){
		classString += element + " ";
	});
	classString += "\"";

	return new Spacebars.SafeString("<li "+classString+"><a href=\""+link+"\" >"+name+"</a></li>");
});
```

Currently this is pretty basic, but i plan to use more helpers to build parts of my HTML.

For performance reasons, i'd like to build the HTML with Javascript `document.createElement("li")` for example.

But if i'm returning a HTML-Element, i just get `[object HTMLLIElement]` in my HTML.

Is there already a way to achieve this? (Maybe an Internal function)

**Comment by arggh** [comment]
Why on earth are you not using just Blaze templates for rendering this stuff?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
