### ISSUE TITLE
scanHtmlForTags stops at first "matching" closing tag

### ISSUE THREAD

**Issue by ghybs** [meteor/blaze#286]
As described in this SO question: [How can I include an HTML `<template>` element within a Meteor Blaze Template?](https://stackoverflow.com/questions/37778490/how-can-i-include-an-html-template-element-within-a-meteor-blaze-template), it is currently not possible to use `<template>` tags within a Blaze template, i.e. as a child of the top-level `<template>`:

```html
<template name="test2">
    <template id="test3">Some stuff i will clone in javascript</template>
</template>
```

Whereas [the description for `TemplatingTools.scanHtmlForTags()`](https://github.com/meteor/blaze/tree/master/packages/templating-tools#templatingtoolsscanhtmlfortagsoptions) states: (emphases mine)

> Scan an HTML file for **top-level** tags […]

The [current algorithm](https://github.com/meteor/blaze/blob/v2.3.2/packages/templating-tools/html-scanner.js) to detect these tags in HTML files matches the first closing tag with same tag name, instead of making sure that this closing tag is correctly associated to the opening one (and not to a child tag):

https://github.com/meteor/blaze/blob/e511abba1d7e5d1ccc2461ecd2a2f5436da7ae49/packages/templating-tools/html-scanner.js#L112-L116

Therefore it stops at the first `</template>` and throws an error for the next `</template>`.

A possible solution could be to count how many opening tags (with the given tag name) appear in `tagContents` and skip the same amount of closing tags, until there are no opening tag left.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
