### ISSUE TITLE
How to use static-html and blaze-html-templates at once?

### ISSUE THREAD

**Issue by gustawdaniel** [meteor/blaze#288]
I want use vue as base of project but include also some blaze templates.

In client there is main.html. I need interpret this as static-html.
I also need compile all blaze templates in given catalog and use it like in

> https://github.com/Akryum/meteor-vue-blaze/blob/render-blaze/imports/ui/Widget.vue

Difference that I want to achieve is:

+ **entry point should be managed by vue**
+ **blaze compiler should be applied to selected location**

**Comment by arggh** [comment]
You might have a better chance of getting help on this from the meteor-vue repositories.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
