### ISSUE TITLE
Blaze reactivity bug with arrays and parentData

### ISSUE THREAD

**Issue by graemian** [meteor/blaze#29]
Assume template "outer" includes "inner" and passes it a data context with an array generated by a collection fetch(). If a helper in "inner" uses parentData() to access this context (from inside #each, for example), then the helper will be run twice when the data context changes. It should only be run once.

See https://github.com/graemian/blaze-extra-redraw . If you run 

```
col.insert({_id: "3"})
```

from the browser console, you will see logging statements showing that the helper is run twice. If you remove the line

```
Template.parentData(1);
```

the helper will only be run once.

Tested on latest Meteor devel (25 April 2016)

**Comment by mitar** [comment]
There is no limit on how many times helpers should run. Helpers are meant to be small and quick.

**Comment by graemian** [comment]
What do you mean by this: "There is no limit on how many times helpers should run" ? Surely the helper should run just once for every time the data context changes? My example shows that it runs twice, which suggests a problem with the dependency code?

In a performance-sensitive context, running small helpers unnecessarily causes problems. I am rendering a report with 8 columns and 50 rows, so running the cell helper unnecessarily 400 times makes a difference.

**Comment by mitar** [comment]
OK, from an optimization point of view you are of course right. We should minimize that. But from semantic point of view helper are run anytime they are needed.

In general Blaze registers dependencies much more often than needed.

And in general it is easier than try to minimize calling helpers is to minimize DOM changes. What I would worry is if Blaze would change DOM twice. If it calls helpers twice this is more or less something which was not optimized for to minimize.

It would be great if you could try to determine why it is calling helper twice. What triggers it? Is it called twice inside the same flush cycle? Or are there two flush cycles?

**Comment by graemian** [comment]
Shucks, I think all that is above my pay grade :-) I guess I can live with the slow performance for now.

However, my repo and instructions should make it easy for more highly-paid people to reproduce the problem.

**Comment by brown2rl** [comment]
Why not include a {{> cell}} template?

Sent from my Windows Phone
________________________________

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
