### ISSUE TITLE
Blaze standalone

### ISSUE THREAD

**Issue by camstuart** [meteor/blaze#290]
The website still mentions that blaze will one day be a standalone UI. Is this still planned?

I have tried all the major UI libraries and frameworks, and never been as productive as I was in blaze.

If it's not happening, or a long way off, can you suggest an alternative that works in a similar way?

**Comment by mitar** [comment]
So we are waiting for MDG to move some of core packages Blaze depends on to NPM. Only after that Blaze can move. But I have not seen any activity about that in quite some time.

**Comment by camstuart** [comment]
That's a shame, ok, thanks for the update @mitar I'll check back again later

**Comment by anomepani** [comment]
Is there any update for making Blaze standalone?

**Comment by znewsham** [comment]
@camstuart @anomepani I ported to npm here: https://www.npmjs.com/package/meteor-blaze-runtime it works nicely, but it does depend on a bunch of (potentially out of date) packages that people have extracted from meteor to npm by hand

**Comment by brettg2** [comment]
+1

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
