### ISSUE TITLE
Iterating array-elements as single values inside collection-document

### ISSUE THREAD

**Issue by TomokoOG** [meteor/blaze#293]
Already pursued attempts: 
- [Stackoverflow-Question](https://stackoverflow.com/questions/56506946/iterating-array-elements-as-single-values-inside-collection-document-meteor)
- [Meteor Forums](https://forums.meteor.com/t/iterating-array-elements-as-single-values-inside-collection-document/49197)

Goal is to display array-elements inside a collection-document as single values with blaze. 

None of these methods seem to work. What am I missing?

 
```
Template.onlineliste.helpers({
  roomData() {
    var name = FlowRouter.getParam('name');
    return Channels.findOne({name:name})
  },
});
```
Templatehelper, finding one document. Inside document is a key called inRoom, which holds an array: 
`inRoom: ["test1", "test2", "another3"]`

Template itself, trying to iterate the array-values as single values.

```
<template name="onlineliste">
  {{#with roomData}}
    <ul>
      {{#each name in this}} 
        <li>{{name}}</li>
      {{/each}}
    </ul>
  {{/with}}
</template>
```

Read the documentation. But wasn't really helpful for me. I would appreciate any help!

**Comment by coagmano** [comment]
If you're in a `#with` block, you want `{{#each name in inRoom}}`
```
<template name="onlineliste">
  {{#with roomData}}
    <ul>
      {{#each name in inRoom}} 
        <li>{{name}}</li>
      {{/each}}
    </ul>
  {{/with}}
</template>
```

Though I recommend not using `#with` and accessing inRoom as a property of roomData:
```
<template name="onlineliste">
  <ul>
    {{#each name in roomData.inRoom}} 
      <li>{{name}}</li>
    {{/each}}
    </ul>
</template>
```

**Comment by TomokoOG** [comment]
``` 
<template name="onlineliste">
  {{#if roomData}}
    <ul>
      {{#each name in roomData.inRoom}} 
        <li>{{name}}</li>
      {{/each}}
    </ul>
  {{/if}}
</template>
``` 
This is certainly something new. Everyone from the previous attempts suggested #with or a double-each. And this works. 

I was looking for something like this in the documentation of blaze.js but I couldn't find it. 

Anyway, thank you very much!

**Comment by TomokoOG** [comment]
I forgot to ask about another matter in the same category, I'm sorry.

How would it look like if I wanted to do the same (Iterating single values of array) if I'm inside {{#each Room}}.

I basically listed up every Chatroom like so

```
  {{#each channels}}
  <div class="roomWrapper"> 
    <form class="enterRoom">
      <b>{{name}}</b>  // <- name of Room itself
        <div class="inRoom"> 
          inRoom:
          {{#each name in channels.inRoom}} 
          <li>{{name}}</li>
          {{/each}}
        </div> 
           <input type="hidden" value="{{name}}" name="name">
           <input type="submit" value="🡺" class="roomJoin">
    </form>
  </div>
  <hr class="light_line">
  {{/each}}
```

using the helper like this 

```
channels() { return Channels.find({}, {sort: {createdAt: 1}}); },
```

I tried using {{#if}} for this case and another {{each}}-statement but this doesn't seem to work.

**Comment by coagmano** [comment]
Not sure of the exact semantics of `{{#each foo}}` since I always use `{{#each bar in foo}}` (purely personal preference), so I would do it like so:

```
{{#each room in channels}}
  <div class="roomWrapper"> 
    <form class="enterRoom">
      <b>{{room.name}}</b>  // <- name of Room itself
        <div class="inRoom"> 
          inRoom:
		  <ul> // <- I added the ul, in case you missed it
		    {{#each name in room.inRoom}} 
             <li>{{name}}</li>
            {{/each}}
          </ul>
        </div> 
         <input type="hidden" value="{{name}}" name="name">
         <input type="submit" value="🡺" class="roomJoin">
    </form>
  </div>
  <hr class="light_line">
{{/each}}
```
Which has the advantage of not having two different `{{name}}`s that do different things.

If you want to save on using `#if` with `#each` statements all the time, you can use [`Template.subscriptionsReady`](http://blazejs.org/api/templates.html#Blaze-TemplateInstance-subscribe). This requires you to subscribe to the collections from your template instance:
```
Template.channels.onCreated(function () {
  this.subscribe('channels');
});
```
```
{{#if Template.subscriptionsReady }}
  {{#each room in roomData}}
    ...etc
  {{/each}}
{{else}}
  <div class="loading-message">Loading...</div>
{{/if}}
```
And when using subscriptions you need that corresponding publication on the server:
```
Meteor.publish('channels', function() {
  return Channels.find();
});
```

---

Also, to help understand the reason loading solved the original issue, have a read of this guide to data flow in Meteor. It's much easier to debug these issues when you understand what's happening to the data (and all the race conditions that it causes)
https://medium.com/meteor-js/data-flow-from-the-database-to-the-ui-three-layers-of-meteor-d5e208b466c3

**Comment by TomokoOG** [comment]
I had to rewrite my code a little bit but it works fine now. Thank you once again!

> Also, to help understand the reason loading solved the original issue, have a read of this guide to data flow in Meteor. It's much easier to debug these issues when you understand what's happening to the data (and all the race conditions that it causes)
https://medium.com/meteor-js/data-flow-from-the-database-to-the-ui-three-layers-of-meteor-d5e208b466c3

I'll make sure to read it. I still have a lot of problems with the realtime dataflow.
