### ISSUE TITLE
Question: Blaze Equivalent Of React Portal?

### ISSUE THREAD

**Issue by chasemaier** [meteor/blaze#294]
I am trying to come up with a reliable solution to Modal Dialogs in our Meteor/Blaze application (mostly due to some annoying edge cases in Safari).

Essentially, the need is to place DOM entries for modal windows directly before the closing `</body>` tag. That way it is possible to be sure that there are no conflicts in terms of nesting context, the modal is not within some DOM element that has `position: relative;` or `overflow: hidden;`, or `z-index: 99999;` etc...

But at the same time, we'd really like to have the modal be defined and managed WITHIN / be attached to the relevant containing template and have access to the event handlers / data context / template lifecycle / etc.. of the component it is supporting / acting on.

I know that React handles this nicely with ["Portals"](https://reactjs.org/docs/portals.html). I was hoping there was an elegant way to reproduce this same concept in Blaze. Essentially -- a chunk of template code that remains attached to the template but is placed OUTSIDE the template at a designated location in the overall DOM (e.g. at the very end of document `<body>`).

Right now we have the modals move themselves to these locations immediately when they are "opened" but they do not remain within the template context and the moving of them around causes a lot of complications and cleanup logic that I feel could be avoided with a Portals-like capability where they remained attached to the containing template/component.

Is there any Blaze functionality I could look more into that could accomplish this?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
