### ISSUE TITLE
Add Blaze to the well-known Stefan Krause UI lib benchmarks

### ISSUE THREAD

**Issue by trusktr** [meteor/blaze#295]
It'd be nice to add Blaze tom the benchmarks over at https://www.stefankrause.net/js-frameworks-benchmark8/table.html. It would need a PR onto https://github.com/krausest/js-framework-benchmark.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
