### ISSUE TITLE
http://blazejs.org/ is down

### ISSUE THREAD

**Issue by wiserweb** [meteor/blaze#297]

**Comment by mitar** [comment]
Works for me.

**Comment by coagmano** [comment]
@wiserweb are you using a plugin like HTTPS Everywhere?
Connecting on https does hang, and that plugin does silently upgrade requests to https

**Comment by mitar** [comment]
Where is the website hosted at all? :-)

**Comment by coagmano** [comment]
Looks like an S3 website:
```
❯ dig blazejs.org
; <<>> DiG 9.10.6 <<>> blazejs.org
;; QUESTION SECTION:
;blazejs.org.			IN	A

;; ANSWER SECTION:
blazejs.org.		1799	IN	CNAME	blazejs.org.s3-website-us-east-1.amazonaws.com.
blazejs.org.s3-website-us-east-1.amazonaws.com.	60 IN CNAME s3-website-us-east-1.amazonaws.com.
s3-website-us-east-1.amazonaws.com. 3 IN A	52.217.8.115
```

**Comment by mitar** [comment]
So let's open this as HTTPS does not work.

**Comment by wiserweb** [comment]
@coagmano  To confirm I was trying with Brave browser which upgrades to https like https everywhere.

Another interesting tidbit...

If you use cloudflare DNS over TLS via  `1.1.1.1` to access blazejs.org it can't find the domain. Did the guys from React put it on the block list? lol

If you use quad9, `9.9.9.9`  DoH it can find the domain.

**Comment by aon108** [comment]
I am also experiencing this issue tried different DNS settings also, is the site down for good?

**Comment by mitar** [comment]
This is now a different problem, currently we are migrating the domain to a different registrar, so I think downtime is because of this.

cc @filipenevola

**Comment by filipenevola** [comment]
Hey, it's fixed now.

The migration was finished but didn't bring the DNS settings, now I fixed.

**Comment by filipenevola** [comment]
Now Meteor Software owns this domain and we are using Route53 on AWS to set up it.

The content is still in the same bucket also in our account.

**Comment by mitar** [comment]
I made https://github.com/meteor/blaze/issues/311 for followup about hosting the site on HTTPS.
