### ISSUE TITLE
Provide architecture overview 

### ISSUE THREAD

**Issue by jankapunkt** [meteor/blaze#301]
I would love to contribute more to Blaze but it takes too long to dig through all the code in order to understand all the internals.

It would be great if some architectural overview would be provided. Does not need to be a full specified modeling language but something like C4 model with some additional paragraphs about which components do which job, rely on which would be so great.

**Comment by filipenevola** [comment]
This working is started here https://github.com/meteor/blaze/pull/312

**Comment by filipenevola** [comment]
Available here https://github.com/meteor/blaze/blob/master/OVERVIEW.md
