### ISSUE TITLE
onDestroyed is not called for templates containing only a Template.ContentBlock at top of outer template

### ISSUE THREAD

**Issue by coagmano** [meteor/blaze#304]
Was just playing around with a `clickAwayListener` HOC / block template which attaches a document event listener in onRendered and removes it in onDestroyed. I can't use an eventmap because I want to know if someone has clicked anywhere other than it's children. The only content of this template is `{{ Template.ContentBlock }}`

If I have this as the top item in another template (outer), the `onDestroyed` hook is never run. 
But if I have at least one DOM node before this block template is used, the hooks run fine.
Also, they fire fine if the parents of the outer template are also destroyed (ie. navigating to a new route)

I'm not sure what the root of the problem is, but I'm guessing it has something to do with `Blaze._InOuterTemplateScope`, which has a bunch of comments in the source warning that this is a weird hack.
Alternatively it might be because the DOMRange needs to be linked to something and if first actual node inside the outer template is after the HOC, it attaches to the parent of the outer instead?

I worked around the issue by only using it when it's nested inside a DOM node in the outer template, so low urgency.
Given the state of the Blaze project and that there's a workaround, I don't expect this to be fixed. I am writing up the issue as a reference in case it either affects more people or someone wants to fix it

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
