### ISSUE TITLE
Lazy load undefined Templates

### ISSUE THREAD

**Issue by jankapunkt** [meteor/blaze#306]
I was playing around with the lookup function and I found, that we could hook into the lookup function and load yet undefined Templates using dynamic imports.

```javascript
const myComponents = new Map()
myComponents.set('button', {
  load: async function () {
    return import('path/to/button')
  },
  loaded: false
})

Blaze.lookupProvider(async function (name) {
  const component = myComponents.get(name)
  if (!component) return  false
  if (component.loaded) return true

  await component.load()
  component.load = true
  myComponents.set(name, component)
  return true
})
```

**Comment by jankapunkt** [comment]
I have successfully implemented this feature and [published it in a package](https://github.com/jankapunkt/meteor-template-loader).

The code breaks down to ~150 lines (including comments already) and intercepts `Blaze.View.prototype.lookup` and `Spacebars.include`.

**Comment by filipenevola** [comment]
Hi @jankapunkt, is it documented on Blaze docs?

The work itself I believe is done.
