### ISSUE TITLE
Visual identity of the framework

### ISSUE THREAD

**Issue by alexandesigner** [meteor/blaze#31]
Guys, first of all, I would like to know if the blazejs has a visual identity, figures, logo or a graphic in which we can work to develop the [landing page](https://github.com/meteor/blaze/issues/24) and later a [documentation](http://docs.meteor.com/#/full/blaze_render).

I started playing and I've got to an advanced version, what do you think?

![logoblaze](https://cloud.githubusercontent.com/assets/3044907/14919025/2f210fc6-0dfd-11e6-8380-4916fdb2d52c.jpg)

**Comment by laosb** [comment]
That's great!

For documention I personally prefer Meteor Guide style instead of a new one. Or maybe another one. What do you think? @mitar

**Comment by laosb** [comment]
In next two days I could help with landing page.

**Comment by alexandesigner** [comment]
> For documention I personally prefer Meteor Guide style instead of a new one. Or maybe another one. What do you think?

That's right.. I was referring to the only documentation with respect to the content that we will explore in the docs.blazejs.com, we will extract from there and the Guide.

> In next two days I could help with landing page.

I can help on the front end also in addition to the design graphic.

**Comment by mitar** [comment]
I like the proposed visual identity. :-)

**Comment by kulttuuri** [comment]
Looks very slick. 👍

**Comment by StanLindsey** [comment]
Goodjob, 👍

**Comment by filipenevola** [comment]
Good job! +1

**Comment by kdanninger** [comment]
I like it, nice work!

**Comment by alexandesigner** [comment]
This was a clearer proposal, with few variations. I received some positive reviews, some suggestions, so I'm going to work on other variations.. https://github.com/alexandesigner/blazejs/issues/2

**Comment by ramezrafla** [comment]
Super cool -- really like.
My only comment for improvement would be to find a way to make the logo 'speak' as to what this library does.

**Comment by kdanninger** [comment]
@alexandesigner I'm going to start creating a website. Could you please share your design assets? `.sketch`, `.ai`, or `.psd` would be greatly appreciated

**Comment by alexandesigner** [comment]
@kdanninger Of course, I posted in dropbox, see link: 
https://www.dropbox.com/s/sjmf46u7fk6oyta/logoblaze.ai?dl=0 (.ai)

Which repository you will develop the site? I started working on a model using the hexo-theme of the meteor to the documentation, see: https://github.com/alexandesigner/blazejs, we may be able to take advantage of something Anyway, let me help you. I have a reasonable amount of time free to devote myself to this work..

**Comment by kdanninger** [comment]
Ah, very cool! Thanks @alexandesigner! I think the consensus I've read from the other issues on this repo is to use meteor+blaze to construct the site. Your docs are wonderful, I'll read through your source later tonight. I'm assuming that we will start porting documentation, and they need to be editable in markdown(?)

**Comment by mitar** [comment]
Don't worry about a repo for now. Just use whatever is easiest for you.

**Comment by mitar** [comment]
Using the same thing as Meteor for documentation sounds like a good idea. And landing page can then be Blaze + Meteor.

**Comment by alexandesigner** [comment]
> Using the same thing as Meteor for documentation sounds like a good idea

Exactly, I used the hexo-meteor-theme for docs that has been widely used by meteor in your guides. Editing using markdown (gh), see: [blazejs-docs](https://github.com/alexandesigner/blazejs).

@mitar  any ideas of who can help me with the organization of the content?

**Comment by mitar** [comment]
I would not worry about the content at the moment. Maybe prepare everything with lorem ipsum and then later on people can start making pull requests with real content.

**Comment by praneybehl** [comment]
👍  Nice!

**Comment by alexandesigner** [comment]
I did two other variations and a few changes in the first proposal suggested by @MiroHibler 
![proposals](https://cloud.githubusercontent.com/assets/3044907/15556875/8576a878-22a6-11e6-8da4-caec5c3d4a7c.jpg)

Other suggestions or improvements?

**Comment by ramezrafla** [comment]
I really like the second one - modern, even font looks great! (Don't recognize it, which font is that ... We could use it for website headers / heroes too)

Well done!

**Comment by laosb** [comment]
Second one +1

**Comment by brown2rl** [comment]
2nd

Sent from my Windows Phone
________________________________

**Comment by aadamsx** [comment]
@alexandesigner is really talented.  I like the second one.  Any chance I can get you to do one of these for my product/brand?

**Comment by kulttuuri** [comment]
I like the font most on the second one, modern sans-serif font fits the best. Having "A" letter missing a crossbar also makes it looks even more modern! :)

As for the design, I like that second one looks modern and clean but also even more the playfulness created by first and third options. However I don't love the first and third options yet as second one is visually more pleasing as of it's symmetry, but I think first and third could be improved to gain that too.

Really depends on which way the brand wants to be seen. I liked the playfulness aspect of the first and third one as playfulness can be seen somewhat experimental, maybe sometimes child-like (easy to use) and not something too corporate feeling. Just my two cents. :)

**Comment by MiroHibler** [comment]
The second one, of course! :)

My comment in the [repo](https://github.com/alexandesigner/blazejs/issues/2) ;)

**Comment by alexandesigner** [comment]
> Any chance I can get you to do one of these for my product/brand?

@aadamsx Thanks a lot man, I'm sorry for the delay ... Put me forwards an email with the exact requirements you need ... alexandesigner@gmail.com

> My comment in the repo ;)

@MiroHibler I've made the changes you proposed, we need to wait for now the MDG's position with respect to this and other things pertaining to the blaze.

**Comment by aadamsx** [comment]
@alexandesigner I responded via email.  Thanks.

**Comment by MiroHibler** [comment]
@alexandesigner, great! Where can I see the latest version?

And yes, we're all eagerly waiting for MDG... ;)

**Comment by alexandesigner** [comment]
Of course.. follow the final version of the proposal

![idvisual-blaze](https://cloud.githubusercontent.com/assets/3044907/18089569/f4af600e-6e96-11e6-9716-79a3930ee2c0.png)

...and below the link to the dropbox (open version):

https://www.dropbox.com/s/07a5l3p9epyuqbw/logoblaze.svg?dl=0

**Comment by MiroHibler** [comment]
Great work! 💯

**Comment by theodorDiaconu** [comment]
love it.

**Comment by maxenceC** [comment]
Great job @alexandesigner, I love It !

**Comment by laosb** [comment]
Love it!

**Comment by stubailo** [comment]
Incredible!

**Comment by mitar** [comment]
Really really cool.

Cold you create please a pull request to this repository and simply add those files? Some top-level directory?

**Comment by ramezrafla** [comment]
Super!
From a branding perspective, don't we want to mention 'handlebars for Meteor' somewhere? If we want the project to continue, we need newcomers to understand what it is and lower barrier to adoption.
e.g. (no artistic intent :smile: -- just a quick idea)

![handlebars-meteor](https://cloud.githubusercontent.com/assets/1903864/18099181/5c970c1e-6eb3-11e6-881a-9c2b2fed4c08.png)

**Comment by stubailo** [comment]
> don't we want to mention 'handlebars for Meteor' somewhere?

Honestly I'm not sure if handlebars is a selling point at all - I personally wouldn't put it in the logo, but i'd maybe put it on the front page of the website, something like "A simple templating library based on Handlebars, built for reactive apps"

**Comment by ramezrafla** [comment]
Understood - should have put my artistic skills somewhere else ;)

Agreed that it's better on web page

**Comment by mitar** [comment]
@alexandesigner, would you be interested in creating a simple landing page (static HTML is good) for Blaze as well? You can add it to `gh-pages` branch. See #24 for discussion.

**Comment by alexandesigner** [comment]
@mitar 

> Cold you create please a pull request to this repository and simply add those files? Some top-level directory?

Okay, I'm going to do ``/images`` 

> would you be interested in creating a simple landing page (static HTML is good) for Blaze as well? You can add it to gh-pages branch. See #24 for discussion.

I will think of something to landing page based on the suggestions of the people, I'm comfortable with the use of gh-pages initially :D

**Comment by mitar** [comment]
@kdanninger volunteered to help with the landing page as well. Feel free to coordinate together (you can also use our Slack organization to find each other).

**Comment by mitar** [comment]
Done with #63.

**Comment by lednhatkhanh** [comment]
This logo's super cool!

**Comment by alawi** [comment]
Very nice logo 👍

**Comment by parhelium** [comment]
good job !

**Comment by steven-tib** [comment]
Very nice logo! 
(I've just sent you an e-mail with some questions about it)
