### ISSUE TITLE
Deploy documentation on HTTPS

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#311]
https://blazejs.org/ does currently not work.

**Comment by jankapunkt** [comment]
Related #336

**Comment by fredmaiaarantes** [comment]
I will work on this issue this week, I believe that using Netlify as the Meteor Docs and Guide we can manage the SSL certificate using the built-in Let's Encrypt integration.

**Comment by fredmaiaarantes** [comment]
It's done: [https://blazejs.org](https://www.blazejs.org).

<img width="1020" alt="Screenshot 2022-04-08 at 21 27 40" src="https://user-images.githubusercontent.com/559305/162549156-2e2864d6-5ea6-4bc1-bcf9-e0ddeb803164.png">
