### ISSUE TITLE
CI broken?

### ISSUE THREAD

**Issue by jankapunkt** [meteor/blaze#316]
All PRs are failing and there are multiple issues in each with CIRCLE CI. @filipenevola do you have access to the circle ci pipelines?

**Comment by filipenevola** [comment]
Hi @jankapunkt , yes, I already looked into this a few weeks ago.

I believe we need to rewrite the CI file as it was designed for CircleCI 1.0 and it's not supported anymore.

Do you need additional access to work on this?

**Comment by jankapunkt** [comment]
@filipenevola thanks a lot for the fast response. For now I am fine with local tests, I have set up a quite stable test environment, I also added a PR for it, see #317

**Comment by filipenevola** [comment]
This was fixed here https://github.com/meteor/blaze/pull/320
