### ISSUE TITLE
Think about a governance 

### ISSUE THREAD

**Issue by laosb** [meteor/blaze#32]
Here're my little cents on community organization: ourmeteor/discussions#1

In that way we could form a community organization to work with MDG in a completely transparent way.

**Comment by mitar** [comment]
I would for now keep the governance in this repository. We can use issues to have discussions, and upvoting and downvoting to make decisions. I am closing this issue with this in mind. We can reopen it if we see that our community has grown so much that we should improve on our governance processes.
