### ISSUE TITLE
observe_sequence should be moved to Blaze

### ISSUE THREAD

**Issue by brucejo75** [meteor/blaze#322]
Reopening #221 

The Meteor [observe_sequence](https://github.com/meteor/meteor/tree/devel/packages/observe-sequence) package is only used by Blaze.  It is not used by Meteor.

This package should be moved to [Blaze Packages](https://github.com/meteor/blaze/tree/master/packages).

**Comment by filipenevola** [comment]
Hi @brucejo75 good catch.

Could you create a PR with this move?

**Comment by brucejo75** [comment]
@filipenevola, sure thing.

Moving a package is new to me... I assume this is 2 PRs?

**Issue:** Removing the package from Meteor will break compatibility with Blaze (all future versions of Meteor will only work with versions of Blaze that have the package integrated in.)


### Option 1
1. Add the package to Blaze.  Release Blaze **vNew**.
2. After Blaze releases with the package integrated remove the package from next version Meteor.  And document that only Blaze **vNew** will only work with the latest Meteor.  (breaks backward compat).

### Option 2
1. Add the package to Blaze.  Release Blaze **vNew**.
2. Leave the package in Meteor.  Document that Meteor will be losing backward compatibility with older versions of Blaze in the future. (Is there a way to add this info to the `package.js` so the user is notified of the upcoming incompatibility?)
3. After 6 months? Remove the package from Meteor.  Now all new users will need to upgrade to the latest Blaze.

I could see either way?  Your thoughts?

**Comment by filipenevola** [comment]
I would think we just need to move the code.

The package name and versions could stay the same, no?

**Comment by brucejo75** [comment]
Yes, I will simply move the package.

You might not understand the quandary:
- Current version of Blaze is **2.4**.
- Say I add the observe_sequence package to Blaze and it gets into **v2.5**.
- And I remove the observe_sequence package from Meteor **v2.3**.

At that point Meteor only works for **v2.5** of Blaze, because older versions of Blaze do not have observe_sequence as part of the package.

Anyone upgrading to Meteor **v2.3** will be required to upgrade to Blaze **v2.5** and any of its dependent packages.  That is my option 1.  Essentially, Meteor does not backwardly support any versions of Blaze prior to **v2.5**.

But this can be kind of harsh to those upgrading Meteor without any forewarning.  So maybe it is worthwhile have the package in both places for some overlap.  And the [History ](https://github.com/meteor/meteor/blob/devel/History.md)comments can include the warning that soon older versions of Blaze will not be compatible.  I don't know if packages can flag that they are about to become obsolete.

Is there a way to install observe_sequence standalone?  [Observe_sequence](https://atmospherejs.com/?q=observe_sequence) is not in atmospherejs.com.  That could solve it for all scenarios...

**Comment by brucejo75** [comment]
Oops!  I take that back.  observe-sequence is in atmospherejs.com, not observe_sequence.

Maybe my concerns are not valid because the package is in atmospherejs.  I assume that removing the package from Meteor will not remove old versions from atmospherejs.

**Comment by brucejo75** [comment]
I will spin up the PR sometime in the next couple of days...

**Comment by filipenevola** [comment]
Yes, exactly, core packages are basically the same as any other packages.

The main difference is that we tie their versions with Meteor versions, except patches.

**Comment by jankapunkt** [comment]
I think the `observe_sequence` is moved, right? Can this be closed?

**Comment by StorytellerCZ** [comment]
Yes
