### ISSUE TITLE
2.4.0 Removed SpacebarsCompiler and other exports

### ISSUE THREAD

**Issue by zodern** [meteor/blaze#327]
https://forums.meteor.com/t/spacebarscompiler-is-undefined/55685

A couple other exports removed were `BlazeTools` and `HTMLTools`. Since this wasn't a major update, these should probably be added back for now to avoid breaking changes.

**Comment by filipenevola** [comment]
Hi, this is fixed.

See the new versions here https://github.com/meteor/blaze/pull/328#issuecomment-821703330

Sorry for the trouble :wink:
