### ISSUE TITLE
Blaze website fails to reflect the latest changes in History.md

### ISSUE THREAD

**Issue by harryadel** [meteor/blaze#336]
The 2.4 release isn't mentioned in the [website](http://blazejs.org/changelog.html)
https://github.com/meteor/blaze/blob/master/HISTORY.md#v240-2021-april-12

![Screenshot_2021-05-15_00-43-46](https://user-images.githubusercontent.com/6644545/118338510-a1006e00-b516-11eb-9548-9844033abfba.png)

**Comment by jankapunkt** [comment]
@StorytellerCZ  @filipenevola  who can actually update the website? It also seems to still have no valid TLS ?

**Comment by StorytellerCZ** [comment]
:thinking: looks like it needs to be done manually. @filipenevola do you know? I'm working on automatic deploy for hexo sites in the main repo so once I get it working there I'll make it work here as well.

**Comment by jankapunkt** [comment]
Can we use GitHub actions to auto-deploy the site? They support a great secrets management so MS can manage the secrets and restrict the page deploy to releases only. @fredmaiaarantes what do you think?

**Comment by jankapunkt** [comment]
Alternatively we can also deploy the docs on GitHub pages and make `blazejs.org` simply link to the GitHub pages

**Comment by fredmaiaarantes** [comment]
I just updated it from a local build. I'll create a PR this week to fix this issue.

**Comment by fredmaiaarantes** [comment]
It's done: [https://blazejs.org/changelog](https://www.blazejs.org/changelog.html).

This was the [commit](https://github.com/meteor/blaze/commit/e2babd76670be9bdb6ab1843c6441d5299a1e283) to solve it and now it is deployed to Netlify as the others Meteor docs. From now, it should trigger a new deployment when a change into the docs is pushed to master.
