### ISSUE TITLE
Trace {{#each}} errors

### ISSUE THREAD

**Issue by antoinep92** [meteor/blaze#338]
Reopen/duplicate https://github.com/meteor/blaze/issues/184 and https://github.com/meteor/meteor/issues/3312

Basically it's very hard to debug this error:
> Error: {{#each}} currently only accepts arrays, cursors or falsey values.

Is suspect other error messages may be affected as well.

Ideally the error should trace an html file + line location of the problematic #each. But I gathered from other issues this is not something that is easily done in the current architecture. So I suggest we log the value that is being passed to #each, which is not as helpful but can help narrow it down, and I guess it should be a lot easier to implement since the values passed to #each should be in context when this error arise.

**Comment by jankapunkt** [comment]
Co-related #339

**Comment by antoinep92** [comment]
> Co-related #339

Both issues are somewhat related in the sense that they relate to #each, but they are really not the same request I think.
#338 is about better error handling/reporting when passing something #each doesn't support
#339 is about supporting a wider range of data types

**Comment by jankapunkt** [comment]
You are correct. I just wanted to link them since they may be handled in one PR because it's the same place in the Code to be updated.

**Comment by StorytellerCZ** [comment]
I think these two issues should be the main focus of Blaze 2.6.
