### ISSUE TITLE
Blaze repo issues

### ISSUE THREAD

**Issue by brucejo75** [meteor/blaze#340]
@filipenevola, @StorytellerCZ,
I am having a hard time finding the releases for **v2.4** & **v2.5**.

Maybe I am looking for the wrong thing?  Has the repo moved?

1. Atmosphere has versions **2.4** & **2.5** of [Blaze](https://atmospherejs.com/meteor/blaze).
2. The history file has references to versions [**2.4**](https://github.com/meteor/blaze/blob/master/HISTORY.md#v240-2021-april-12) & [**2.5**](https://github.com/meteor/blaze/blob/master/HISTORY.md#v250-2021-june-5).
3. The [releases](https://github.com/meteor/blaze/releases) only go up to **v2.3.4**.
3. I cannot find tags or branches for **v2.4** or **v2.5**.

[Release 2.4 PR](https://github.com/meteor/blaze/pull/323/commits)
- I assume this is the published commit? [`80fbd1d`](https://github.com/meteor/blaze/pull/323/commits/80fbd1da3624332855114bc41d930dfc4771c4f0)

Release 2.5 has no PR...
- Was this [PR](https://github.com/meteor/blaze/pull/331) the one that was published?
- Is this the commit that was published? [`75fd80d`](https://github.com/meteor/blaze/pull/331/commits/75fd80dfead92cd6f4f29fe548e6d92cdacb89c1)

I have a fork that I need to keep up to date for my project.

Thanks!

**Comment by filipenevola** [comment]
Hi @brucejo75 I believe the tags were not created but @StorytellerCZ can fix this soon.

Out of curiosity, what are the changes that are you keeping in your fork? Wouldn't they be useful to the community?

**Comment by brucejo75** [comment]
Hi @filipenevola,

OK, great.  Thought I might have missed something.  Having the tags will be useful for me.

I have been running 2 versions of blaze in my app.  One that I use directly (essentially "as-is").

In the other one I do things like prepending the template name with a custom string and the variable lookup is extended to look in my dictionaries.  I think this is really stuff that is custom for my application.

Otherwise I would definitely proposing pulling into Meteor.

**Comment by StorytellerCZ** [comment]
Added tags, now adding the releases...

**Comment by StorytellerCZ** [comment]
Should be done now, but release 2.5 had no PR as it was not necessary due to the changes.

**Comment by brucejo75** [comment]
Great!  Thanks!
