### ISSUE TITLE
unable to integrate webscoket

### ISSUE THREAD

**Issue by Merrick17** [meteor/blaze#345]
I'm trying to integrate websocket using pusher but each time i get a connection timeout

**Comment by StorytellerCZ** [comment]
Hi @Merrick17 could you give us more details? This is very little to go on.

**Comment by filipenevola** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.

**Comment by Merrick17** [comment]
hey sorry didn't saw this actually yes i found  a solution , the websocket using pusher was closing alone , so i forced it to reopen
