### ISSUE TITLE
observe-sequence@1.0.18 syntax broken on IE 11

### ISSUE THREAD

**Issue by dougfabris** [meteor/blaze#347]
Recently we updated the meteor version e we realize the `observe-sequence@1.0.18` is broken on Internet Explorer 11

We believe is something related to the syntax, not supported, present here: https://github.com/meteor/blaze/blob/master/packages/observe-sequence/observe_sequence.js#L170

As a workaround, we are doing a downgrade to the `v1.0.16`: https://github.com/RocketChat/Rocket.Chat/pull/22557
We hope you guys can have a fix for that soon, thanks!

**Comment by StorytellerCZ** [comment]
Confirmed, `for-of` loop is not compatible with IE at all. I'll get a fix out today.

**Comment by StorytellerCZ** [comment]
ping @antoinep92 who implemented this originally.

**Comment by antoinep92** [comment]
Sorry about that. I'll submit a fix tomorrow

**Comment by antoinep92** [comment]
Hum ok I saw your fix. Indeed it should work in IE, but breaks my code for non-array iterables. I thought about using `Array.from` but that's [not supported either](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#browser_compatibility).
Is there some kind of library you use that provides a polyfill or equivalent to `Array.from`, or should I implement it "by hand" ? :thinking:

**Comment by antoinep92** [comment]
After giving this some more thought: I can use `Array.from` safely, since it won't trigger a parse error in IE 11 (as `for .. in` did) and iterables aren't supported on IE either, so the branch with `Array.from` will be unreachable in IE. I'll submit a PR shortly.
