### ISSUE TITLE
small issue with parsing html comments inside Blaze templates

### ISSUE THREAD

**Issue by TheRealByteraver** [meteor/blaze#362]
Disclaimer: total beginner writing here.
I noticed that an html comment like this:
`<!-- -- -->`
crashes modules-runtime-hot.js. The following works fine:
`<!-- - -->`
`<!-- -========- -->`
I am running Meteor 2.5.6. Apologies if this was mentioned before; I did a quick search but could not directly find a reference to it.
Thank you for your work, Meteor is amazing <3

**Comment by jankapunkt** [comment]
If you don't need the comments to be added to the output you can rather use the Blaze comments:

```
{{!-- =========== whateever ======== --}}
```

They are multiline, work with `=` and they will get stripped by the compiler from the final HTML output.

**Comment by TheRealByteraver** [comment]
Thanks! Didn't know that Blaze comments are stripped from the final html, good to know.

**Comment by jankapunkt** [comment]
@TheRealByteraver please close if your issue is resolved. Feel free to reopen if the issue persists or reoccurs.
