### ISSUE TITLE
Add ts types

### ISSUE THREAD

**Issue by jankapunkt** [meteor/blaze#388]
Since we can now support to make types available with `zodern:types` we should try to add this for 2.6.2 already. Any thoughts/comments in this?

**Comment by StorytellerCZ** [comment]
I think that makes sense.

**Comment by jankapunkt** [comment]
@Grubba27 do you think this might be a low-hanging fruit? I am personally not that much deep into typescript to be confident enough to provide a PR yet but I would be willing to try if you could support with a review or something like that
