### ISSUE TITLE
{{elsif}} or {{elseif}} or {{#elseif}}

### ISSUE THREAD

**Issue by ramezrafla** [meteor/blaze#39]
I am suggesting we add an {{elsif}} or {{elseif}} or whatever variation to avoid this ugly piece of code:

```
{{#if condition1}}
{{else}}
  {{#if condition2}}
  {{else}}
     {{#if condition3}}
     {{/if}}
  {{/if}}
{{/if}}
```

Imagine this instead

```
{{#if condition1}}
{{elseif condition2}}
{{elseif condition3}}
{{/if}}
```

I also think this will go a long way in making people more likely to adopt Blaze as it cleans up the code quite a bit for complex apps.

**Comment by mitar** [comment]
Does handlebars have it?

**Comment by mitar** [comment]
The issue is that this might seem a simple addition but would require a lot of changes internally. Like, a lot.

**Comment by ramezrafla** [comment]
Handlebars does not seem to have it.
I was thinking .. a preprocessor would do the trick :)

**Comment by mitar** [comment]
Hmmm. Maybe. So at the level or parser. Like a syntactic sugar. This could work. You could look into spacebars parser if you feel adventurous. :-)

**Comment by ramezrafla** [comment]
Got it :) -- will start digging into it. Is the parser part of this repo or somewhere else?

**Comment by mitar** [comment]
https://github.com/meteor/blaze/tree/master/packages/spacebars-compiler

**Comment by AdrienTorris** [comment]
totally agreed with this issue. Simple if/else if/else is just so usefull

**Comment by nathantreid** [comment]
I've been wanting this everytime I write an ugly if else if else chain, and today it caught my interest, so I've implemented a version using {{elseif}} (example taken from original post):
``` handlebars
{{#if condition1}}
{{elseif condition2}}
{{elseif condition3}}
{{/if}}
```
As suggested, it is simply sugar syntax. The above example is transformed into the compiled spacebars version of this:
``` handlebars
{{#if condition1}}
{{else}}
  {{#if condition2}}
  {{else}}
     {{#if condition3}}
     {{/if}}
  {{/if}}
{{/if}}
```

**Comment by ramezrafla** [comment]
Excellent @nathantreid,
Can you PR with your changes?

**Comment by nathantreid** [comment]
@ramezrafla Check out the PR link above my previous post. :smile:

**Comment by ramezrafla** [comment]
Oops - sorry - I'll blame it on small iPhone screen :) thanks a lot!

**Comment by capensisma** [comment]
When is this coming out? coming soon this summer 2017?

**Comment by nathantreid** [comment]
@capensisma: Quoting Mitar (from my pull request):
> Waiting for #20 and that we release first community Blaze version. I would like that one to be without extra features, just bugfixes. And then we can start adding features.

**Comment by ramezrafla** [comment]
Is there anything gating this? @mitar, want me to run some tests first?

**Comment by mitar** [comment]
See the pull request #50. I would like that this is implemented compatible with Handlebars which allows any block helper to be used. So you can do:

```
{{#tab title="Foo"}}

{{else tab title="Bar"}}

{{else tab title="Baz"}}

{{/tab}}
```

Feel free to make a pull request like that. With tests and documentation. That would be great!

**Comment by ramezrafla** [comment]
Thanks @mitar, we can certainly adopt this syntax, but we can also add the other syntax above. The two can be exclusive. Blaze has evolved quite a bit from Handlebars syntax. I personally like have elseif's -- it's more natural and less convoluted and would add value to developers.

**Comment by mitar** [comment]
With 2fa3cabcf446a1db571fd63aabea60b974d2c1a0 I implemented the Handlebars syntax for chaining block tags. After further consideration I did not implement `{{elseif}}` as well because it opens a small backwards incompatibility (somebody could have a template helper named `elseif`). Let's try the `{{else if}}` syntax and see how it will work. I started to like it, especially because you can use it with custom block tags.

**Comment by mitar** [comment]
Released as 2.3.0. You have to update templating package.

**Comment by namirsab** [comment]
@mitar and the rest, first of all, thanks a lot for keeping blaze alive. 

 I'm writing here even if it's closed just to point one thing.
It was difficult to me to know which packages i had to update. `meteor test` was not passing even if it had the correct blaze version and it was because templating was not up to date.

Is it written anywhere which packages are needed to be updated?

Again, thanks a lot!

**Comment by mitar** [comment]
`meteor update` should update all? So all packages in this repository.

**Comment by namirsab** [comment]
but meteor update also updates the meteor tool and so on. What if i just want to update blaze?

**Comment by maxfi** [comment]
> Released as 2.3.0. You have to update templating package.

Is this mentioned somewhere in the docs? I couldn't find anything. Thanks.

**Comment by mitar** [comment]
It is documented here: http://blazejs.org/guide/spacebars.html#Chaining-of-Block-Helpers

**Comment by maxfi** [comment]
Thanks @mitar. I expected there to be a mention here: http://blazejs.org/guide/spacebars.html#If-Unless

**Comment by mitar** [comment]
Feel free to make a pull request. :-)

**Comment by wei170** [comment]
My blaze version is on 2.3.2. But I still cannot use
`{{#if foo}}
{{else if boo}}
{{else}}
{{/if}}`

**Comment by mitar** [comment]
Which version of `spacebars-compiler` package you have?

**Comment by wei170** [comment]
My `spacebars-compiler` is @1.1.2

**Comment by mitar** [comment]
Then please create a small reproduction (a repo showcasing ony this issue).

**Comment by wei170** [comment]
`   
 {{#if isUserProfile}}
        <h3>User Profile</h3>
    {{else if isLawyerProfile}}
        <h3>Lawyer Profile</h3>
    {{else}}
        <h3>Test</h3>
    {{/if}}
`

Error:

`
Errors prevented startup:

While processing files with templating-compiler (for target web.browser): client/profile/Profile.html:8: Expected `}}`
...ofile</h3>     {{else if isLawyerProfile}...
`

**Comment by mitar** [comment]
This is not a reproduction. Please create a small Meteor app in a git repo and provide a link to it here. Because the only thing I can tell you based on your snippet above is: it works for me.

**Comment by wei170** [comment]
Oh, I figured out. It was caused by templating-compiler version. I was on @1.2.15. When I updated it to @1.3.2, it works.

**Comment by Roshdy** [comment]
Can you please add this fix to the [documentation](http://blazejs.org/guide/spacebars.html#If-Unless) of blaze
