### ISSUE TITLE
Don't pass an empty {hash:{}} as the last arg to a template helper

### ISSUE THREAD

**Issue by lorensr** [meteor/blaze#40]
Moved from https://github.com/meteor/meteor/issues/5031

**Comment by mitar** [comment]
This would potentially be backwards incompatible. But yes, this is really unneeded. Also, I think it is unneeded that data is stored inside `hash` ant not directly inside `Spacebars.kw` object.

**Comment by stubailo** [comment]
Would it make sense to simplify helpers to use either only positional or only keyword args? So either:

```
{{helper x y}}
```

Or

```
{{helper x=x y=y}}
```

The second seems more desirable as a single option, since with positional arguments you need to constantly be looking up the order, etc. Unfortunately all current code uses the first.

**Comment by mitar** [comment]
The question for me is just why we have `hash` property for data, why it is not simply an object which is an instance of something (`Spacebars.kw`) and this is it?

**Comment by stubailo** [comment]
No reason I can imagine at all. We should 100% get rid of it.

**Comment by MiroHibler** [comment]
> Would it make sense to simplify helpers to use either only positional or only keyword args? So either:

> `{{helper x y}}`

> Or

> `{{helper x=x y=y}}`

> The second seems more desirable as a single option, since with positional arguments you need to constantly be looking up the order, etc. Unfortunately all current code uses the first.

I'd do both for backward compatibility, get rid of `hash` and make the same for inclusion tags (`{{> foo x y=y}}`) and block tags (`{{#foo x y=y}}`).

**Comment by stubailo** [comment]
I agree that helper and inclusion syntax should be consistent!

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
