### ISSUE TITLE
Improve spacebars string data context

### ISSUE THREAD

**Issue by lorensr** [meteor/blaze#42]
Migrated from https://github.com/meteor/meteor/issues/4259

When you do `{{> foo uid}}`, where `uid` is `"FuFa6muAquumzfLMC"`, and you're inside a `foo` event, `this` is not a string, but rather an object representation of a string.

```
> console.log this, typeof this, Meteor.users.findOne this
String {0: "F", 1: "u", 2: "F", 3: "a", 4: "6", 5: "m", 6: "u", 7: "A", 8: "q", 9: "u", 10: "u", 11: "m", 12: "z", 13: "f", 14: "L", 15: "M", 16: "C", length: 17, [[PrimitiveValue]]: "FuFa6muAquumzfLMC"}
object
Uncaught TypeError: key.substr is not a function
```
1. It would be nice if `this` was a real string, but I don't think that's possible in JS.
2. If not 1, then it would be nice for Meteor functions that take strings, like `findOne`, to convert these spacebars object strings into real strings instead of throwing errors.

**Comment by mitar** [comment]
I think we should discourage use of `this` at all. We should make sure that `Blaze.currentData()` returns a normal string object.

**Comment by lorensr** [comment]
If it's bad to use this, perhaps we could change this to be what's good to
use? It's nice in its simplicity of accessing

**Comment by mitar** [comment]
I think in Blaze 1 we should discourage its use, and in Blaze 2 it should be template instance.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
