### ISSUE TITLE
Add Template.registerHelpers(object)

### ISSUE THREAD

**Issue by lorensr** [meteor/blaze#43]
Migrated from https://github.com/meteor/meteor/issues/4367

This is now a feature of https://github.com/aldeed/meteor-template-extension 
We could consider including the whole package

---

There are two patterns I use a few places in my app that would be improved by this:
1. registering multiple helpers at once
2. registering helpers that are also called from app JS
Before:

``` coffeescript
helpers = 
  foo: ->
    0
  bar: ->
    1
for name, fn of helpers
  Template.registerHelper name, fn
```

After:

``` coffeescript
Template.registerHelpers
  foo: ->
    0
  bar: ->
    1
```

Before:

``` coffeescript
foo = ->
  0
bar = ->
  1

Template.registerHelper 'foo', foo
Template.registerHelper 'bar', bar
```

After:

``` coffeescript
foo = ->
  0
bar = ->
  1

Template.registerHelpers {foo, bar}
```

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
