### ISSUE TITLE
Redefine `this`

### ISSUE THREAD

**Issue by lorensr** [meteor/blaze#46]
Make it the template instance? 

Migrated from https://github.com/meteor/meteor/issues/3579 

For Blaze 2 milestone

**Comment by zimme** [comment]
While we're att it, maybe make `this` and the first argument of the callback being the same.
This will make it possible to use arrow functions for the callback functions of `onRendered` etc.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
