### ISSUE TITLE
Async Helpers are not reactive after the first "await"

### ISSUE THREAD

**Issue by vincentcarpentier** [meteor/blaze#461]
See link: https://docs.meteor.com/api/tracker.html#Tracker-autorun-and-async-callbacks

Tracker.autorun and async callbacks works with "Tracker.withComputation" and "computation" argument trick.
But quid about async helpers that contains multiple awaited promises ?
After the first "await" all reactive vars are no more reactives
To be ISO with autoruns, Blaze helpers should be able to use "computation" variable and "Tracker.withComputation" like in autoruns.

**Comment by radekmie** [comment]
You can get the computation from [`Tracker.currentComputation`](https://docs.meteor.com/api/tracker.html#Tracker-currentComputation) before the first `await` and use `Tracker.withComputation` just as in the documentation.
