### ISSUE TITLE
We need global template hooks

### ISSUE THREAD

**Issue by talha-asad** [meteor/blaze#49]
We need a global onRendered hookable function, the same goes for onCreated, onDestroyed, etc. Agreed?

**Comment by crapthings** [comment]
check this @talha-asad 

https://github.com/aldeed/meteor-template-extension/#templateoncreated--templateonrendered--templateondestroyed

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
