### ISSUE TITLE
Spacebars: Objects/arrays as arguments

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#5]
(From https://github.com/meteor/meteor/issues/5095 .)

I really think Blaze should allow the following syntax:

```
{{foo (a=1 b=2)}}
{{foo (1 2)}}
```

So in the first case it just creates in-place object. In the second case it finds that `1` is not a function, so it returns an array `[1, 2]`. `{{foo (1 2 a=1)}}` would return `[1, 2, Spacebars.kw({a: 1})]`.

Alternatively, we could introduce `{{foo [1 2])}}`.

**Comment by nathantreid** [comment]
Given your first syntax, would `{{foo ((a=1) (b=2))}}` become `[Spacebars.kw({a: 1}), Spacebars.kw({b: 1})]`?
I'm thinking that might be more readable in the square brackets format: `{{foo [(a=1) (b=2)]}}`.
Perhaps objects could instead use the single curly brace:  `{{foo {a=1 b=2}}}`.
That's especially helpful if you have subexpressions: `{{foo (bar [1 2] {a=1 b=2}) }}`, and of course the square brackets and curly brackets are easily readable by anyone familiar with JavaScript, so it makes adoption easier.

**Comment by mitar** [comment]
I think we could go with `{{foo (a=1 b=2)}}` and `{{foo [1 2]}}`

**Comment by stubailo** [comment]
Yeah I think using square brackets for arrays is the only reasonable option.

**Comment by mitar** [comment]
And they are already also used for escaping, so they already have a special meaning.

**Comment by tcastelli** [comment]
Just copying my insights from #75 

> If I could choose, maybe something less confusing than ( would be fine, since "( " is already used for (sub)expressions and mixing both things could be troublesome:

> {{> tmp1 param1="hi" param2=(helper (a=8 b=3) (ahelper (b="pa")) ) }}
I had to write it 3 times for having so many "(" :hankey: 


This could work with a simple JSON.parse, but it's true that maybe it's too verbose
`eg: {{> tmp1 param1="hi" param2='{"a":8, "b":3}' }}`

**Comment by mitar** [comment]
I prefer sticking to `()` and `[]` because those are already symbols parsed inside helpers. `{` and `}` could get confusing with outside `{{` and `}}`.

**Comment by mitar** [comment]
I also do not think you should overuse those features. I think this is mostly to be used for one-level objects. If you want something more complicated you should probably move it to code anyway.

**Comment by tcastelli** [comment]
`[] ` for arrays looks totally okay to me. For objects I think `{ }` all alone can be confusing (like "( )") so what about using more or less what you said and forget about `()`
{{foo [a=1 b=2]}}  => {a:1, b:2}
{{foo [1 2]}} => [1,2]

**Comment by mitar** [comment]
I do not thing this is good. Because you cannot define an empty object and empty array your way.

```
{{foo ()}}
{{foo []}}
```

I agree it is not the best, but I think it is the best from all other options I have seen.

**Comment by tcastelli** [comment]
Good point, what about ?
````
{{foo [=]}}  => {}
{{foo []}} => []
`````

**Comment by mitar** [comment]
You really do not like parenthesis, do you? :-)

Let's leave this discussion for a bit, to see what people will vote on.

**Comment by tcastelli** [comment]
Hahaha, to be honest I picture myself getting crazy matching parenthesis, so if we can avoid that I think code is less prone to errors and easier for the parser too. Like I said, if anyway we have to introduce [ ] we can suggest another symbol for objects like ``| a=1 b=2 |` or '/ a=1 b=2/' ` , but you are right, let's see what other people think about it :)

**Comment by mitar** [comment]
I think that if you get to the stage that you have issues with parenthesis you are having too much logic in templates and you should move them out. Simple as that.

**Comment by mitar** [comment]
So this feature is so that you do not need to make helpers just to combine two variables together into an object. But not really to make nested expressions.

**Comment by tcastelli** [comment]
Yes, I get it, and yes I was pushing it with my example (though I have used some long helpers with parenthesis ocasionally). I just feel than reusing the same symbol for different purposes when are about to introduce a new syntax for arrays it's a little against the "logic".

But well, if you confess your secret love for parenthesis I might let it go :heart:

**Comment by fafournier** [comment]
I was just looking for such a way to build objects and arrays. What I found so far is that making 2 global helpers seems to do the job:

```
Template.registerHelper("makeObject", function(){
  const args = arguments;
  return args && args.length && args.length > 0 && args[arguments.length-1] && args[args.length-1].hash || {}; //hash
});
```

```
Template.registerHelper("makeArray", function(...args){
  return args || [];
});
```

They can be used such as:
`{{otherFunction (makeObject atype="OBJECT" source=1 type="good" value=123 inline=true editable=false)}}`
`{{otherFunction (makeArray 1 2 3 4 5 6 true false "array item" null)}} `

Would it be enough to document this or just to include the helpers or does it make a real difference to create a new syntax?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
