### ISSUE TITLE
Slack join page not working

### ISSUE THREAD

**Issue by atom-azimov** [meteor/blaze#51]
![16 20 51__838x243__heroku nosuchapp-googlechrome](https://cloud.githubusercontent.com/assets/9398439/17276214/8fa51bd0-573b-11e6-845b-753e6fe30004.png)

**Comment by grsabreu** [comment]
Yeah, not working at all :/

**Comment by MiroHibler** [comment]
Hey, @voidale, can you take a look?

**Comment by alexandesigner** [comment]
Somehow the slack spent working on different subdomains... I made a change in the readme or if you would like to be able to ignore and do who have access to the master.

**Comment by mitar** [comment]
Can we find somewhere else to host it? Is this still the simplest way to host a Blaze invite? A Heroku container?

**Comment by stubailo** [comment]
Based on my findings, that's the easiest way - hosting slackin on DO or Heroku

**Comment by mitar** [comment]
And probably for such simple app it should be free to host it on Heroku? So why is it down? @MiroHibler, who has it over? Could more people get access to the domain and the website? I have a bad feeling if only one person has access to all this.

**Comment by mitar** [comment]
Also, who pays for domain?

**Comment by voidale** [comment]
@mitar, @MiroHibler hey guys who of you want to host it? got namecheap account? I will transfer the domain, I will not be taking any part in blaze as I switched to react now. I deleted the heroku container by mistake some time ago wasn't sure anybody is using it sorry.

**Comment by MiroHibler** [comment]
Ok, guys, we're covered - @voidale was very kind to transfer the `blazejs.com` domain to me, and I also acquired `blazejs.org` which seems more appropriate now that Blaze has been transferred to community.

I've also set up Heroku app, so we only need to wait for DNS to propagate (I also redirected `blazejs.com` -> `blazejs.org`).

I'm open to any suggestion on how to proceed from now on :)

**Comment by mitar** [comment]
Can you update in README links to .org version of it?

Can you make blazejs.org redirect to our GitHub pages?

https://help.github.com/articles/using-a-custom-domain-with-github-pages/

I think you will have to configure `ALIAS` DNS entry because it is a [top-level domain](https://help.github.com/articles/setting-up-an-apex-domain/).

I will configure the .org version for GitHub pages now.

**Comment by mitar** [comment]
Oh, you first have to setup DNS, then I can configure it.

Can you also add me to domain to be able to manage it somehow? Which provider are you using. I can create an account there.

**Comment by MiroHibler** [comment]
It's Namecheap - let me know your username.

**Comment by mitar** [comment]
@MiroHibler: Do you know why http://slack.blazejs.org/badge.svg does not work?

**Comment by MiroHibler** [comment]
I hope all problems with slack invite page have been fixed now.

**Comment by mitar** [comment]
Yea!
