### ISSUE TITLE
[Bug] Blaze: hidden html attribute does not work properly

### ISSUE THREAD

**Issue by gcacars** [meteor/blaze#52]
Blaze dynamic attributes doesn't work properly with attribute **hidden**.

If you use:

    helperName(){
        return {
            checked: false
    }

It works great, removing the checked attribute.
But when you use:

    helperName(){
        return {
            hidden: false
    }

Blaze creates a html with:

    hidden="false"

that occurs in an hidden element.

**Comment by mitar** [comment]
Probably it just has to be added here: https://github.com/meteor/blaze/blob/master/packages/blaze/attrs.js#L296

This could be a simple pull request. Would you like to contribute it?

Also, there are probably some other new HTML5 attributes likes that.

**Comment by mitar** [comment]
A different fix has been implemented in 84c58a6.
