### ISSUE TITLE
A callback event after DOM is updated

### ISSUE THREAD

**Issue by laosb** [meteor/blaze#53]
**Migrated from meteor/meteor#4731**

**_7 Upvotes**_ _please feel free to close this issue if this request is invalid or I neglected an already-existing feature_

We need something better than `onRendered` that is called everytime a DOM is updated.

Given the following code:

```
<template name="FrameItems">
  {{#each frames}}
    <div id="frame-{{_id}}" class="frame-preview-item cyan lighten-5">
      <div class='frame-name'>{{name}}</div>
      <div class="ep"></div>
    </div>
  {{/each}}
</template>
```

and the helper function

```
  Template.FrameItems.helpers({
    frames: function() {
      var trialId = Session.get('trialId');
      return Frames.find({trialId: trialId});
    }
  });
```

DOM is updated every time `frames` helper function is re-run, but `onRendered()` only gets called once when the template was initially constructed. What if you want to update the DOM every time `frames` helper function returns new set of `.frame-preview-item`? On StackOverflow and Google Groups, people have been suggesting to use `Meteor.defer()`. However, since it's basically same as `setTimeout` it's not called exactly when the new frames are inserted (i.e. it's slower than `onRendered` callback). To solve this problem, I used `Blaze.remove` and `Blaze.render` to destroy `FrameItems` and insert them manually (not using `{{> frameItems}}`) every time `frames` is updated, so that I can use the `onRendered` callback.

This seems to be a common use case and I wonder if Meteor yet supports a clean way to deal with this.
These are links to posts asking how to do this:

http://stackoverflow.com/questions/10109788/callback-after-the-dom-was-updated-in-meteor-js
https://groups.google.com/forum/#!topic/meteor-talk/TMf4RLfQK_w
http://stackoverflow.com/questions/17584522/how-to-make-a-meteor-template-helper-re-run-render-after-another-template-has-re
http://stackoverflow.com/questions/31353120/run-a-function-after-dom-is-updated-from-a-helper-function/31353151?noredirect=1#comment50720195_31353151

**Comment by mitar** [comment]
I do not get what exactly is wanted here. Why you would not leave to Blaze to update DOM when needed? Why would you do this manually?

**Comment by laosb** [comment]
For example, we use a formatter to format our content after the DOM update. Or wysiwyg editors need to be re-inited after the content update. (That's not about "is it intended to update editing content", in my case, since the *new article* shares the same template with *edit article*, which means routing between this two pages only cause helper data update instead of template rerender.)

**Comment by laosb** [comment]
I ended with using Tracker to observe data changes and do dom updates by myself. It looks like:

```
this.autorun(() => {
  const post = Posts.findOne(this.getArticleId());
  if (post) {
    removeEditor();
    $('.wygeditor').html(post.content);
    initEditor();
  }
});
```

**Comment by mitar** [comment]
I must say I have never ever needed to do something like that. Maybe I am really confused. :-) What I do here is simply split template into a subtemplate. So something like:

```
{{#with post}}
  {{> editor}}
{{/with}}

editor.onRender(function () {
  # initialize wygeditor editor
});
```

This one recreates editor every time.

But yes, autorun is also a normal thing to do. So instead of trying to hook up to the helper and know when something happens, you simply use the same function inside autorun and do it in parallel. With Blaze Components it is easy, because all helpers are available as methods anyway, so you can just call them from inside of autorun on the component:

```
class Foo extends BlazeComponent {
  onRendered() {
    super.onRendered();
    this.autorun(() => {
      const post = this.post();
      if (post) {
        removeEditor();
        $('.wygeditor').html(post.content);
        initEditor();
      }
    });
  }

  post() {
    return Posts.findOne(this.getArticleId());
  }
}

BTW, I really like [Trix](https://github.com/peer/mind/blob/master/packages/council/base/editor.html) editor, it works great with Blaze.

**Comment by laosb** [comment]
Using an extra template sounds like a not so hacky hack. Let me try on next refactor 👍

**Comment by avalanche1** [comment]
@mitar , Using #each block, for example, I need to animate each arriving element in collection.

**Comment by laosb** [comment]
@avalanche1 You can try `_uihooks`.

**Comment by avalanche1** [comment]
I tried and didn't succeed. they are too hard to implement

**Comment by mitar** [comment]
@avalanche1: You should just use a package. I [like this one](https://atmospherejs.com/percolate/momentum). Or, alternatively, [Blaze Components has also support for them](https://github.com/peerlibrary/meteor-blaze-components#animations).

**Comment by avalanche1** [comment]
Ok, what about doing other tasks, like updating my UI in other ways, when new elements arrive?

**Comment by mitar** [comment]
Which other ways? You use Blaze to update UI. That's the whole point of Blaze. That it renders and updates DOM. If you want to manually update things, then don't use Blaze?

**Comment by avalanche1** [comment]
Well, ok. I'm out of arguments. When I have a reallife example, I'll make sure to write here.

**Comment by mitar** [comment]
OK. :-) Reproductions are best. And yes, maybe this is also the question of collecting common problematic patterns and show "Blaze way" to address them.

**Comment by laosb** [comment]
Common patterns should go into the Guide, I think? For example, WYSIWYG editors?

**Comment by NitroBAY** [comment]
Hello,
As for me I have 
```
                  {{#each worksheet in worksheets}}
                    <option value="{{worksheet._id}}">{{worksheet.title}}</option>
                  {{/each}}
```
I need to call (because of my front-end framework) `$('#worksheet-select').material_select())` after **all** the `<option>` have been populated inside the `<select>` how do I achieve that ?

**Comment by NitroBAY** [comment]
Hello,
I have 
```
{{#each worksheet in worksheets}}
  <option value="{{worksheet._id}}">{{worksheet.title}}</option>
{{/each}}
```
I need to call `$('#worksheet-select').material_select())` after all the <option> have been populated.
I tried unsuccessfully : 
1)
``` 
 this.autorun(() => {
    const data = Worksheets.find();
    if (data) {
      Tracker.afterFlush(() => $('#worksheet-select').material_select());
    }
  });
```
2)
```
Meteor.subscribe('everyWorksheets', { onReady: () => currentData.worksheetsReady.set(true) });
    if (Template.currentData().worksheetsReady.get()) $('#worksheet-select').material_select();
```
My init code is called too early so only 1 or 2 option on multiple options is actually shown in the <select>
I may create another template but ... for one line (an option tag) it's ridiculous.

PS : @laosb what does 7 Upvotes is coming from an neither meteor's issue or this one has 7 upvotes. I see that kind of thing from time to time and I've always wanted to know what was that.

**Comment by NitroBAY** [comment]
So I tried to go with gwendall ui hooks
```
Template.admin.uihooks({
  '.worksheet-item': {
    insert: function(node, next, tpl) {
      console.log('Inserting an item.');
    },
    move: function(node, next, tpl) {
      console.log('Moving an item.');
    },
    remove: function(node, tpl) {
      console.log('Removing an item.');
    }
  }
});`
```
but it doesn't log anything, it doesn't work at all for me.
Last option (barbaric) would be an event listener on `option`.  I don't see other way around.

**Comment by NitroBAY** [comment]
If it can helps anyone I end up with : 
```
  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      if (mutation.addedNodes && mutation.addedNodes.length > 0) {
        mutation.addedNodes.forEach((node) => {
          if ($(node).is('option')) {
            initWorksheetSelect();
          }
        });
      }
    });
  });

  observer.observe($('#worksheet-select')[0], { childList: true });
```

**Comment by mitar** [comment]
What I do is split templates into smaller template, so that the whole `#each` would be in its own template, and then I use `onRendered` on that template to call such post-processing callbacks.

If I have to respond to more changes, I sometimes just have an autorun which depends on all collection, for example:

```javascript
this.autorun((computation) => {
  // Depend on whole collection.
  Worksheets.find().fetch();

  Tracker.afterFlush(() => {
    this.$('#worksheet-select').material_select();
  });
});
```

Notice that you have to run `.fetch()` to really depend on documents in the collection. Just running `.find()` does not help you.

**Comment by NitroBAY** [comment]
Damn it. I didn't know that `fetch()` was required for reacitivty. That changes everything !
Thanks

**Comment by mitar** [comment]
Yes. Without it you just prepare a cursor. Reactivity is also different if you do `fetch` or `count`. With the latter for example it is only invalided when count changes, not when for example some field changes.

**Comment by NitroBAY** [comment]
Extremely interesting, I already taught that it would be cool to have reactivity for fields and another way for reactivity only for counts, I didn't know how to achieve that. Thanks a lot !
