### ISSUE TITLE
[Idea] Add a contribution guide (contributing.md) for blaze

### ISSUE THREAD

**Issue by maxenceC** [meteor/blaze#59]
A contribution guide make it easier to start helping on the project.

There are some points that could need a workflow guide : 
- How to submit bugs (templates)
- How to reproduce a bug & submit reproduction in the repo issues
- In the [Next steps](https://github.com/meteor/blaze/milestone/1), how do you notify contributors that you've started working on a milestone & how do you submit the result for validation

**Comment by mitar** [comment]
Great idea. Could you make a pull request with a version?

I would like that for now we use this repo for everything: bugs, feature requests, pull requests, and so on.

For code style we should probably just direct to Meteor's?

**Comment by maxenceC** [comment]
> Could you make a pull request with a version?

Sure thing ! I'll have a look at how large repo are doig.

>For code style we should probably just direct to Meteor's?

Yes probably

**Comment by mitar** [comment]
@maxenceC: Have you had time to give a shot at it?

**Comment by maxenceC** [comment]
@mitar : Not at all, unfortunately

**Comment by mitar** [comment]
I made the file with a bit of content: https://github.com/meteor/blaze/blob/master/CONTRIBUTING.md

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
