### ISSUE TITLE
Easy way to force no data context in templates

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#6]
(From https://github.com/meteor/meteor/issues/5459 .)

Proposal:

```
{{> fooTemplate ()}}
```

Includes the template with `{}` as a data context.

We should check if `{{> fooTemplate null}}` works.

I would then suggest that we document this in the guide as a recommended way to include templates, if you do not want to pass a data context.

Or, we could do:

```
<template name="foo" nullDefaultDataContext="true">
  ...
</template>
```

So we could provide some arguments to template to tweak the behavior.

Imagine even:

```
<template name="foo" templateInstanceAsThis="true">
  ...
</template>
```

**Comment by nathan-muir** [comment]
Hmm, is there a reason you would define it in the HTML file, why not add a methods to the template object?

eg.
```
Template.foo.defaultDataContext(()=> null)
```
or 
```
Template.foo.configure({
  defaultDataContext(){ return null; },
  helperContext: 'instance'
});

**Comment by mitar** [comment]
Good idea.

**Comment by stubailo** [comment]
It really makes sense to have a single rontime place to configure templates - we can also use this as a transition oth to new features.

**Comment by mitar** [comment]
Closing in favor of #113.
