### ISSUE TITLE
Establish Open Collective for Blaze

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#60]
[Open Collective](http://opencollective.com/) is an interesting new and transparent way to do financing for [open source projects](https://opencollective.com/opensource). We could establish one for Blaze and then use it collectively to cover expenses (like Heroku containers we might need, domain name, maybe even have bounties).

Companies who relay on Blaze could becomes sponsors. It would be great if MDG could become such a sponsor, too.

What others think? I think we should do it because I worry a bit about our infrastructure (domain, Slack invite #51).

**Comment by aadamsx** [comment]
This is a brilliant idea.  This is exactly what Blaze needs.

**Comment by theadactyl** [comment]
Following up on this, I think this is a great idea. We've heard from Open Collective before, so I'll make an introduction to Mitar so he can take the lead on setting this up.

**Comment by b-long** [comment]
+1

**Comment by mitar** [comment]
Done with #124. We have it here: http://opencollective.com/blaze

**Comment by mitar** [comment]
We can edit language on the site, try a background image or add a gif. So if anyone has any suggestions, feel free to propose.

**Comment by aadamsx** [comment]
Are the expenses going to be listed on the collective?  Who's going to manage that?

**Comment by mitar** [comment]
All expenses are publicly listed there. I do not yet know how managing works. I think contributors can submit expenses and then somebody (other contributors?) approve them? Or they get approved automatically.

Currently I am the only contributor added. But I am pretty open to add anyone who is willing to regularly contribute to the project.

But I think for now we should be probably spending money on things which are non-work. Like resources we might need (domain name? we could reimburse the person who bought it).

But again, like with the rest of things I am doing with Blaze, I am trying just to provide resources for community to operate. How then community uses them we will see.
