### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#62]
They are failing now: https://circleci.com/gh/meteor/blaze/38

```
Error: Depending on unknown package spacebars-compiler
```

Maybe now that those packages were removed from Meteor?

**Comment by mitar** [comment]
@tmeasday, you are paying for CircleCI? Could you reach to them to enable matrix support on Blaze repository. On [Twitter they are saying this is possible](https://twitter.com/circleci/status/631196534483341313). (Then I can run tests against Meteor devel and Meteor stable in different containers.)

**Comment by mitar** [comment]
See [build matrix documentation](https://docs.travis-ci.com/user/customizing-the-build#build-matrix) on Travis CI for what a matrix is.

**Comment by tmeasday** [comment]
You probably just need to grab the submodule for the checked-out meteor.

**Comment by tmeasday** [comment]
You could just use travis?

**Comment by mitar** [comment]
> You probably just need to grab the submodule for the checked-out meteor.

What you mean here? Submodule?

> You could just use travis?

Ah, but I already have nice integration with CircleCI. Like report tests, parallelism. Only matrix is missing.

**Comment by tmeasday** [comment]
`meteor/meteor` now includes `meteor/blaze` as a submodule for isopackets.

If you are just testing checked out `devel` and the current recommended release, I think you could just use circle's parallelism pretty easily (like is `CIRCLE_NODE_INDEX` odd or even, for instance)?

**Comment by mitar** [comment]
> meteor/meteor now includes meteor/blaze as a submodule for isopackets.

But I run git clone with recursive, so I should get them.

> If you are just testing checked out devel and the current recommended release, I think you could just use circle's parallelism pretty easily (like is CIRCLE_NODE_INDEX odd or even, for instance)?

I use that to decide which packages to test. :-) This might then become more complicated then.

But they are saying that have matrix, one should just contact them. :-)

**Comment by tmeasday** [comment]
Well go for it, I don't think they know/care that you aren't an MDG employee, given the repo is on the `meteor` org.

**Comment by tmeasday** [comment]
> But I run git clone with recursive, so I should get them.

If you say so, I'm pretty sure that's what's going on though.

**Comment by mitar** [comment]
> If you say so, I'm pretty sure that's what's going on though.

I mean, it is here: https://github.com/meteor/blaze/blob/master/circle.yml#L13

**Comment by mitar** [comment]
But yes, current error is strange. Not sure why there are sometimes missing symbols.

**Comment by tmeasday** [comment]
I mean, yeah I believe you that you are cloning w/ submodules. But I'm pretty confident that's the error you get when the submodule isn't there.

**Comment by tmeasday** [comment]
Or, to rephrase: if you are missing the submodule, you get that error. I guess it's possible you could get that error some other way, but it seems like the most likely explanation.

**Comment by mitar** [comment]
Done. It seems it was a combination of trying to run tests also using current stable Meteor, and using parallelism which seems to break because of the CDN issues. So currently we are not using any parallelism and we are waiting for current `devel` branch to get released.

**Comment by funkybunky** [comment]
I'm getting the same error after simply forking the repo and trying to run from `devel`.

**Comment by mitar** [comment]
Can you explain a bit more what you are doing?

They are passing online. So maybe open a new issue with more precise explanation.

**Comment by akvadrako** [comment]
Me too. Just a git clone from the devel branch and ./meteor --help doesn't work.
