### ISSUE TITLE
Improve our documentation

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#66]
We have now documentation in the repository, but there are many things to improve. Some:
* [x] links to source code from documentation do not work
* [x] API docs are missing
* [x] links in API docs are pointing to Meteor repository
* [x] landing page is duplicating the README file of this repository, I think we should decide where should be main content and then the other should point to it (I think we should put content of README into docs and then README should be very thin and just point to docs)
* [x] Improve the layout, use the same theme and style of the "Meteor Docs" (submodule)

**Comment by b-long** [comment]
Relates to https://github.com/meteor/blaze/issues/70

**Comment by alexandesigner** [comment]
Fix links to source

- [ ] links to source code from documentation do not work

**Comment by mitar** [comment]
Thanks!

**Comment by mitar** [comment]
Now blaze.js is automatically published every time when tests on master branch pass on CircleCI.

**Comment by alexandesigner** [comment]
@mitar  had the liberty of adding a few more tasks to improve the documentation.

In a second step, we can differentiate the landing page of the documentation ... We need a landing page more expressive with a marketing footprint. _(Not that we're thinking of "market" but to make it more attractive for new developers.)_

Maybe the @kdanninger can help us with this In addition, I think it's very important we have a tutorial or perhaps some examples for those just starting out. What do you think?

**Comment by kdanninger** [comment]
@mitar very cool. glad to see continuous integration for production.

@alexandesigner I'm happy to help where i can :) if you'd like to get something started, I can help wherever needed.

**Comment by mitar** [comment]
I completely agree with the things above.

But first I would like to deduplicate the content. Now that we have API integrated into the site, we have one more level case of duplication of a lot.

**Comment by alexandesigner** [comment]
> But first I would like to deduplicate the content. Now that we have API integrated into the site, we have one more level case of duplication of a lot.

I made several changes to a PR https://github.com/meteor/blaze/pull/85 of these changes would be exactly correct this duplication of readme
