### ISSUE TITLE
Depend on values using Minimongo and getters

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#69]
So modern browsers support JavaScript getters. One issue currently is that when you are doing Minimongo queries you have to limit reactivity only to fields you care. But the issue is that where you make a query (code) is different from where you use it, so it is hard to keep those two in sync. By using getters (I think this is how vue.js is doing as well) we can register dependencies on fields dynamically.

I think this is pretty straightforward to do (using a custom transform around Minimongo), but I am not sure if it has already been done. Any packages around for this?

In any case, I think it would be very powerful for Blaze, because it would lower autorun reruns.

Data context could be similarly converted with getters.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
