### ISSUE TITLE
Align Blaze 2.x with WebComponents standards

### ISSUE THREAD

**Issue by brylie** [meteor/blaze#71]
An idea which has been discussed previously would be to move Blaze 2.x into alignment with [WebComponents](http://webcomponents.org) standards. This would include atleast the following:
- Allowing [custom HTML elements](http://w3c.github.io/webcomponents/spec/custom/)
- Modifying the [`<template>` element](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element)
- Using [WebComponent lifecycle callbacks](https://www.w3.org/TR/2013/WD-components-intro-20130606/#lifecycle-callbacks)
- considering adopting a [shadow DOM](http://w3c.github.io/webcomponents/spec/shadow/) polyfill
# Blaze 2.x roadmap

What are some other considerations related to putting WebComponent support on the Blaze 2.x roadmap?
# References
## Related Blaze issues
- [[IDEA] Components represented as HTML elements rather than spacebars syntax.](https://github.com/meteor/blaze/issues/58)
## Meteor forums
- [Add first-class support for WebComponents (e.g. Blaze 2)](https://forums.meteor.com/t/add-first-class-support-for-webcomponents-e-g-blaze-2/18323)
- [Polymer + Meteor Support With meteor webcomponents packages](https://forums.meteor.com/t/polymer-meteor-support-with-meteor-webcomponents-packages/20536)
- [Polymer 1.0 paper-drawer-panel not rendering well with Blaze](https://forums.meteor.com/t/polymer-1-0-paper-drawer-panel-not-rendering-well-with-blaze/5502)
## Meteor packages
- Discussion on peerlibarary:blaze-components [Issue #14](https://github.com/peerlibrary/meteor-blaze-components/issues/14)
- [mwc:synthesis](https://github.com/meteorwebcomponents/synthesis)

**Comment by mitar** [comment]
I think custom HTML elements are already supported? I am using them in my apps.

What is "Modifying the element"?

I am not exactly sure if I understand what is needed from Blaze to use web components? Or what exactly are you proposing here.

**Comment by brylie** [comment]
Sorry, the `<template>` markup was stripped out.

**Comment by brylie** [comment]
Basically, when developing with Blaze, we are writing code and templates that is specific mainly to Blaze. This discussion proposes modifying the Blaze component model to align with WebComponents standards, so that writing Blaze code would be very similar to writing a general purpose WebComponent.

**Comment by mitar** [comment]
I was looking into this a year ago or something and my conclusion was that I do not get why would you then even use Blaze? What does Blaze give you which you cannot then simply just use web components? So why then not just write web components?

**Comment by brylie** [comment]
Well, things I like about Blaze are
- ease of use
- reactive template helpers
- template autorun
- instance subscriptions

I think it is worth discussing where WebComponents and Blaze could be compatible initiatives, and consider aligning Blaze towards WebComponents where the is functional similarity.

**Comment by mitar** [comment]
See also: https://github.com/peerlibrary/meteor-blaze-components/issues/14

**Comment by brylie** [comment]
Thanks for the link to that discussion. I added it to the resources section above as well.

**Comment by necmettin** [comment]
From _modifying the Blaze component model_, I understand trying to make Blaze look and behave like WebComponents, converting Blaze code to WebComponents code behind the scenes. Is that right?

If I'm way off below, forgive my ignorance.

We already have something working, is easy and beautiful. Why are we trying to make it look like or behave like something else?

Subjectively speaking, Blaze is much more beautiful and easy to write in than WebComponents. Blaze is much more beautiful and easy to write in than anything else. Trying to make it look or behave like something else (imho) would defeat the purpose of this whole endeavour.

Also, correct me if I'm mistaken, but WebComponents are not supported in IE10 and below.

**Comment by mitar** [comment]
> We already have something working, is easy and beautiful. Why are we trying to make it look like or behave like something else?

This are also my thoughts. I do not think it is possible really to make one project fit everyone's needs and wishes. And this is why there are different technologies around. You pick the one you prefer. As such Blaze should stay faithful to those who prefer it over React, Web Components and so on.

On the other hand, if we can make it easier to interoperate with other systems, without loosing too much on code complexity and performance, why not. I know that I will not be spearheading this, but if somebody makes a good pull request, I think it is a valid change.

**Comment by brylie** [comment]
> We already have something working, is easy and beautiful. Why are we trying to make it look like or behave like something else?

The main goal would be standards alignment, so that WebComponents gain traction and Blaze components are portable across projects.

> Blaze is much more beautiful and easy to write in than WebComponents.

The WebComponents standard is collectively defined, so we can enhance the standards by participating in their development.

**Comment by stubailo** [comment]
I don't think anyone in the UI framework community except polymer people are excited about web components. I think it would be a waste of time to try to chase that standard.

**Comment by necmettin** [comment]
> The main goal would be standards alignment, so that WebComponents gain traction and Blaze components are portable across projects.

Standards alignment is nice and all, but
1) WebComponents and Blaze are different beasts, with different purposes and behaviour models.
2) converting Blaze into WebComponents would destroy Blaze's beauty and simplicity altogether.

> The WebComponents standard is collectively defined, so we can enhance the standards by participating in their development.

Being 'collectively defined' is not a valid argument to make Blaze look and feel like something else. We are here because we love how Blaze looks and feels. Making it look like WebComponents would make it a WebComponents implementation. It wouldn't be Blaze anymore.

**Comment by brylie** [comment]
> WebComponents and Blaze are different beasts, with different purposes and behaviour models.

@necmettin how are they different? Do they need to remain different, or is there some possibility of alignment?

>  I don't think anyone [is] excited about web components. I think it would be a waste of time to try to chase that standard.

@stubailo as you indeed know, we have standards such as ES, HTML, CSS, SVG, etc. to align our work and stop reinventing things and fragmenting the developer community. The WebComponents offers a unifying proposal and is emerging from the same standards body (W3C) that maintains HTML, CSS, SVG, etc.. 

Fortunately, projects such as [Vue.js](http://vuejs.org/) and [Riot.js](http://riotjs.com/) recognize the importance of standards, and are building solutions to balance simplicity and standards alignment. Blaze can balance simplicity and standards alignment, staying true to its beauty while joining the standards track. 

All I am proposing is that we look to WebComponents, rather than ignore or deride it, while evolving the Blaze API.

**Comment by mitar** [comment]
@brylie: I think the best way to achieve this is if you can provide concrete examples of what would have to be changed. Then it would be much easier to talk concrete things than just currently where I think many are responding with "oh, more work, for unclear benefit, or even for destroying the current beauty". I think none of us are really using web components, we are just using Blaze, so it is hard for us to gauge how much work would it take and how much changes to Blaze. If you think things can work without changing Blaze to much for those who prefer just Blaze, I think it would be the best if you can propose those concrete changes, and later on even code implementing those changes.

**Comment by brylie** [comment]
## Practical changes
@mitar at least two changes, or overlapping features, have been mentioned:

- supporting the same [lifecycle callbacks](https://www.w3.org/TR/2013/WD-components-intro-20130606/#lifecycle-callbacks) as the WebComponents spec
- use of `<template>` to define Blaze components
  - right now [Blaze's use of `<template>` conflicts with WebComponents](https://github.com/meteor/meteor/issues/2765) libraries such as Polymer
- ability to use Blaze components as [custom elements](http://w3c.github.io/webcomponents/spec/custom/) ([see discussion](https://github.com/peerlibrary/meteor-blaze-components/issues/14))

## Community interest in WebComponents
@stubailo regarding community interest in WebComponents, an ]interview with Travis Leithead](http://webcomponents.org/articles/interview-with-travis-leithead/) mentioned that: 

> in the top 10 of [Microsoft] Edge’s User Voice poll... Numbers two through five are the Web Component specs and the first one is about updating our browser so that everyone is using the most modern version.

That [top voted requests remain largely the same](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/filters/top).

## Browser support
The second point above speaks to the browser support horizon for WebComponents.

There are several projects from prominent organizations which are developing libraries based on the WebComponents specifications with various levels of browser support:

- [X-Tag](http://x-tag.github.io/) is a Microsoft supported, open source, JavaScript library that wraps the W3C standard Web Components. X-Tag has good browser support as well:
  - Edge (all versions and devices), Internet Explorer 9+
  - Firefox (all versions, devices, and platforms)
  - Chrome (all versions, devices, and platforms), Android 4+ stock browser
  - Safari Mac, Safari iOS 5+
  - Opera 11+ (all devices and platforms)
- [Bosonic](http://bosonic.github.io/) has wide browser support, and plans to support IE 9+

**Comment by mitar** [comment]
I must say that I do not understand what would same lifecycle callbacks help, but you already have all those three callbacks inside Blaze, Blaze Components exposes them as:
* insertedCallback -> insertDOMElement
* readyCallback -> onReady
* removedCallback -> removeDOMElement

> use of `<template>` to define Blaze components

So are you talking about the fact that you cannot use `<template>` inside HTML files in Meteor because Blaze tries to parse them and it fails because it is not a valid Blaze template? But why would you put a Web Components `<template>` into a Blaze file? It is not served as HTML to the client. I think you have to simply define your own extension, like `.web.html` which would then deliver that HTML as it is to the client, so that it can be used on the client as a Web Components `<template>`. That is pretty straightforward to do, but it is not related to Blaze.

And I do not know why would you want to mix both Web Components `<template>`s and Blaze `<template>`s in the same file. This would probably lead to a lot of confusion.

**Comment by mitar** [comment]
You can probably simply do `addAssets` on the HTML file with web components and this is it? Problem solved.

**Comment by brylie** [comment]
One problem with the `<template>` usage is that it has [caused errors when even starting a project with Blaze and Polymer in the codebase](https://github.com/meteor/meteor/issues/2765).

**Comment by necmettin** [comment]
Could you provide an example as to what Blaze will finally look like? I believe abstract discussions can drag for days without concrete examples.

**Comment by brylie** [comment]
Blaze components would start to resemble custom HTML elements. The underlying API would follow the WebComponents standard, including lifecycle callbacks, code structure, HTML imports, scoped CSS, etc. Here is an example from the Polymer project:

```html
    <dom-module id="element-name">

      <template>
        <style>
          /* CSS rules for your element */
        </style>

        <!-- local DOM for your element -->

        <div>{{greeting}}</div> <!-- data bindings in local DOM -->
      </template>

      <script>
        // element registration
        Polymer({
          is: "element-name",

          // add properties and methods on the element's prototype

          properties: {
            // declare properties for the element's public API
            greeting: {
              type: String,
              value: "Hello!"
            }
          }
        });
      </script>

    </dom-module>
```

**Comment by brylie** [comment]
Matt DeBergalis also made a [relevant comment](https://www.youtube.com/watch?v=Mooqax2uJ40&feature=youtu.be&list=PLTUf4ytkmI8TtmPN-lxhji5DbJBvLdVrA&t=1802) recently:

> To be successful; to be something that everybody can learn, it's got to be based on standards. And, a lot of what made Meteor really easy in the earliest days was possible because there weren't any standards to worry about. That just isn't the case anymore.

By aligning Blaze with the WebComponents standards track, we might reach towards Matt's prize and *meet the constraints of real world software development while providing a great developer experience*.

**Comment by necmettin** [comment]
I've always thought of Blaze as a templating engine before anything else. It gave me the templating logic I know and love from all the other languages I've used. Combined with the events logic that resembled jQuery and the helpers logic that let me provide / transform relevant data, Blaze was simple and simply beautiful.

You realize of course, that this looks nothing like Blaze. This is not a templating engine. This is an HTML components engine. What's more, any solution to any problem (especially in coding) has its own problems. It's not like this _standards_ way is perfect.

If we modify Blaze to conform these standards, we are essentially taking on a different set of problems. If we try to maintain _the Blaze way_ with _the standards way_, we will have practically doubled the maintenance costs.

As long as I can choose between the Blaze way and the standards way, I wouldn't mind having this option, but it must be an _option_. It's just that the Blaze way is much more (_any positive adjective here_) for me. Just my two cents.

**Comment by stubailo** [comment]
> @stubailo as you indeed know, we have standards such as ES, HTML, CSS, SVG, etc. to align our work and stop reinventing things and fragmenting the developer community.

As a web developer (and in the Blaze community, that's all I am, so you shouldn't take my opinions more seriously than anyone else's), I can't see this particular standard making life better for me. Every templating and component library I've used before makes more sense to me than the proposed Web Components standard, at least for my use cases.

**Comment by stubailo** [comment]
Never thought I'd say this, but Tom Dale makes the point perfectly in his Medium post today: https://medium.com/@tomdale/javascript-frameworks-distribution-channels-for-good-ideas-9f3b95c0e293#.pntbkx7hl

**Comment by mitar** [comment]
So the syntax you are proposing above is what I think what could be done in a similar way how Jade compiles down to Blaze. We do not have to change Blaze in my opinion to accommodate this. But yes, it would be interesting to see somebody create such a wrapper around. I would be open to add to Blaze integration points to make this happen, if some is missing (I think they are probably all there already).

**Comment by mitar** [comment]
> One problem with the `<template>` usage is that it has [caused errors when even starting a project with Blaze and Polymer in the codebase](https://github.com/meteor/meteor/issues/2765).

Only if you want to use Polymer in `.html` Blaze template files. But why would you want to use that? You should have a file extension for that.

Or are you saying that you have a use case for:

```html
<template name="foo">
   <template><!-- web components template --></template>
</template>
```

And that this does not work?

**Comment by brylie** [comment]
> Only if you want to use Polymer in .html Blaze template files. But why would you want to use that? You should have a file extension for that.

Perhaps part of the problem is that Blaze templates should be distinguished from HTML. Therein may be where Blaze and WebComponents slightly conflict, since WebComponents are targeting browser support while Blaze is more of a pre-processing/templating language.

**Comment by mitar** [comment]
Yes, so you should add static files with `addAssets`?

**Comment by brylie** [comment]
# Concerns
> I believe abstract discussions can drag for days without concrete examples.
>
> -- @necmettin

Lets briefly explore several concerns, raised throughout this discussion. We can agree not to drag out the high level topics for too long.

## Costs / benefits
> If we try to maintain the Blaze way with the standards way, we will have practically doubled the maintenance costs.
>
> -- @necmettin 

As @necmettin mentioned, we can consider development costs of evolving the Blaze 2.x component model and API. Types of costs to consider, include:

- developer experience
  - learning
  - efficiency
  - maintenance
- user experience
  - time to load
  - natural feel

### Framework fatigue
>  I do not think it is possible really to make one project fit everyone's needs and wishes. And this is why there are different technologies around.
>
> -- @mitar 

Developer needs and choices differ. As a result, there are many tools and frameworks working in similar ways. As an effect, many people have discussed [framework/library proliferation](https://www.google.fi/search?q=javascript+framework+fatigue), [costs](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/) and [coping strategies](http://teropa.info/blog/2015/07/15/overcoming-javascript-framework-fatigue.html).

> A recurring theme that we see over and over is that wherever the web as a development platform has failed us, wherever there are holes or annoying deficiencies, we see an amazing thing happen. We see this vibrant web developer ecosystem rise up and solve all these problems in user space. 
>
> So, these [solutions] often take the form of new libraries, and tools, and JavaScript frameworks that all kind of layer on top of the [Web Platform]. And on the one hand this is awesome, because it allows us to get our jobs done. And, without waiting for the Web Platform to catch up, we can get our app shipped to our users today. But it's also good, from time to time, to take a step back and realize that a lot of these layers that we pile onto the platform, and start to take for granted, actually have real costs.
>
> So some of these costs come in the form of developer complexity. We've drifted a long way away from where we could just edit some HTML and refresh it in the web browser, to a world where starting a new project usually means wading through a sea of complicated choices, setting up really complex toolchains, and cobbling together something that hopefully is going to result in something good at the end.
>
> But more than the developer experience, as we're layering and layering on to the platform, inevitably this takes a toll on the user experience as well.
>
> -- Kevin Schaaf (@kevinpschaaf) [Progressive, Performant, Polymer: Pick Three - Google I/O 2016](https://www.youtube.com/watch?v=J4i0xJnQUzU)

### Evolution and innovation
> Never thought I'd say this, but Tom Dale makes the point perfectly in his [Medium post](https://medium.com/@tomdale/javascript-frameworks-distribution-channels-for-good-ideas-9f3b95c0e293#.pntbkx7hl) today
>
> -- @stubailo 

Frameworks, libraries, build tools, etc. are essential for the evolution of our industry. 

The Web Platform is also evolving to serve common needs:

> HTML provide[s] a set of tags that were great for marking up documents, but not so great for building applications.
>
> Over the years, we've used JavaScript to fill this gap. We've invented clever models for structuring our apps, built libraries and frameworks to implement them, and layered lots of other useful features on top. We've also constructed elaborate tool chains to build and serve and bundle and split our JavaScript code. These innovations have filled the gaps in the web platform, but they've also added cost in the form of complexity, developer lock-in and JavaScript overhead.
> Fortunately, the web platform is evolving to meet these challenges:
>
> - Thanks to [Web Components](http://webcomponents.org/), developers have a way to extend HTML itself: to unlock the powerful component model that's baked directly into the browser and build an application out of granular, low-overhead components.
>
> - Thanks to [HTTP/2](https://http2.github.io/), developers have a way to efficiently deliver granular dependencies over the network without incurring the high overhead of multiple round-trips.
>
> - Thanks to [Service Worker](http://www.html5rocks.com/en/tutorials/service-worker/introduction/), developers have a way to reliably cache these granular components, to ensure their web applications can still function and perform reliably even in flaky network conditions.
>
> -- [Polymer at Google I/O 2016](https://www.polymer-project.org/1.0/blog/2016-05-19-Polymer-IO-2016)

The Web Platform is designed to offer common base features, so we can focus development efforts on 'higher level' challenges. Eventually, higher level patterns and solutions would ideally enter the Web Platform portfolio as new or evolved specifications.

## Perfection
> any solution to any problem (especially in coding) has its own problems. It's not like this standards way is perfect.
>
> -- @necmettin 

We agree that our work to improve the developer and user experience is not perfect. There are trade-offs to any solution -- we rule out choices when making decisions.

The aim of this discussion is to steer us towards the Web Platform community process.

## Simplicity and elegance

> [Blaze] is easy and beautiful.
>
> As long as I can choose between the Blaze way and the standards way, I wouldn't mind having this option, but it must be an option.
>
> -- @necmettin 

@necmettin describes two of the best parts of Blaze, simplicity and choice.

Developer choice is important, and the choice isn't *binary*. It is possible to use WebComponents as a base while adding the syntactic sugar to preserve the Blaze developer experience.

## Browser compatibility
> WebComponents are not supported in IE10 and below.
>
> -- @necmettin 

As @necmettin points out, we have to acknowledge the shifting browser landscape. WebComponents, and [Web Platform features](https://platform.html5.org/) in general, have mixed browser support and may not be compatible with older browsers.

At some point, browsers must be retired, and community projects may decide to drop support for legacy browsers. This has been the case with several prominent projects:

### Bootstrap
> Bootstrap supports the latest, stable releases of all major browsers and platforms. On Windows, we support Internet Explorer 9-11 / Microsoft Edge.
> [Bootstrap Browsers and devices](http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/) page

### jQuery
> While jQuery might run without major issues in older browser versions, we do not actively test jQuery in them and generally do not fix bugs that may appear in them.
> [jQuery Browser Support](https://jquery.com/browser-support/)

### Lodash
> Tested in Chrome 51-52, Firefox 47-48, IE 11, Edge 14, Safari 8-9, Node.js 4-6 & PhantomJS 2.1.1. [Lodash home page](https://lodash.com/)

### Microsoft
> Beginning January 12, 2016, only the most current version of Internet Explorer available for a supported operating system will receive technical supports and security updates. Internet Explorer 11 is the last version of Internet Explorer, and will continue to receive security updates
> [Support for older versions of Internet Explorer ended ](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support)

### React
> React DOM will continue to support IE 9 and above for the foreseeable future.
> [Discontinuing IE 8 Support in React DOM](https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html)

# Some proposed changes
> If you think things can work without changing Blaze to much for those who prefer just Blaze, I think it would be the best if you can propose those concrete changes, and later on even code implementing those changes.
>
> -- @mitar 

## ES classes
We can allow an ES2015 class-based definition. E.g. used by [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) and [Polymer](https://www.polymer-project.org).

### Blaze Components example
[Blaze components](https://github.com/peerlibrary/meteor-blaze-components#components) use ESclass inheritance:

```js
class ExampleComponent extends BlazeComponent {
  // Life-cycle hook to initialize component's state.
  onCreated() {
    // It is a good practice to always call super.
    super.onCreated();
  }

  // Event handlers
  events() {
    // It is a good practice to always call super.
    return super.events().concat({
      // You could inline the handler, but the best is to make
      // it a method so that it can be extended later on.
      'click .increment': this.onClick
    });
  }

  onClick(event) {
   // Specific event handler
  }

  // Any component's method is available as a template helper in the template.
  customHelper() {
    // do something
  }
}

// Register a component so that it can be included in templates. It also
// gives the component the name. The convention is to use the class name.
ExampleComponent.register('ExampleComponent');
```

### Polymer example
[Polymer elements](https://www.polymer-project.org/1.0/docs/devguide/registering-elements) use ES class inheritance. See the [Polymer 2.x preview](https://www.polymer-project.org/1.0/blog/2016-09-09-polymer-2.0) component model:

> Polymer 2.0 will ... support an ES6 class-based way to define a custom element - letting you truly use the native web platform features without getting in your way.

```js
class MyElement extends Polymer.Element {
  static get is() { return ‘my-element’; }

  // lifecycle 'created' callback
  created: function() {
   // do something
  }

  static get config() {
    properties: {
      // element properties
    },
    observers: [
      // property change observers
    ]
  },
  
  listeners: {
    // event listeners
  },
  
  // specific event listener
  regularTap: function(e) {
    // do something
  }

  constructor() {
    super();
    …
  }
}
```

>The new Polymer.Element class extends from the native HTMLElement

See the [Polymer 2.x preview README](https://github.com/Polymer/polymer/blob/2.0-preview/README.md) for further details.

## HTML pre-processor
> the syntax you are proposing above is what I think what could be done in a similar way how Jade compiles down to Blaze.
>
> -- @mitar 

As @mitar has pointed out, Blaze is basically an HTML pre-processor. Lets find ways in which the Blaze syntax might interfere with Web Platform features. E.g. Custom Elements.

We can work to distinguish Blaze more clearly. 

### `<template>` tag
The Blaze `<template>` syntax has been discussed as causing conflicts with WebComponent libraries. It also may not conform to the HTML specification.

We can avoid using the HTML `<template>` element in a non-standard way. 

### File extension
Currently, Blaze templates are written using the *.html* extension. Since Blaze is not HTML, we recommend a specific file extention, such as *.blaze*.

# Clarifications

> Every templating and component library I've used before makes more sense to me than the proposed Web Components standard, at least for my use cases.
>
> -- @stubailo 

@stubailo, would you please describe some example use cases?

> I think custom HTML elements are already supported? I am using them in my apps.
>
> -- @mitar 

@mitar, would you please show an example of using custom HTML elements with Blaze, as reference?

> Yes, so you should add static files with addAssets?
>
> -- @mitar 

I am not sure, having not worked much with `addAssets`. What would be an example of using `addAssets` to load custom HTML element source(s)?

Please be patient with my lack of in-depth knowledge of the Blaze architecture, WebComponents specifications, etc. I am eager to learn.

**Comment by brylie** [comment]
Please be patient with my lack of in-depth knowledge of the Blaze architecture, WebComponents specifications, etc. I am eager to learn.

I am also sincerely grateful for the effort that has gone in to making Blaze so elegant.

**Comment by mitar** [comment]
> Please be patient with my lack of in-depth knowledge of the Blaze architecture, WebComponents specifications, etc. I am eager to learn.

Don't worry. We are all here to work together. Question are good. Pooking as well. :-)

> Currently, Blaze templates are written using the .html extension. Since Blaze is not HTML, we recommend a specific file extention, such as .blaze.

I do not think we can do that, it is backwards incompatible. Again, the question is that you probably do not want to process web components through Blaze anyway. You can also use [static-html](https://atmospherejs.com/meteor/static-html) for this as well. An example of a package which processes `.html` files differently. Maybe this is useful for web components?

> @mitar, would you please show an example of using custom HTML elements with Blaze, as reference?

See [here](https://github.com/peer/mind/blob/master/packages/peermind/base/editor.html#L7).

> I am not sure, having not worked much with addAssets. What would be an example of using addAssets to load custom HTML element source(s)?

I do not know if I can answer this because I do not know how you are supposed to be loading web components at all. :-)

**Comment by necmettin** [comment]
> ... we recommend a specific file extension, such as .blaze.

Although I seriously doubt this would be implemented (backwards incompatible), I would really love to see this. I have always thought that the .html extension would (although an understandable decision at the time) prove wrong in the long run. Pretty much every other templating language out there has its own extension (it should). So should Blaze. It would make things much easier for editors, editor extensions, and preprocessors (and pretty much anything else that wants to work on Blaze files); it would also be easier to distinguish a Blaze templating file from an actual HTML file.

This is probably a little off topic but maybe a way to achieve this could be merging the HTML and JS parts of Blaze under a single, .blaze extension? Instead of a folder that contains a .html and a .js, a .blaze that contains `<template name='x'>`, `Template.x.helpers({})`, and `Template.x.methods({})`? This way, we could also keep the .html extension.

**Comment by mitar** [comment]
So for merging code and template, see the proposal in #94. I think this is orthogonal from the question of the extension.

I think the question of an extension is a good one and I will open a different issue to discuss it.

**Comment by mitar** [comment]
I opened: #97.

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
