### ISSUE TITLE
Move spacebars documentation to blazejs.org as well

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#79]

**Comment by mrjones91** [comment]
Going ahead and attempting this. Does the Order field in each one of the page files correspond with where it appears in the left hand table of contents on the site?

**Comment by mitar** [comment]
No idea about ordering. @alexandesigner might know about this better.

@tmeasday, can you link to our blazejs.org also Spacebars documentation? (Once tests passed and it gets auto-deployed.) Is there any spacebars apibox which has to be moved as well?

**Comment by laosb** [comment]
@mrjones91 Yes, exactly.

**Comment by tmeasday** [comment]
Oh, this bit: http://docs.meteor.com/packages/spacebars.html ? Sure, it's just a Markdown file I think, should be easy enough to add.

**Comment by mitar** [comment]
We already added it: http://blazejs.org/spacebars.html

So you could link to it from Meteor docs.

@mrjones91: I do not see Spacebars linked anywhere from the front page/navbar. Could you add it? http://blazejs.org/

**Comment by tmeasday** [comment]
Done.

**Comment by mrjones91** [comment]
That was my question with the order field at the top of each .md file. I wasn't sure how the navbar generated a link to each section @mitar

**Comment by tmeasday** [comment]
Here: https://github.com/meteor/blaze/blob/master/site/_config.yml#L20
