### ISSUE TITLE
Whitespace control

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#88]
Handlebars [supports whitespace control](http://handlebarsjs.com/expressions.html#whitespace-control). I think we should support it in Blaze as well.

(Especially when Blaze is used for rendering text, not just HTML.)

**Comment by aadamsx** [comment]
The following is one of the examples, will you explain?

```handlebars
{{#each nav ~}}
  <a href="{{url}}">
    {{~#if test}}
      {{~title}}
    {{~^~}}
      Empty
    {{~/if~}}
  </a>
{{~/each}}
```

**Comment by mitar** [comment]
So instead of rendering:

```
  <a href="<url1>">
      <title1>
  </a>
  <a href="<url2>">
      <title2>
  </a>
  <a href="<url2>">
      <title2>
  </a>
```

It renders:
```
<a href="<url1>"><title1></a><a href="<url2>"><title2></a><a href="<url2>"><title2></a>
```

**Comment by msavin** [comment]
Maybe the bigger goal here is to align Blaze with Handlebars, and put Spacebars on the deprecation panel? That way, we can just go by their standard instead of debating how to do things.

**Comment by stubailo** [comment]
> That way, we can just go by their standard instead of debating how to do things.

I wouldn't go so far as to call handlebars a "standard", IMO their syntax is pretty janky.

**Comment by mitar** [comment]
> Maybe the bigger goal here is to align Blaze with Handlebars, and put Spacebars on the deprecation panel? That way, we can just go by their standard instead of debating how to do things. 

I always thought that Spacebars is pretty aligned already? So I would not change the implementation details, but I would go into direction of using their syntax, yes.

> I wouldn't go so far as to call handlebars a "standard", IMO their syntax is pretty janky.

I do not think that non-janky is a requirement for standard. Standard just means that it is defined and somebody uses it. :-) We will make it a standard by using it. :-)

**Comment by mitar** [comment]
One good reason for using their syntax is that then syntax coloring will be easier to be supported. (One will be able to reuse existing coloring definitions to make a definition for `.blaze`.)

**Comment by msavin** [comment]
Does anyone know how open the handlebars community is to making changes? Perhaps we can help them iron out some of the issues. I suppose they would be interested as Blaze could like the first big view layer built around

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
