### ISSUE TITLE
#each ... of syntax

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#90]
I propose that we introduce also `#each ... of` syntax to iterate over objects.

**Comment by stubailo** [comment]
What's the ordering? Same as JS?

**Comment by mitar** [comment]
I would have the same as JS, but you are right that this is undefined. Hmm. Maybe it is a bad idea. :-) Maybe it is easier to leave this out of Blaze, and leave it to users to have their own helpers which convert and object to an array in any any way user wants.
