### ISSUE TITLE
blazejs.org website down; Meteor Guide links broken

### ISSUE THREAD

**Issue by brylie** [meteor/blaze#92]
While trying to browse the Blaze documentation, via the Meteor Guide, I noticed that blazejs.org does not seem to be serving the documentation. Is this intentional? What are the plans for blazejs.org / Blaze documentation?

- http://blazejs.org/blaze.html
- http://docs.meteor.com/packages/spacebars.html
- http://docs.meteor.com/api/blaze.html

# Related issue
#77 - multiple versions of Blaze docs: [mentions that Blaze documentation is transitioning to S3](https://github.com/meteor/blaze/issues/77#issuecomment-245824057)

**Comment by mitar** [comment]
This is just temporary while DNS is refreshing cache. We are moving documentation from GitHub pages to Amazon S3.

Thanks for the report.

**Comment by brylie** [comment]
Jep. Thanks for working on the docs :-)

**Comment by mitar** [comment]
OK, it started resolving with Google's DNS for me.
