### ISSUE TITLE
WebReflection Custom Elements v1 polyfill from NPM breaks Meteor app.

### ISSUE THREAD

**Issue by trusktr** [meteor/blaze#95]
Originally posted at https://github.com/meteor/meteor/issues/7736 and https://github.com/WebReflection/document-register-element/issues/72, but the stack trace seems to be related to Blaze/templating, so I'm opening a third issue here.

I have only the following single line of code in my app,

```js
import 'document-register-element'
```

which causes this error:

![screen shot 2016-08-30 at 1 43 29 am](https://cloud.githubusercontent.com/assets/297678/18082411/a825c518-6e53-11e6-9eeb-a16e79e953b5.png)

Reproduction:

```sh
git clone git@github.com:trusktr/meteor --branch issue-7736 --single-branch
cd meteor
./run-dev.sh
```

**Comment by trusktr** [comment]
Hello Mitar, this is a funky bug, because I'm not sure who's at fault (maybe no one). It seems like something in Meteor (Blaze/templating) and something in @WebReflection's polyfill accidentally clash with each other.

**Comment by WebReflection** [comment]
If both libraries extend natives we need to coordinate on how. My poly
inevitably needs to do that. What about Meteor?

**Comment by stubailo** [comment]
What is the issue here? What is being overridden and conflicting? I feel like there isn't enough info here to find the root of the issue, other than "these two libraries don't work together".

**Comment by trusktr** [comment]
@stubailo It's not just "two libraries" per se: Meteor is a popular and widely adopted web framework built on web technology, while WebComponents are an important new part of the future of web technology. It's important for a framework like Meteor to care about WebComponents polyfills working in order to promote the very future of the platform on which Meteor itself thrives.

> What is the issue here? What is being overridden and conflicting?

That we haven't found out yet.

**Comment by trusktr** [comment]
Note: after importing the polyfill as in the reproduction, a Meteor app fails to render anything.

**Comment by trusktr** [comment]
Fixed in https://github.com/WebReflection/document-register-element/commit/a80ccede63d1cc2be1d0108e0bbd24e7e2c2bc18

**Comment by mitar** [comment]
@trusktr: Can you expand on what was a problem?

**Comment by WebReflection** [comment]
@mitar you define a global object with a tag name: `HTML`

This was interfering with a filter that was looping through classes and tags and patching your object instead of the tag/class.

I've fixed on my polyfill the issue but I think meteor should stick with its own namespace or at least don't chose valid tag names / known names for its global pollution.

`MtHTML` or anything else wouldn't have conflicted with anything I know ;-)

**Comment by mitar** [comment]
Hm, Blaze should not be exposing any global symbols? Are you sure? Do you know where it is coming from?

**Comment by trusktr** [comment]
@mitar It's coming from https://github.com/meteor/blaze/blob/master/packages/htmljs/preamble.js

**Comment by mitar** [comment]
That one is not a global variable. This is how Meteor wraps it when building the package:

```
/* Imports */
var Meteor = Package.meteor.Meteor;
var global = Package.meteor.global;
var meteorEnv = Package.meteor.meteorEnv;
var Tracker = Package.tracker.Tracker;
var Deps = Package.tracker.Deps;

/* Package-scope variables */
var HTML, IDENTITY, SLICE;

(function(){

////////////////////////////////////////////////////////////////////////////////////////
//                                                                                    //
// packages/htmljs/preamble.js                                                        //
//                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////
                                                                                      //
HTML = {};                                                                            // 1
                                                                                      // 2
IDENTITY = function (x) { return x; };                                                // 3
SLICE = Array.prototype.slice;                                                        // 4
                                                                                      // 5
////////////////////////////////////////////////////////////////////////////////////////

}).call(this);
```

**Comment by mitar** [comment]
But, it is in `global-imports.js`:

```
HTML = Package.htmljs.HTML;
```

So when app uses Blaze on app-level the global symbol is exposed, true.

**Comment by trusktr** [comment]
Yeah, that was it. document-register-element is not touching that global now, so at least all works for me. Would be nice to transition Blaze to Es6, avoiding globals, at some point. It's work though.

**Comment by mitar** [comment]
Again, this has nothing with ES6 or globals and Blaze. They are not globals. They are something apps by configuration by default import into a global namespace. You can remove blaze from your global packages and it will go away. The problem here is that this is a Meteor default.

So yes, Meteor should maybe change so that there is no need for globals to be defined at all, but Blaze does not have to change at all to support that. So feel free to open an issue with Meteor here.
