### ISSUE TITLE
Make Templates an extendable class

### ISSUE THREAD

**Issue by mitar** [meteor/blaze#98]
- [ ] change Blaze templates to be nicely extendable JavaScript classes
- [ ] move resolving of `this` and any symbols to methods of a class instead of a statically defined methods on `Template`
- [ ] add life-cycle and some other methods to this base Blaze class, a bit like Blaze Components
- [ ] add a method which prepares a data context (so that we can do data context validation, or custom equality on the data context, or replace it with reactive dict, or disable it all together)
- [ ] have a method for lookup, migrated from https://github.com/meteor/meteor/issues/5577

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
